// Auto-generated ayah highlights for SPOT_IN_QURAN activities
// Source: api.alquran.cloud (Uthmani script)
// Generated: 2026-02-16
// Only includes words where the EXACT taught form appears.

export interface AyahHighlightSeed {
  wordOrderIndex: number;
  surahName: string;
  surahNum: number;
  ayahNum: number;
  arabicText: string;
  highlightStartIndex: number;
  highlightEndIndex: number;
}

export const AYAH_HIGHLIGHTS: AyahHighlightSeed[] = [
  {
    wordOrderIndex: 48,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 4,
    arabicText: 'مَٰلِكِ يَوْمِ ٱلدِّينِ',
    highlightStartIndex: 8,
    highlightEndIndex: 14,
  },
  {
    wordOrderIndex: 108,
    surahName: 'Al-Anbiya',
    surahNum: 21,
    ayahNum: 35,
    arabicText: 'كُلُّ نَفْسٍۢ ذَآئِقَةُ ٱلْمَوْتِ ۗ وَنَبْلُوكُم بِٱلشَّرِّ وَٱلْخَيْرِ فِتْنَةًۭ ۖ وَإِلَيْنَا تُرْجَعُونَ',
    highlightStartIndex: 0,
    highlightEndIndex: 5,
  },
  {
    wordOrderIndex: 33,
    surahName: 'Maryam',
    surahNum: 19,
    ayahNum: 30,
    arabicText: 'قَالَ إِنِّى عَبْدُ ٱللَّهِ ءَاتَىٰنِىَ ٱلْكِتَٰبَ وَجَعَلَنِى نَبِيًّۭا',
    highlightStartIndex: 13,
    highlightEndIndex: 19,
  },
  {
    wordOrderIndex: 123,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 125,
    arabicText: 'وَإِذْ جَعَلْنَا ٱلْبَيْتَ مَثَابَةًۭ لِّلنَّاسِ وَأَمْنًۭا وَٱتَّخِذُوا۟ مِن مَّقَامِ إِبْرَٰهِۦمَ مُصَلًّۭى ۖ وَعَهِدْنَآ إِلَىٰٓ إِبْرَٰهِۦمَ وَإِسْمَٰعِيلَ أَن طَهِّرَا بَيْتِىَ لِلطَّآئِفِينَ وَٱلْعَٰكِفِينَ وَٱلرُّكَّعِ ٱلسُّجُودِ',
    highlightStartIndex: 17,
    highlightEndIndex: 26,
  },
  {
    wordOrderIndex: 94,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 151,
    arabicText: 'سَنُلْقِى فِى قُلُوبِ ٱلَّذِينَ كَفَرُوا۟ ٱلرُّعْبَ بِمَآ أَشْرَكُوا۟ بِٱللَّهِ مَا لَمْ يُنَزِّلْ بِهِۦ سُلْطَٰنًۭا ۖ وَمَأْوَىٰهُمُ ٱلنَّارُ ۚ وَبِئْسَ مَثْوَى ٱلظَّٰلِمِينَ',
    highlightStartIndex: 106,
    highlightEndIndex: 117,
  },
  {
    wordOrderIndex: 148,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 57,
    arabicText: 'قُلْ إِنِّى عَلَىٰ بَيِّنَةٍۢ مِّن رَّبِّى وَكَذَّبْتُم بِهِۦ ۚ مَا عِندِى مَا تَسْتَعْجِلُونَ بِهِۦٓ ۚ إِنِ ٱلْحُكْمُ إِلَّا لِلَّهِ ۖ يَقُصُّ ٱلْحَقَّ ۖ وَهُوَ خَيْرُ ٱلْفَٰصِلِينَ',
    highlightStartIndex: 109,
    highlightEndIndex: 118,
  },
  {
    wordOrderIndex: 198,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 36,
    arabicText: 'فَأَزَلَّهُمَا ٱلشَّيْطَٰنُ عَنْهَا فَأَخْرَجَهُمَا مِمَّا كَانَا فِيهِ ۖ وَقُلْنَا ٱهْبِطُوا۟ بَعْضُكُمْ لِبَعْضٍ عَدُوٌّۭ ۖ وَلَكُمْ فِى ٱلْأَرْضِ مُسْتَقَرٌّۭ وَمَتَٰعٌ إِلَىٰ حِينٍۢ',
    highlightStartIndex: 115,
    highlightEndIndex: 123,
  },
  {
    wordOrderIndex: 229,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 197,
    arabicText: 'ٱلْحَجُّ أَشْهُرٌۭ مَّعْلُومَٰتٌۭ ۚ فَمَن فَرَضَ فِيهِنَّ ٱلْحَجَّ فَلَا رَفَثَ وَلَا فُسُوقَ وَلَا جِدَالَ فِى ٱلْحَجِّ ۗ وَمَا تَفْعَلُوا۟ مِنْ خَيْرٍۢ يَعْلَمْهُ ٱللَّهُ ۗ وَتَزَوَّدُوا۟ فَإِنَّ خَيْرَ ٱلزَّادِ ٱلتَّقْوَىٰ ۚ وَٱتَّقُونِ يَٰٓأُو۟لِى ٱلْأَلْبَٰبِ',
    highlightStartIndex: 214,
    highlightEndIndex: 225,
  },
  {
    wordOrderIndex: 267,
    surahName: 'Al-Hujurat',
    surahNum: 49,
    ayahNum: 6,
    arabicText: 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ إِن جَآءَكُمْ فَاسِقٌۢ بِنَبَإٍۢ فَتَبَيَّنُوٓا۟ أَن تُصِيبُوا۟ قَوْمًۢا بِجَهَٰلَةٍۢ فَتُصْبِحُوا۟ عَلَىٰ مَا فَعَلْتُمْ نَٰدِمِينَ',
    highlightStartIndex: 50,
    highlightEndIndex: 58,
  },
  {
    wordOrderIndex: 298,
    surahName: 'Al-Bayyinah',
    surahNum: 98,
    ayahNum: 1,
    arabicText: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ لَمْ يَكُنِ ٱلَّذِينَ كَفَرُوا۟ مِنْ أَهْلِ ٱلْكِتَٰبِ وَٱلْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ ٱلْبَيِّنَةُ',
    highlightStartIndex: 144,
    highlightEndIndex: 156,
  },
  {
    wordOrderIndex: 238,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 34,
    arabicText: 'ذُرِّيَّةًۢ بَعْضُهَا مِنۢ بَعْضٍۢ ۗ وَٱللَّهُ سَمِيعٌ عَلِيمٌ',
    highlightStartIndex: 0,
    highlightEndIndex: 11,
  },
  {
    wordOrderIndex: 2,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 107,
    arabicText: 'وَأَمَّا ٱلَّذِينَ ٱبْيَضَّتْ وُجُوهُهُمْ فَفِى رَحْمَةِ ٱللَّهِ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 48,
    highlightEndIndex: 56,
  },
  {
    wordOrderIndex: 58,
    surahName: 'Al-Mulk',
    surahNum: 67,
    ayahNum: 4,
    arabicText: 'ثُمَّ ٱرْجِعِ ٱلْبَصَرَ كَرَّتَيْنِ يَنقَلِبْ إِلَيْكَ ٱلْبَصَرُ خَاسِئًۭا وَهُوَ حَسِيرٌۭ',
    highlightStartIndex: 14,
    highlightEndIndex: 23,
  },
  {
    wordOrderIndex: 274,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 2,
    arabicText: 'ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ',
    highlightStartIndex: 47,
    highlightEndIndex: 62,
  },
  {
    wordOrderIndex: 178,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 55,
    arabicText: 'وَإِذْ قُلْتُمْ يَٰمُوسَىٰ لَن نُّؤْمِنَ لَكَ حَتَّىٰ نَرَى ٱللَّهَ جَهْرَةًۭ فَأَخَذَتْكُمُ ٱلصَّٰعِقَةُ وَأَنتُمْ تَنظُرُونَ',
    highlightStartIndex: 46,
    highlightEndIndex: 53,
  },
  {
    wordOrderIndex: 182,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 27,
    arabicText: 'ٱلَّذِينَ يَنقُضُونَ عَهْدَ ٱللَّهِ مِنۢ بَعْدِ مِيثَٰقِهِۦ وَيَقْطَعُونَ مَآ أَمَرَ ٱللَّهُ بِهِۦٓ أَن يُوصَلَ وَيُفْسِدُونَ فِى ٱلْأَرْضِ ۚ أُو۟لَٰٓئِكَ هُمُ ٱلْخَٰسِرُونَ',
    highlightStartIndex: 41,
    highlightEndIndex: 47,
  },
  {
    wordOrderIndex: 152,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 177,
    arabicText: '۞ لَّيْسَ ٱلْبِرَّ أَن تُوَلُّوا۟ وُجُوهَكُمْ قِبَلَ ٱلْمَشْرِقِ وَٱلْمَغْرِبِ وَلَٰكِنَّ ٱلْبِرَّ مَنْ ءَامَنَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَٱلْمَلَٰٓئِكَةِ وَٱلْكِتَٰبِ وَٱلنَّبِيِّۦنَ وَءَاتَى ٱلْمَالَ عَلَىٰ حُبِّهِۦ ذَوِى ٱلْقُرْبَىٰ وَٱلْيَتَٰمَىٰ وَٱلْمَسَٰكِينَ وَٱبْنَ ٱلسَّبِيلِ وَٱلسَّآئِلِينَ وَفِى ٱلرِّقَابِ وَأَقَامَ ٱلصَّلَوٰةَ وَءَاتَى ٱلزَّكَوٰةَ وَٱلْمُوفُونَ بِعَهْدِهِمْ إِذَا عَٰهَدُوا۟ ۖ وَٱلصَّٰبِرِينَ فِى ٱلْبَأْسَآءِ وَٱلضَّرَّآءِ وَحِينَ ٱلْبَأْسِ ۗ أُو۟لَٰٓئِكَ ٱلَّذِينَ صَدَقُوا۟ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُتَّقُونَ',
    highlightStartIndex: 2,
    highlightEndIndex: 9,
  },
  {
    wordOrderIndex: 117,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 55,
    arabicText: 'وَإِذْ قُلْتُمْ يَٰمُوسَىٰ لَن نُّؤْمِنَ لَكَ حَتَّىٰ نَرَى ٱللَّهَ جَهْرَةًۭ فَأَخَذَتْكُمُ ٱلصَّٰعِقَةُ وَأَنتُمْ تَنظُرُونَ',
    highlightStartIndex: 27,
    highlightEndIndex: 30,
  },
  {
    wordOrderIndex: 288,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 26,
    arabicText: '۞ إِنَّ ٱللَّهَ لَا يَسْتَحْىِۦٓ أَن يَضْرِبَ مَثَلًۭا مَّا بَعُوضَةًۭ فَمَا فَوْقَهَا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا ٱلَّذِينَ كَفَرُوا۟ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلًۭا ۘ يُضِلُّ بِهِۦ كَثِيرًۭا وَيَهْدِى بِهِۦ كَثِيرًۭا ۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلْفَٰسِقِينَ',
    highlightStartIndex: 2,
    highlightEndIndex: 7,
  },
  {
    wordOrderIndex: 77,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 174,
    arabicText: 'إِنَّ ٱلَّذِينَ يَكْتُمُونَ مَآ أَنزَلَ ٱللَّهُ مِنَ ٱلْكِتَٰبِ وَيَشْتَرُونَ بِهِۦ ثَمَنًۭا قَلِيلًا ۙ أُو۟لَٰٓئِكَ مَا يَأْكُلُونَ فِى بُطُونِهِمْ إِلَّا ٱلنَّارَ وَلَا يُكَلِّمُهُمُ ٱللَّهُ يَوْمَ ٱلْقِيَٰمَةِ وَلَا يُزَكِّيهِمْ وَلَهُمْ عَذَابٌ أَلِيمٌ',
    highlightStartIndex: 33,
    highlightEndIndex: 40,
  },
  {
    wordOrderIndex: 252,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 180,
    arabicText: 'كُتِبَ عَلَيْكُمْ إِذَا حَضَرَ أَحَدَكُمُ ٱلْمَوْتُ إِن تَرَكَ خَيْرًا ٱلْوَصِيَّةُ لِلْوَٰلِدَيْنِ وَٱلْأَقْرَبِينَ بِٱلْمَعْرُوفِ ۖ حَقًّا عَلَى ٱلْمُتَّقِينَ',
    highlightStartIndex: 56,
    highlightEndIndex: 62,
  },
  {
    wordOrderIndex: 207,
    surahName: 'Al-Jumu\'ah',
    surahNum: 62,
    ayahNum: 2,
    arabicText: 'هُوَ ٱلَّذِى بَعَثَ فِى ٱلْأُمِّيِّۦنَ رَسُولًۭا مِّنْهُمْ يَتْلُوا۟ عَلَيْهِمْ ءَايَٰتِهِۦ وَيُزَكِّيهِمْ وَيُعَلِّمُهُمُ ٱلْكِتَٰبَ وَٱلْحِكْمَةَ وَإِن كَانُوا۟ مِن قَبْلُ لَفِى ضَلَٰلٍۢ مُّبِينٍۢ',
    highlightStartIndex: 13,
    highlightEndIndex: 19,
  },
];

// Skipped (9 words — exact form doesn't appear standalone):
// 17 (Amila), 29 (Abada), 63 (Kharaja), 87 (Anfaqa), 138 (Andhara),
// 213 (Zanna), 243 (Ashraka), 259 (Nasiya), 168 (Akh)
