// Auto-generated ayah highlights for SPOT_IN_QURAN activities
// Source: api.alquran.cloud (Uthmani script)
// Generated: 2026-02-18
// Only includes words where the EXACT taught form appears.

export interface AyahHighlightSeed {
  wordOrderIndex: number;
  surahName: string;
  surahNum: number;
  ayahNum: number;
  arabicText: string;
  highlightStartIndex: number;
  highlightEndIndex: number;
}

export const AYAH_HIGHLIGHTS: AyahHighlightSeed[] = [
  {
    wordOrderIndex: 1,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 2,
    arabicText: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
    highlightStartIndex: 18,
    highlightEndIndex: 23,
  },
  {
    wordOrderIndex: 3,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 32,
    arabicText: 'قَالُوا۟ سُبْحَٰنَكَ لَا عِلْمَ لَنَآ إِلَّا مَا عَلَّمْتَنَآ ۖ إِنَّكَ أَنتَ ٱلْعَلِيمُ ٱلْحَكِيمُ',
    highlightStartIndex: 25,
    highlightEndIndex: 31,
  },
  {
    wordOrderIndex: 4,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 45,
    arabicText: 'وَٱسْتَعِينُوا۟ بِٱلصَّبْرِ وَٱلصَّلَوٰةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى ٱلْخَٰشِعِينَ',
    highlightStartIndex: 16,
    highlightEndIndex: 27,
  },
  {
    wordOrderIndex: 5,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 2,
    arabicText: 'ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ',
    highlightStartIndex: 40,
    highlightEndIndex: 46,
  },
  {
    wordOrderIndex: 6,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 255,
    arabicText: 'ٱللَّهُ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ ۚ لَا تَأْخُذُهُۥ سِنَةٌۭ وَلَا نَوْمٌۭ ۚ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ مَن ذَا ٱلَّذِى يَشْفَعُ عِندَهُۥٓ إِلَّا بِإِذْنِهِۦ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَىْءٍۢ مِّنْ عِلْمِهِۦٓ إِلَّا بِمَا شَآءَ ۚ وَسِعَ كُرْسِيُّهُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ ۖ وَلَا يَـُٔودُهُۥ حِفْظُهُمَا ۚ وَهُوَ ٱلْعَلِىُّ ٱلْعَظِيمُ',
    highlightStartIndex: 0,
    highlightEndIndex: 7,
  },
  {
    wordOrderIndex: 7,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 2,
    arabicText: 'ذَٰلِكَ ٱلْكِتَٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ',
    highlightStartIndex: 8,
    highlightEndIndex: 18,
  },
  {
    wordOrderIndex: 9,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 144,
    arabicText: 'وَمَا مُحَمَّدٌ إِلَّا رَسُولٌۭ قَدْ خَلَتْ مِن قَبْلِهِ ٱلرُّسُلُ ۚ أَفَإِي۟ن مَّاتَ أَوْ قُتِلَ ٱنقَلَبْتُمْ عَلَىٰٓ أَعْقَٰبِكُمْ ۚ وَمَن يَنقَلِبْ عَلَىٰ عَقِبَيْهِ فَلَن يَضُرَّ ٱللَّهَ شَيْـًۭٔا ۗ وَسَيَجْزِى ٱللَّهُ ٱلشَّٰكِرِينَ',
    highlightStartIndex: 23,
    highlightEndIndex: 31,
  },
  {
    wordOrderIndex: 10,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 26,
    arabicText: '۞ إِنَّ ٱللَّهَ لَا يَسْتَحْىِۦٓ أَن يَضْرِبَ مَثَلًۭا مَّا بَعُوضَةًۭ فَمَا فَوْقَهَا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا ٱلَّذِينَ كَفَرُوا۟ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلًۭا ۘ يُضِلُّ بِهِۦ كَثِيرًۭا وَيَهْدِى بِهِۦ كَثِيرًۭا ۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلْفَٰسِقِينَ',
    highlightStartIndex: 141,
    highlightEndIndex: 149,
  },
  {
    wordOrderIndex: 11,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 164,
    arabicText: 'إِنَّ فِى خَلْقِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَٱخْتِلَٰفِ ٱلَّيْلِ وَٱلنَّهَارِ وَٱلْفُلْكِ ٱلَّتِى تَجْرِى فِى ٱلْبَحْرِ بِمَا يَنفَعُ ٱلنَّاسَ وَمَآ أَنزَلَ ٱللَّهُ مِنَ ٱلسَّمَآءِ مِن مَّآءٍۢ فَأَحْيَا بِهِ ٱلْأَرْضَ بَعْدَ مَوْتِهَا وَبَثَّ فِيهَا مِن كُلِّ دَآبَّةٍۢ وَتَصْرِيفِ ٱلرِّيَٰحِ وَٱلسَّحَابِ ٱلْمُسَخَّرِ بَيْنَ ٱلسَّمَآءِ وَٱلْأَرْضِ لَءَايَٰتٍۢ لِّقَوْمٍۢ يَعْقِلُونَ',
    highlightStartIndex: 31,
    highlightEndIndex: 42,
  },
  {
    wordOrderIndex: 13,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 48,
    arabicText: 'وَٱتَّقُوا۟ يَوْمًۭا لَّا تَجْزِى نَفْسٌ عَن نَّفْسٍۢ شَيْـًۭٔا وَلَا يُقْبَلُ مِنْهَا شَفَٰعَةٌۭ وَلَا يُؤْخَذُ مِنْهَا عَدْلٌۭ وَلَا هُمْ يُنصَرُونَ',
    highlightStartIndex: 34,
    highlightEndIndex: 40,
  },
  {
    wordOrderIndex: 14,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 257,
    arabicText: 'ٱللَّهُ وَلِىُّ ٱلَّذِينَ ءَامَنُوا۟ يُخْرِجُهُم مِّنَ ٱلظُّلُمَٰتِ إِلَى ٱلنُّورِ ۖ وَٱلَّذِينَ كَفَرُوٓا۟ أَوْلِيَآؤُهُمُ ٱلطَّٰغُوتُ يُخْرِجُونَهُم مِّنَ ٱلنُّورِ إِلَى ٱلظُّلُمَٰتِ ۗ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 74,
    highlightEndIndex: 82,
  },
  {
    wordOrderIndex: 16,
    surahName: 'Al-Alaq',
    surahNum: 96,
    ayahNum: 5,
    arabicText: 'عَلَّمَ ٱلْإِنسَٰنَ مَا لَمْ يَعْلَمْ',
    highlightStartIndex: 0,
    highlightEndIndex: 7,
  },
  {
    wordOrderIndex: 18,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 1,
    arabicText: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ ٱلْحَمْدُ لِلَّهِ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ وَجَعَلَ ٱلظُّلُمَٰتِ وَٱلنُّورَ ۖ ثُمَّ ٱلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ يَعْدِلُونَ',
    highlightStartIndex: 65,
    highlightEndIndex: 71,
  },
  {
    wordOrderIndex: 19,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 143,
    arabicText: 'وَكَذَٰلِكَ جَعَلْنَٰكُمْ أُمَّةًۭ وَسَطًۭا لِّتَكُونُوا۟ شُهَدَآءَ عَلَى ٱلنَّاسِ وَيَكُونَ ٱلرَّسُولُ عَلَيْكُمْ شَهِيدًۭا ۗ وَمَا جَعَلْنَا ٱلْقِبْلَةَ ٱلَّتِى كُنتَ عَلَيْهَآ إِلَّا لِنَعْلَمَ مَن يَتَّبِعُ ٱلرَّسُولَ مِمَّن يَنقَلِبُ عَلَىٰ عَقِبَيْهِ ۚ وَإِن كَانَتْ لَكَبِيرَةً إِلَّا عَلَى ٱلَّذِينَ هَدَى ٱللَّهُ ۗ وَمَا كَانَ ٱللَّهُ لِيُضِيعَ إِيمَٰنَكُمْ ۚ إِنَّ ٱللَّهَ بِٱلنَّاسِ لَرَءُوفٌۭ رَّحِيمٌۭ',
    highlightStartIndex: 310,
    highlightEndIndex: 315,
  },
  {
    wordOrderIndex: 21,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 35,
    arabicText: 'وَقُلْنَا يَٰٓـَٔادَمُ ٱسْكُنْ أَنتَ وَزَوْجُكَ ٱلْجَنَّةَ وَكُلَا مِنْهَا رَغَدًا حَيْثُ شِئْتُمَا وَلَا تَقْرَبَا هَٰذِهِ ٱلشَّجَرَةَ فَتَكُونَا مِنَ ٱلظَّٰلِمِينَ',
    highlightStartIndex: 48,
    highlightEndIndex: 58,
  },
  {
    wordOrderIndex: 22,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 39,
    arabicText: 'وَٱلَّذِينَ كَفَرُوا۟ وَكَذَّبُوا۟ بِـَٔايَٰتِنَآ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 74,
    highlightEndIndex: 82,
  },
  {
    wordOrderIndex: 23,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 74,
    arabicText: '۞ فَلْيُقَٰتِلْ فِى سَبِيلِ ٱللَّهِ ٱلَّذِينَ يَشْرُونَ ٱلْحَيَوٰةَ ٱلدُّنْيَا بِٱلْءَاخِرَةِ ۚ وَمَن يُقَٰتِلْ فِى سَبِيلِ ٱللَّهِ فَيُقْتَلْ أَوْ يَغْلِبْ فَسَوْفَ نُؤْتِيهِ أَجْرًا عَظِيمًۭا',
    highlightStartIndex: 176,
    highlightEndIndex: 183,
  },
  {
    wordOrderIndex: 24,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 7,
    arabicText: 'خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ أَبْصَٰرِهِمْ غِشَٰوَةٌۭ ۖ وَلَهُمْ عَذَابٌ عَظِيمٌۭ',
    highlightStartIndex: 102,
    highlightEndIndex: 109,
  },
  {
    wordOrderIndex: 25,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 175,
    arabicText: 'أُو۟لَٰٓئِكَ ٱلَّذِينَ ٱشْتَرَوُا۟ ٱلضَّلَٰلَةَ بِٱلْهُدَىٰ وَٱلْعَذَابَ بِٱلْمَغْفِرَةِ ۚ فَمَآ أَصْبَرَهُمْ عَلَى ٱلنَّارِ',
    highlightStartIndex: 73,
    highlightEndIndex: 88,
  },
  {
    wordOrderIndex: 27,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 108,
    arabicText: 'أَمْ تُرِيدُونَ أَن تَسْـَٔلُوا۟ رَسُولَكُمْ كَمَا سُئِلَ مُوسَىٰ مِن قَبْلُ ۗ وَمَن يَتَبَدَّلِ ٱلْكُفْرَ بِٱلْإِيمَٰنِ فَقَدْ ضَلَّ سَوَآءَ ٱلسَّبِيلِ',
    highlightStartIndex: 107,
    highlightEndIndex: 120,
  },
  {
    wordOrderIndex: 28,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 92,
    arabicText: 'وَمَا كَانَ لِمُؤْمِنٍ أَن يَقْتُلَ مُؤْمِنًا إِلَّا خَطَـًۭٔا ۚ وَمَن قَتَلَ مُؤْمِنًا خَطَـًۭٔا فَتَحْرِيرُ رَقَبَةٍۢ مُّؤْمِنَةٍۢ وَدِيَةٌۭ مُّسَلَّمَةٌ إِلَىٰٓ أَهْلِهِۦٓ إِلَّآ أَن يَصَّدَّقُوا۟ ۚ فَإِن كَانَ مِن قَوْمٍ عَدُوٍّۢ لَّكُمْ وَهُوَ مُؤْمِنٌۭ فَتَحْرِيرُ رَقَبَةٍۢ مُّؤْمِنَةٍۢ ۖ وَإِن كَانَ مِن قَوْمٍۭ بَيْنَكُمْ وَبَيْنَهُم مِّيثَٰقٌۭ فَدِيَةٌۭ مُّسَلَّمَةٌ إِلَىٰٓ أَهْلِهِۦ وَتَحْرِيرُ رَقَبَةٍۢ مُّؤْمِنَةٍۢ ۖ فَمَن لَّمْ يَجِدْ فَصِيَامُ شَهْرَيْنِ مُتَتَابِعَيْنِ تَوْبَةًۭ مِّنَ ٱللَّهِ ۗ وَكَانَ ٱللَّهُ عَلِيمًا حَكِيمًۭا',
    highlightStartIndex: 12,
    highlightEndIndex: 22,
  },
  {
    wordOrderIndex: 32,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 8,
    arabicText: 'وَمِنَ ٱلنَّاسِ مَن يَقُولُ ءَامَنَّا بِٱللَّهِ وَبِٱلْيَوْمِ ٱلْءَاخِرِ وَمَا هُم بِمُؤْمِنِينَ',
    highlightStartIndex: 7,
    highlightEndIndex: 15,
  },
  {
    wordOrderIndex: 35,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 39,
    arabicText: 'فَنَادَتْهُ ٱلْمَلَٰٓئِكَةُ وَهُوَ قَآئِمٌۭ يُصَلِّى فِى ٱلْمِحْرَابِ أَنَّ ٱللَّهَ يُبَشِّرُكَ بِيَحْيَىٰ مُصَدِّقًۢا بِكَلِمَةٍۢ مِّنَ ٱللَّهِ وَسَيِّدًۭا وَحَصُورًۭا وَنَبِيًّۭا مِّنَ ٱلصَّٰلِحِينَ',
    highlightStartIndex: 170,
    highlightEndIndex: 181,
  },
  {
    wordOrderIndex: 37,
    surahName: 'Saba',
    surahNum: 34,
    ayahNum: 13,
    arabicText: 'يَعْمَلُونَ لَهُۥ مَا يَشَآءُ مِن مَّحَٰرِيبَ وَتَمَٰثِيلَ وَجِفَانٍۢ كَٱلْجَوَابِ وَقُدُورٍۢ رَّاسِيَٰتٍ ۚ ٱعْمَلُوٓا۟ ءَالَ دَاوُۥدَ شُكْرًۭا ۚ وَقَلِيلٌۭ مِّنْ عِبَادِىَ ٱلشَّكُورُ',
    highlightStartIndex: 136,
    highlightEndIndex: 144,
  },
  {
    wordOrderIndex: 38,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 37,
    arabicText: 'فَتَقَبَّلَهَا رَبُّهَا بِقَبُولٍ حَسَنٍۢ وَأَنۢبَتَهَا نَبَاتًا حَسَنًۭا وَكَفَّلَهَا زَكَرِيَّا ۖ كُلَّمَا دَخَلَ عَلَيْهَا زَكَرِيَّا ٱلْمِحْرَابَ وَجَدَ عِندَهَا رِزْقًۭا ۖ قَالَ يَٰمَرْيَمُ أَنَّىٰ لَكِ هَٰذَا ۖ قَالَتْ هُوَ مِنْ عِندِ ٱللَّهِ ۖ إِنَّ ٱللَّهَ يَرْزُقُ مَن يَشَآءُ بِغَيْرِ حِسَابٍ',
    highlightStartIndex: 166,
    highlightEndIndex: 174,
  },
  {
    wordOrderIndex: 39,
    surahName: 'Al-Ma\'idah',
    surahNum: 5,
    ayahNum: 20,
    arabicText: 'وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِۦ يَٰقَوْمِ ٱذْكُرُوا۟ نِعْمَةَ ٱللَّهِ عَلَيْكُمْ إِذْ جَعَلَ فِيكُمْ أَنۢبِيَآءَ وَجَعَلَكُم مُّلُوكًۭا وَءَاتَىٰكُم مَّا لَمْ يُؤْتِ أَحَدًۭا مِّنَ ٱلْعَٰلَمِينَ',
    highlightStartIndex: 54,
    highlightEndIndex: 62,
  },
  {
    wordOrderIndex: 40,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 269,
    arabicText: 'يُؤْتِى ٱلْحِكْمَةَ مَن يَشَآءُ ۚ وَمَن يُؤْتَ ٱلْحِكْمَةَ فَقَدْ أُوتِىَ خَيْرًۭا كَثِيرًۭا ۗ وَمَا يَذَّكَّرُ إِلَّآ أُو۟لُوا۟ ٱلْأَلْبَٰبِ',
    highlightStartIndex: 8,
    highlightEndIndex: 19,
  },
  {
    wordOrderIndex: 41,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 30,
    arabicText: 'وَإِذْ قَالَ رَبُّكَ لِلْمَلَٰٓئِكَةِ إِنِّى جَاعِلٌۭ فِى ٱلْأَرْضِ خَلِيفَةًۭ ۖ قَالُوٓا۟ أَتَجْعَلُ فِيهَا مَن يُفْسِدُ فِيهَا وَيَسْفِكُ ٱلدِّمَآءَ وَنَحْنُ نُسَبِّحُ بِحَمْدِكَ وَنُقَدِّسُ لَكَ ۖ قَالَ إِنِّىٓ أَعْلَمُ مَا لَا تَعْلَمُونَ',
    highlightStartIndex: 7,
    highlightEndIndex: 12,
  },
  {
    wordOrderIndex: 42,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 38,
    arabicText: 'هُنَالِكَ دَعَا زَكَرِيَّا رَبَّهُۥ ۖ قَالَ رَبِّ هَبْ لِى مِن لَّدُنكَ ذُرِّيَّةًۭ طَيِّبَةً ۖ إِنَّكَ سَمِيعُ ٱلدُّعَآءِ',
    highlightStartIndex: 10,
    highlightEndIndex: 15,
  },
  {
    wordOrderIndex: 44,
    surahName: 'Al-Ahzab',
    surahNum: 33,
    ayahNum: 41,
    arabicText: 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ ٱذْكُرُوا۟ ٱللَّهَ ذِكْرًۭا كَثِيرًۭا',
    highlightStartIndex: 53,
    highlightEndIndex: 61,
  },
  {
    wordOrderIndex: 46,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 154,
    arabicText: 'وَلَا تَقُولُوا۟ لِمَن يُقْتَلُ فِى سَبِيلِ ٱللَّهِ أَمْوَٰتٌۢ ۚ بَلْ أَحْيَآءٌۭ وَلَٰكِن لَّا تَشْعُرُونَ',
    highlightStartIndex: 36,
    highlightEndIndex: 43,
  },
  {
    wordOrderIndex: 47,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 6,
    arabicText: 'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ',
    highlightStartIndex: 9,
    highlightEndIndex: 19,
  },
  {
    wordOrderIndex: 49,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 210,
    arabicText: 'هَلْ يَنظُرُونَ إِلَّآ أَن يَأْتِيَهُمُ ٱللَّهُ فِى ظُلَلٍۢ مِّنَ ٱلْغَمَامِ وَٱلْمَلَٰٓئِكَةُ وَقُضِىَ ٱلْأَمْرُ ۚ وَإِلَى ٱللَّهِ تُرْجَعُ ٱلْأُمُورُ',
    highlightStartIndex: 105,
    highlightEndIndex: 114,
  },
  {
    wordOrderIndex: 50,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 19,
    arabicText: 'أَوْ كَصَيِّبٍۢ مِّنَ ٱلسَّمَآءِ فِيهِ ظُلُمَٰتٌۭ وَرَعْدٌۭ وَبَرْقٌۭ يَجْعَلُونَ أَصَٰبِعَهُمْ فِىٓ ءَاذَانِهِم مِّنَ ٱلصَّوَٰعِقِ حَذَرَ ٱلْمَوْتِ ۚ وَٱللَّهُ مُحِيطٌۢ بِٱلْكَٰفِرِينَ',
    highlightStartIndex: 140,
    highlightEndIndex: 149,
  },
  {
    wordOrderIndex: 51,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 85,
    arabicText: 'ثُمَّ أَنتُمْ هَٰٓؤُلَآءِ تَقْتُلُونَ أَنفُسَكُمْ وَتُخْرِجُونَ فَرِيقًۭا مِّنكُم مِّن دِيَٰرِهِمْ تَظَٰهَرُونَ عَلَيْهِم بِٱلْإِثْمِ وَٱلْعُدْوَٰنِ وَإِن يَأْتُوكُمْ أُسَٰرَىٰ تُفَٰدُوهُمْ وَهُوَ مُحَرَّمٌ عَلَيْكُمْ إِخْرَاجُهُمْ ۚ أَفَتُؤْمِنُونَ بِبَعْضِ ٱلْكِتَٰبِ وَتَكْفُرُونَ بِبَعْضٍۢ ۚ فَمَا جَزَآءُ مَن يَفْعَلُ ذَٰلِكَ مِنكُمْ إِلَّا خِزْىٌۭ فِى ٱلْحَيَوٰةِ ٱلدُّنْيَا ۖ وَيَوْمَ ٱلْقِيَٰمَةِ يُرَدُّونَ إِلَىٰٓ أَشَدِّ ٱلْعَذَابِ ۗ وَمَا ٱللَّهُ بِغَٰفِلٍ عَمَّا تَعْمَلُونَ',
    highlightStartIndex: 372,
    highlightEndIndex: 382,
  },
  {
    wordOrderIndex: 53,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 85,
    arabicText: 'ثُمَّ أَنتُمْ هَٰٓؤُلَآءِ تَقْتُلُونَ أَنفُسَكُمْ وَتُخْرِجُونَ فَرِيقًۭا مِّنكُم مِّن دِيَٰرِهِمْ تَظَٰهَرُونَ عَلَيْهِم بِٱلْإِثْمِ وَٱلْعُدْوَٰنِ وَإِن يَأْتُوكُمْ أُسَٰرَىٰ تُفَٰدُوهُمْ وَهُوَ مُحَرَّمٌ عَلَيْكُمْ إِخْرَاجُهُمْ ۚ أَفَتُؤْمِنُونَ بِبَعْضِ ٱلْكِتَٰبِ وَتَكْفُرُونَ بِبَعْضٍۢ ۚ فَمَا جَزَآءُ مَن يَفْعَلُ ذَٰلِكَ مِنكُمْ إِلَّا خِزْىٌۭ فِى ٱلْحَيَوٰةِ ٱلدُّنْيَا ۖ وَيَوْمَ ٱلْقِيَٰمَةِ يُرَدُّونَ إِلَىٰٓ أَشَدِّ ٱلْعَذَابِ ۗ وَمَا ٱللَّهُ بِغَٰفِلٍ عَمَّا تَعْمَلُونَ',
    highlightStartIndex: 394,
    highlightEndIndex: 406,
  },
  {
    wordOrderIndex: 54,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 202,
    arabicText: 'أُو۟لَٰٓئِكَ لَهُمْ نَصِيبٌۭ مِّمَّا كَسَبُوا۟ ۚ وَٱللَّهُ سَرِيعُ ٱلْحِسَابِ',
    highlightStartIndex: 67,
    highlightEndIndex: 77,
  },
  {
    wordOrderIndex: 57,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 171,
    arabicText: 'يَٰٓأَهْلَ ٱلْكِتَٰبِ لَا تَغْلُوا۟ فِى دِينِكُمْ وَلَا تَقُولُوا۟ عَلَى ٱللَّهِ إِلَّا ٱلْحَقَّ ۚ إِنَّمَا ٱلْمَسِيحُ عِيسَى ٱبْنُ مَرْيَمَ رَسُولُ ٱللَّهِ وَكَلِمَتُهُۥٓ أَلْقَىٰهَآ إِلَىٰ مَرْيَمَ وَرُوحٌۭ مِّنْهُ ۖ فَـَٔامِنُوا۟ بِٱللَّهِ وَرُسُلِهِۦ ۖ وَلَا تَقُولُوا۟ ثَلَٰثَةٌ ۚ ٱنتَهُوا۟ خَيْرًۭا لَّكُمْ ۚ إِنَّمَا ٱللَّهُ إِلَٰهٌۭ وَٰحِدٌۭ ۖ سُبْحَٰنَهُۥٓ أَن يَكُونَ لَهُۥ وَلَدٌۭ ۘ لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ وَكَفَىٰ بِٱللَّهِ وَكِيلًۭا',
    highlightStartIndex: 201,
    highlightEndIndex: 209,
  },
  {
    wordOrderIndex: 66,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 54,
    arabicText: 'وَإِذْ قَالَ مُوسَىٰ لِقَوْمِهِۦ يَٰقَوْمِ إِنَّكُمْ ظَلَمْتُمْ أَنفُسَكُم بِٱتِّخَاذِكُمُ ٱلْعِجْلَ فَتُوبُوٓا۟ إِلَىٰ بَارِئِكُمْ فَٱقْتُلُوٓا۟ أَنفُسَكُمْ ذَٰلِكُمْ خَيْرٌۭ لَّكُمْ عِندَ بَارِئِكُمْ فَتَابَ عَلَيْكُمْ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ',
    highlightStartIndex: 168,
    highlightEndIndex: 175,
  },
  {
    wordOrderIndex: 67,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 216,
    arabicText: 'كُتِبَ عَلَيْكُمُ ٱلْقِتَالُ وَهُوَ كُرْهٌۭ لَّكُمْ ۖ وَعَسَىٰٓ أَن تَكْرَهُوا۟ شَيْـًۭٔا وَهُوَ خَيْرٌۭ لَّكُمْ ۖ وَعَسَىٰٓ أَن تُحِبُّوا۟ شَيْـًۭٔا وَهُوَ شَرٌّۭ لَّكُمْ ۗ وَٱللَّهُ يَعْلَمُ وَأَنتُمْ لَا تَعْلَمُونَ',
    highlightStartIndex: 157,
    highlightEndIndex: 163,
  },
  {
    wordOrderIndex: 68,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 62,
    arabicText: 'إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَٱلَّذِينَ هَادُوا۟ وَٱلنَّصَٰرَىٰ وَٱلصَّٰبِـِٔينَ مَنْ ءَامَنَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَعَمِلَ صَٰلِحًۭا فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
    highlightStartIndex: 135,
    highlightEndIndex: 144,
  },
  {
    wordOrderIndex: 69,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 7,
    arabicText: 'خَتَمَ ٱللَّهُ عَلَىٰ قُلُوبِهِمْ وَعَلَىٰ سَمْعِهِمْ ۖ وَعَلَىٰٓ أَبْصَٰرِهِمْ غِشَٰوَةٌۭ ۖ وَلَهُمْ عَذَابٌ عَظِيمٌۭ',
    highlightStartIndex: 110,
    highlightEndIndex: 118,
  },
  {
    wordOrderIndex: 70,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 217,
    arabicText: 'يَسْـَٔلُونَكَ عَنِ ٱلشَّهْرِ ٱلْحَرَامِ قِتَالٍۢ فِيهِ ۖ قُلْ قِتَالٌۭ فِيهِ كَبِيرٌۭ ۖ وَصَدٌّ عَن سَبِيلِ ٱللَّهِ وَكُفْرٌۢ بِهِۦ وَٱلْمَسْجِدِ ٱلْحَرَامِ وَإِخْرَاجُ أَهْلِهِۦ مِنْهُ أَكْبَرُ عِندَ ٱللَّهِ ۚ وَٱلْفِتْنَةُ أَكْبَرُ مِنَ ٱلْقَتْلِ ۗ وَلَا يَزَالُونَ يُقَٰتِلُونَكُمْ حَتَّىٰ يَرُدُّوكُمْ عَن دِينِكُمْ إِنِ ٱسْتَطَٰعُوا۟ ۚ وَمَن يَرْتَدِدْ مِنكُمْ عَن دِينِهِۦ فَيَمُتْ وَهُوَ كَافِرٌۭ فَأُو۟لَٰٓئِكَ حَبِطَتْ أَعْمَٰلُهُمْ فِى ٱلدُّنْيَا وَٱلْءَاخِرَةِ ۖ وَأُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 78,
    highlightEndIndex: 86,
  },
  {
    wordOrderIndex: 72,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 164,
    arabicText: 'إِنَّ فِى خَلْقِ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ وَٱخْتِلَٰفِ ٱلَّيْلِ وَٱلنَّهَارِ وَٱلْفُلْكِ ٱلَّتِى تَجْرِى فِى ٱلْبَحْرِ بِمَا يَنفَعُ ٱلنَّاسَ وَمَآ أَنزَلَ ٱللَّهُ مِنَ ٱلسَّمَآءِ مِن مَّآءٍۢ فَأَحْيَا بِهِ ٱلْأَرْضَ بَعْدَ مَوْتِهَا وَبَثَّ فِيهَا مِن كُلِّ دَآبَّةٍۢ وَتَصْرِيفِ ٱلرِّيَٰحِ وَٱلسَّحَابِ ٱلْمُسَخَّرِ بَيْنَ ٱلسَّمَآءِ وَٱلْأَرْضِ لَءَايَٰتٍۢ لِّقَوْمٍۢ يَعْقِلُونَ',
    highlightStartIndex: 65,
    highlightEndIndex: 77,
  },
  {
    wordOrderIndex: 73,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 258,
    arabicText: 'أَلَمْ تَرَ إِلَى ٱلَّذِى حَآجَّ إِبْرَٰهِۦمَ فِى رَبِّهِۦٓ أَنْ ءَاتَىٰهُ ٱللَّهُ ٱلْمُلْكَ إِذْ قَالَ إِبْرَٰهِۦمُ رَبِّىَ ٱلَّذِى يُحْىِۦ وَيُمِيتُ قَالَ أَنَا۠ أُحْىِۦ وَأُمِيتُ ۖ قَالَ إِبْرَٰهِۦمُ فَإِنَّ ٱللَّهَ يَأْتِى بِٱلشَّمْسِ مِنَ ٱلْمَشْرِقِ فَأْتِ بِهَا مِنَ ٱلْمَغْرِبِ فَبُهِتَ ٱلَّذِى كَفَرَ ۗ وَٱللَّهُ لَا يَهْدِى ٱلْقَوْمَ ٱلظَّٰلِمِينَ',
    highlightStartIndex: 228,
    highlightEndIndex: 239,
  },
  {
    wordOrderIndex: 74,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 77,
    arabicText: 'فَلَمَّا رَءَا ٱلْقَمَرَ بَازِغًۭا قَالَ هَٰذَا رَبِّى ۖ فَلَمَّآ أَفَلَ قَالَ لَئِن لَّمْ يَهْدِنِى رَبِّى لَأَكُونَنَّ مِنَ ٱلْقَوْمِ ٱلضَّآلِّينَ',
    highlightStartIndex: 15,
    highlightEndIndex: 24,
  },
  {
    wordOrderIndex: 76,
    surahName: 'An-Najm',
    surahNum: 53,
    ayahNum: 18,
    arabicText: 'لَقَدْ رَأَىٰ مِنْ ءَايَٰتِ رَبِّهِ ٱلْكُبْرَىٰٓ',
    highlightStartIndex: 7,
    highlightEndIndex: 13,
  },
  {
    wordOrderIndex: 80,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 22,
    arabicText: 'ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ فِرَٰشًۭا وَٱلسَّمَآءَ بِنَآءًۭ وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءًۭ فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًۭا لَّكُمْ ۖ فَلَا تَجْعَلُوا۟ لِلَّهِ أَندَادًۭا وَأَنتُمْ تَعْلَمُونَ',
    highlightStartIndex: 8,
    highlightEndIndex: 14,
  },
  {
    wordOrderIndex: 81,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 4,
    arabicText: 'مَٰلِكِ يَوْمِ ٱلدِّينِ',
    highlightStartIndex: 15,
    highlightEndIndex: 23,
  },
  {
    wordOrderIndex: 83,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 67,
    arabicText: 'مَا كَانَ إِبْرَٰهِيمُ يَهُودِيًّۭا وَلَا نَصْرَانِيًّۭا وَلَٰكِن كَانَ حَنِيفًۭا مُّسْلِمًۭا وَمَا كَانَ مِنَ ٱلْمُشْرِكِينَ',
    highlightStartIndex: 82,
    highlightEndIndex: 93,
  },
  {
    wordOrderIndex: 85,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 189,
    arabicText: '۞ يَسْـَٔلُونَكَ عَنِ ٱلْأَهِلَّةِ ۖ قُلْ هِىَ مَوَٰقِيتُ لِلنَّاسِ وَٱلْحَجِّ ۗ وَلَيْسَ ٱلْبِرُّ بِأَن تَأْتُوا۟ ٱلْبُيُوتَ مِن ظُهُورِهَا وَلَٰكِنَّ ٱلْبِرَّ مَنِ ٱتَّقَىٰ ۗ وَأْتُوا۟ ٱلْبُيُوتَ مِنْ أَبْوَٰبِهَا ۚ وَٱتَّقُوا۟ ٱللَّهَ لَعَلَّكُمْ تُفْلِحُونَ',
    highlightStartIndex: 166,
    highlightEndIndex: 174,
  },
  {
    wordOrderIndex: 88,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 64,
    arabicText: 'ثُمَّ تَوَلَّيْتُم مِّنۢ بَعْدِ ذَٰلِكَ ۖ فَلَوْلَا فَضْلُ ٱللَّهِ عَلَيْكُمْ وَرَحْمَتُهُۥ لَكُنتُم مِّنَ ٱلْخَٰسِرِينَ',
    highlightStartIndex: 52,
    highlightEndIndex: 58,
  },
  {
    wordOrderIndex: 89,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 22,
    arabicText: 'ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ فِرَٰشًۭا وَٱلسَّمَآءَ بِنَآءًۭ وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءًۭ فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًۭا لَّكُمْ ۖ فَلَا تَجْعَلُوا۟ لِلَّهِ أَندَادًۭا وَأَنتُمْ تَعْلَمُونَ',
    highlightStartIndex: 136,
    highlightEndIndex: 144,
  },
  {
    wordOrderIndex: 91,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 26,
    arabicText: 'قُلِ ٱللَّهُمَّ مَٰلِكَ ٱلْمُلْكِ تُؤْتِى ٱلْمُلْكَ مَن تَشَآءُ وَتَنزِعُ ٱلْمُلْكَ مِمَّن تَشَآءُ وَتُعِزُّ مَن تَشَآءُ وَتُذِلُّ مَن تَشَآءُ ۖ بِيَدِكَ ٱلْخَيْرُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌۭ',
    highlightStartIndex: 24,
    highlightEndIndex: 33,
  },
  {
    wordOrderIndex: 92,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 107,
    arabicText: 'أَلَمْ تَعْلَمْ أَنَّ ٱللَّهَ لَهُۥ مُلْكُ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۗ وَمَا لَكُم مِّن دُونِ ٱللَّهِ مِن وَلِىٍّۢ وَلَا نَصِيرٍ',
    highlightStartIndex: 36,
    highlightEndIndex: 42,
  },
  {
    wordOrderIndex: 93,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 165,
    arabicText: 'وَمِنَ ٱلنَّاسِ مَن يَتَّخِذُ مِن دُونِ ٱللَّهِ أَندَادًۭا يُحِبُّونَهُمْ كَحُبِّ ٱللَّهِ ۖ وَٱلَّذِينَ ءَامَنُوٓا۟ أَشَدُّ حُبًّۭا لِّلَّهِ ۗ وَلَوْ يَرَى ٱلَّذِينَ ظَلَمُوٓا۟ إِذْ يَرَوْنَ ٱلْعَذَابَ أَنَّ ٱلْقُوَّةَ لِلَّهِ جَمِيعًۭا وَأَنَّ ٱللَّهَ شَدِيدُ ٱلْعَذَابِ',
    highlightStartIndex: 208,
    highlightEndIndex: 218,
  },
  {
    wordOrderIndex: 95,
    surahName: 'Al-A\'raf',
    surahNum: 7,
    ayahNum: 54,
    arabicText: 'إِنَّ رَبَّكُمُ ٱللَّهُ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ فِى سِتَّةِ أَيَّامٍۢ ثُمَّ ٱسْتَوَىٰ عَلَى ٱلْعَرْشِ يُغْشِى ٱلَّيْلَ ٱلنَّهَارَ يَطْلُبُهُۥ حَثِيثًۭا وَٱلشَّمْسَ وَٱلْقَمَرَ وَٱلنُّجُومَ مُسَخَّرَٰتٍۭ بِأَمْرِهِۦٓ ۗ أَلَا لَهُ ٱلْخَلْقُ وَٱلْأَمْرُ ۗ تَبَارَكَ ٱللَّهُ رَبُّ ٱلْعَٰلَمِينَ',
    highlightStartIndex: 109,
    highlightEndIndex: 118,
  },
  {
    wordOrderIndex: 97,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 26,
    arabicText: '۞ إِنَّ ٱللَّهَ لَا يَسْتَحْىِۦٓ أَن يَضْرِبَ مَثَلًۭا مَّا بَعُوضَةًۭ فَمَا فَوْقَهَا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا ٱلَّذِينَ كَفَرُوا۟ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلًۭا ۘ يُضِلُّ بِهِۦ كَثِيرًۭا وَيَهْدِى بِهِۦ كَثِيرًۭا ۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلْفَٰسِقِينَ',
    highlightStartIndex: 217,
    highlightEndIndex: 224,
  },
  {
    wordOrderIndex: 124,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 144,
    arabicText: 'قَدْ نَرَىٰ تَقَلُّبَ وَجْهِكَ فِى ٱلسَّمَآءِ ۖ فَلَنُوَلِّيَنَّكَ قِبْلَةًۭ تَرْضَىٰهَا ۚ فَوَلِّ وَجْهَكَ شَطْرَ ٱلْمَسْجِدِ ٱلْحَرَامِ ۚ وَحَيْثُ مَا كُنتُمْ فَوَلُّوا۟ وُجُوهَكُمْ شَطْرَهُۥ ۗ وَإِنَّ ٱلَّذِينَ أُوتُوا۟ ٱلْكِتَٰبَ لَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۗ وَمَا ٱللَّهُ بِغَٰفِلٍ عَمَّا يَعْمَلُونَ',
    highlightStartIndex: 116,
    highlightEndIndex: 127,
  },
  {
    wordOrderIndex: 125,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 127,
    arabicText: '۞ لَهُمْ دَارُ ٱلسَّلَٰمِ عِندَ رَبِّهِمْ ۖ وَهُوَ وَلِيُّهُم بِمَا كَانُوا۟ يَعْمَلُونَ',
    highlightStartIndex: 9,
    highlightEndIndex: 14,
  },
  {
    wordOrderIndex: 126,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 64,
    arabicText: 'قُلْ يَٰٓأَهْلَ ٱلْكِتَٰبِ تَعَالَوْا۟ إِلَىٰ كَلِمَةٍۢ سَوَآءٍۭ بَيْنَنَا وَبَيْنَكُمْ أَلَّا نَعْبُدَ إِلَّا ٱللَّهَ وَلَا نُشْرِكَ بِهِۦ شَيْـًۭٔا وَلَا يَتَّخِذَ بَعْضُنَا بَعْضًا أَرْبَابًۭا مِّن دُونِ ٱللَّهِ ۚ فَإِن تَوَلَّوْا۟ فَقُولُوا۟ ٱشْهَدُوا۟ بِأَنَّا مُسْلِمُونَ',
    highlightStartIndex: 46,
    highlightEndIndex: 55,
  },
  {
    wordOrderIndex: 127,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 59,
    arabicText: 'فَبَدَّلَ ٱلَّذِينَ ظَلَمُوا۟ قَوْلًا غَيْرَ ٱلَّذِى قِيلَ لَهُمْ فَأَنزَلْنَا عَلَى ٱلَّذِينَ ظَلَمُوا۟ رِجْزًۭا مِّنَ ٱلسَّمَآءِ بِمَا كَانُوا۟ يَفْسُقُونَ',
    highlightStartIndex: 30,
    highlightEndIndex: 37,
  },
  {
    wordOrderIndex: 128,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 42,
    arabicText: 'يَوْمَئِذٍۢ يَوَدُّ ٱلَّذِينَ كَفَرُوا۟ وَعَصَوُا۟ ٱلرَّسُولَ لَوْ تُسَوَّىٰ بِهِمُ ٱلْأَرْضُ وَلَا يَكْتُمُونَ ٱللَّهَ حَدِيثًۭا',
    highlightStartIndex: 120,
    highlightEndIndex: 129,
  },
  {
    wordOrderIndex: 129,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 200,
    arabicText: 'فَإِذَا قَضَيْتُم مَّنَٰسِكَكُمْ فَٱذْكُرُوا۟ ٱللَّهَ كَذِكْرِكُمْ ءَابَآءَكُمْ أَوْ أَشَدَّ ذِكْرًۭا ۗ فَمِنَ ٱلنَّاسِ مَن يَقُولُ رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا وَمَا لَهُۥ فِى ٱلْءَاخِرَةِ مِنْ خَلَٰقٍۢ',
    highlightStartIndex: 94,
    highlightEndIndex: 102,
  },
  {
    wordOrderIndex: 130,
    surahName: 'Al-Ma\'idah',
    surahNum: 5,
    ayahNum: 4,
    arabicText: 'يَسْـَٔلُونَكَ مَاذَآ أُحِلَّ لَهُمْ ۖ قُلْ أُحِلَّ لَكُمُ ٱلطَّيِّبَٰتُ ۙ وَمَا عَلَّمْتُم مِّنَ ٱلْجَوَارِحِ مُكَلِّبِينَ تُعَلِّمُونَهُنَّ مِمَّا عَلَّمَكُمُ ٱللَّهُ ۖ فَكُلُوا۟ مِمَّآ أَمْسَكْنَ عَلَيْكُمْ وَٱذْكُرُوا۟ ٱسْمَ ٱللَّهِ عَلَيْهِ ۖ وَٱتَّقُوا۟ ٱللَّهَ ۚ إِنَّ ٱللَّهَ سَرِيعُ ٱلْحِسَابِ',
    highlightStartIndex: 225,
    highlightEndIndex: 230,
  },
  {
    wordOrderIndex: 132,
    surahName: 'An-Nazi\'at',
    surahNum: 79,
    ayahNum: 21,
    arabicText: 'فَكَذَّبَ وَعَصَىٰ',
    highlightStartIndex: 10,
    highlightEndIndex: 18,
  },
  {
    wordOrderIndex: 133,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 21,
    arabicText: 'وَمَنْ أَظْلَمُ مِمَّنِ ٱفْتَرَىٰ عَلَى ٱللَّهِ كَذِبًا أَوْ كَذَّبَ بِـَٔايَٰتِهِۦٓ ۗ إِنَّهُۥ لَا يُفْلِحُ ٱلظَّٰلِمُونَ',
    highlightStartIndex: 48,
    highlightEndIndex: 55,
  },
  {
    wordOrderIndex: 134,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 37,
    arabicText: 'فَتَلَقَّىٰٓ ءَادَمُ مِن رَّبِّهِۦ كَلِمَٰتٍۢ فَتَابَ عَلَيْهِ ۚ إِنَّهُۥ هُوَ ٱلتَّوَّابُ ٱلرَّحِيمُ',
    highlightStartIndex: 46,
    highlightEndIndex: 53,
  },
  {
    wordOrderIndex: 136,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 95,
    arabicText: 'لَّا يَسْتَوِى ٱلْقَٰعِدُونَ مِنَ ٱلْمُؤْمِنِينَ غَيْرُ أُو۟لِى ٱلضَّرَرِ وَٱلْمُجَٰهِدُونَ فِى سَبِيلِ ٱللَّهِ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ ۚ فَضَّلَ ٱللَّهُ ٱلْمُجَٰهِدِينَ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ عَلَى ٱلْقَٰعِدِينَ دَرَجَةًۭ ۚ وَكُلًّۭا وَعَدَ ٱللَّهُ ٱلْحُسْنَىٰ ۚ وَفَضَّلَ ٱللَّهُ ٱلْمُجَٰهِدِينَ عَلَى ٱلْقَٰعِدِينَ أَجْرًا عَظِيمًۭا',
    highlightStartIndex: 248,
    highlightEndIndex: 254,
  },
  {
    wordOrderIndex: 137,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 95,
    arabicText: 'لَّا يَسْتَوِى ٱلْقَٰعِدُونَ مِنَ ٱلْمُؤْمِنِينَ غَيْرُ أُو۟لِى ٱلضَّرَرِ وَٱلْمُجَٰهِدُونَ فِى سَبِيلِ ٱللَّهِ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ ۚ فَضَّلَ ٱللَّهُ ٱلْمُجَٰهِدِينَ بِأَمْوَٰلِهِمْ وَأَنفُسِهِمْ عَلَى ٱلْقَٰعِدِينَ دَرَجَةًۭ ۚ وَكُلًّۭا وَعَدَ ٱللَّهُ ٱلْحُسْنَىٰ ۚ وَفَضَّلَ ٱللَّهُ ٱلْمُجَٰهِدِينَ عَلَى ٱلْقَٰعِدِينَ أَجْرًا عَظِيمًۭا',
    highlightStartIndex: 248,
    highlightEndIndex: 254,
  },
  {
    wordOrderIndex: 139,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 25,
    arabicText: 'وَبَشِّرِ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمْ جَنَّٰتٍۢ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ ۖ كُلَّمَا رُزِقُوا۟ مِنْهَا مِن ثَمَرَةٍۢ رِّزْقًۭا ۙ قَالُوا۟ هَٰذَا ٱلَّذِى رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا۟ بِهِۦ مُتَشَٰبِهًۭا ۖ وَلَهُمْ فِيهَآ أَزْوَٰجٌۭ مُّطَهَّرَةٌۭ ۖ وَهُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 0,
    highlightEndIndex: 9,
  },
  {
    wordOrderIndex: 141,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 32,
    arabicText: 'قَالُوا۟ سُبْحَٰنَكَ لَا عِلْمَ لَنَآ إِلَّا مَا عَلَّمْتَنَآ ۖ إِنَّكَ أَنتَ ٱلْعَلِيمُ ٱلْحَكِيمُ',
    highlightStartIndex: 80,
    highlightEndIndex: 90,
  },
  {
    wordOrderIndex: 142,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 1,
    arabicText: '﻿بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ',
    highlightStartIndex: 29,
    highlightEndIndex: 39,
  },
  {
    wordOrderIndex: 143,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 173,
    arabicText: 'إِنَّمَا حَرَّمَ عَلَيْكُمُ ٱلْمَيْتَةَ وَٱلدَّمَ وَلَحْمَ ٱلْخِنزِيرِ وَمَآ أُهِلَّ بِهِۦ لِغَيْرِ ٱللَّهِ ۖ فَمَنِ ٱضْطُرَّ غَيْرَ بَاغٍۢ وَلَا عَادٍۢ فَلَآ إِثْمَ عَلَيْهِ ۚ إِنَّ ٱللَّهَ غَفُورٌۭ رَّحِيمٌ',
    highlightStartIndex: 193,
    highlightEndIndex: 201,
  },
  {
    wordOrderIndex: 144,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 127,
    arabicText: 'وَإِذْ يَرْفَعُ إِبْرَٰهِۦمُ ٱلْقَوَاعِدَ مِنَ ٱلْبَيْتِ وَإِسْمَٰعِيلُ رَبَّنَا تَقَبَّلْ مِنَّآ ۖ إِنَّكَ أَنتَ ٱلسَّمِيعُ ٱلْعَلِيمُ',
    highlightStartIndex: 115,
    highlightEndIndex: 125,
  },
  {
    wordOrderIndex: 145,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 32,
    arabicText: 'قَالُوا۟ سُبْحَٰنَكَ لَا عِلْمَ لَنَآ إِلَّا مَا عَلَّمْتَنَآ ۖ إِنَّكَ أَنتَ ٱلْعَلِيمُ ٱلْحَكِيمُ',
    highlightStartIndex: 91,
    highlightEndIndex: 101,
  },
  {
    wordOrderIndex: 146,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 27,
    arabicText: 'ٱلَّذِينَ يَنقُضُونَ عَهْدَ ٱللَّهِ مِنۢ بَعْدِ مِيثَٰقِهِۦ وَيَقْطَعُونَ مَآ أَمَرَ ٱللَّهُ بِهِۦٓ أَن يُوصَلَ وَيُفْسِدُونَ فِى ٱلْأَرْضِ ۚ أُو۟لَٰٓئِكَ هُمُ ٱلْخَٰسِرُونَ',
    highlightStartIndex: 21,
    highlightEndIndex: 27,
  },
  {
    wordOrderIndex: 147,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 79,
    arabicText: 'مَّآ أَصَابَكَ مِنْ حَسَنَةٍۢ فَمِنَ ٱللَّهِ ۖ وَمَآ أَصَابَكَ مِن سَيِّئَةٍۢ فَمِن نَّفْسِكَ ۚ وَأَرْسَلْنَٰكَ لِلنَّاسِ رَسُولًۭا ۚ وَكَفَىٰ بِٱللَّهِ شَهِيدًۭا',
    highlightStartIndex: 155,
    highlightEndIndex: 164,
  },
  {
    wordOrderIndex: 149,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 26,
    arabicText: '۞ إِنَّ ٱللَّهَ لَا يَسْتَحْىِۦٓ أَن يَضْرِبَ مَثَلًۭا مَّا بَعُوضَةًۭ فَمَا فَوْقَهَا ۚ فَأَمَّا ٱلَّذِينَ ءَامَنُوا۟ فَيَعْلَمُونَ أَنَّهُ ٱلْحَقُّ مِن رَّبِّهِمْ ۖ وَأَمَّا ٱلَّذِينَ كَفَرُوا۟ فَيَقُولُونَ مَاذَآ أَرَادَ ٱللَّهُ بِهَٰذَا مَثَلًۭا ۘ يُضِلُّ بِهِۦ كَثِيرًۭا وَيَهْدِى بِهِۦ كَثِيرًۭا ۚ وَمَا يُضِلُّ بِهِۦٓ إِلَّا ٱلْفَٰسِقِينَ',
    highlightStartIndex: 46,
    highlightEndIndex: 54,
  },
  {
    wordOrderIndex: 150,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 105,
    arabicText: 'مَّا يَوَدُّ ٱلَّذِينَ كَفَرُوا۟ مِنْ أَهْلِ ٱلْكِتَٰبِ وَلَا ٱلْمُشْرِكِينَ أَن يُنَزَّلَ عَلَيْكُم مِّنْ خَيْرٍۢ مِّن رَّبِّكُمْ ۗ وَٱللَّهُ يَخْتَصُّ بِرَحْمَتِهِۦ مَن يَشَآءُ ۚ وَٱللَّهُ ذُو ٱلْفَضْلِ ٱلْعَظِيمِ',
    highlightStartIndex: 38,
    highlightEndIndex: 44,
  },
  {
    wordOrderIndex: 151,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 79,
    arabicText: 'مَا كَانَ لِبَشَرٍ أَن يُؤْتِيَهُ ٱللَّهُ ٱلْكِتَٰبَ وَٱلْحُكْمَ وَٱلنُّبُوَّةَ ثُمَّ يَقُولَ لِلنَّاسِ كُونُوا۟ عِبَادًۭا لِّى مِن دُونِ ٱللَّهِ وَلَٰكِن كُونُوا۟ رَبَّٰنِيِّۦنَ بِمَا كُنتُمْ تُعَلِّمُونَ ٱلْكِتَٰبَ وَبِمَا كُنتُمْ تَدْرُسُونَ',
    highlightStartIndex: 4,
    highlightEndIndex: 9,
  },
  {
    wordOrderIndex: 153,
    surahName: 'Al-A\'raf',
    surahNum: 7,
    ayahNum: 155,
    arabicText: 'وَٱخْتَارَ مُوسَىٰ قَوْمَهُۥ سَبْعِينَ رَجُلًۭا لِّمِيقَٰتِنَا ۖ فَلَمَّآ أَخَذَتْهُمُ ٱلرَّجْفَةُ قَالَ رَبِّ لَوْ شِئْتَ أَهْلَكْتَهُم مِّن قَبْلُ وَإِيَّٰىَ ۖ أَتُهْلِكُنَا بِمَا فَعَلَ ٱلسُّفَهَآءُ مِنَّآ ۖ إِنْ هِىَ إِلَّا فِتْنَتُكَ تُضِلُّ بِهَا مَن تَشَآءُ وَتَهْدِى مَن تَشَآءُ ۖ أَنتَ وَلِيُّنَا فَٱغْفِرْ لَنَا وَٱرْحَمْنَا ۖ وَأَنتَ خَيْرُ ٱلْغَٰفِرِينَ',
    highlightStartIndex: 183,
    highlightEndIndex: 189,
  },
  {
    wordOrderIndex: 154,
    surahName: 'Al-Qasas',
    surahNum: 28,
    ayahNum: 15,
    arabicText: 'وَدَخَلَ ٱلْمَدِينَةَ عَلَىٰ حِينِ غَفْلَةٍۢ مِّنْ أَهْلِهَا فَوَجَدَ فِيهَا رَجُلَيْنِ يَقْتَتِلَانِ هَٰذَا مِن شِيعَتِهِۦ وَهَٰذَا مِنْ عَدُوِّهِۦ ۖ فَٱسْتَغَٰثَهُ ٱلَّذِى مِن شِيعَتِهِۦ عَلَى ٱلَّذِى مِنْ عَدُوِّهِۦ فَوَكَزَهُۥ مُوسَىٰ فَقَضَىٰ عَلَيْهِ ۖ قَالَ هَٰذَا مِنْ عَمَلِ ٱلشَّيْطَٰنِ ۖ إِنَّهُۥ عَدُوٌّۭ مُّضِلٌّۭ مُّبِينٌۭ',
    highlightStartIndex: 61,
    highlightEndIndex: 69,
  },
  {
    wordOrderIndex: 156,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 28,
    arabicText: 'يُرِيدُ ٱللَّهُ أَن يُخَفِّفَ عَنكُمْ ۚ وَخُلِقَ ٱلْإِنسَٰنُ ضَعِيفًۭا',
    highlightStartIndex: 49,
    highlightEndIndex: 60,
  },
  {
    wordOrderIndex: 157,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 115,
    arabicText: 'وَلِلَّهِ ٱلْمَشْرِقُ وَٱلْمَغْرِبُ ۚ فَأَيْنَمَا تُوَلُّوا۟ فَثَمَّ وَجْهُ ٱللَّهِ ۚ إِنَّ ٱللَّهَ وَٰسِعٌ عَلِيمٌۭ',
    highlightStartIndex: 69,
    highlightEndIndex: 75,
  },
  {
    wordOrderIndex: 158,
    surahName: 'Al-Ma\'idah',
    surahNum: 5,
    ayahNum: 64,
    arabicText: 'وَقَالَتِ ٱلْيَهُودُ يَدُ ٱللَّهِ مَغْلُولَةٌ ۚ غُلَّتْ أَيْدِيهِمْ وَلُعِنُوا۟ بِمَا قَالُوا۟ ۘ بَلْ يَدَاهُ مَبْسُوطَتَانِ يُنفِقُ كَيْفَ يَشَآءُ ۚ وَلَيَزِيدَنَّ كَثِيرًۭا مِّنْهُم مَّآ أُنزِلَ إِلَيْكَ مِن رَّبِّكَ طُغْيَٰنًۭا وَكُفْرًۭا ۚ وَأَلْقَيْنَا بَيْنَهُمُ ٱلْعَدَٰوَةَ وَٱلْبَغْضَآءَ إِلَىٰ يَوْمِ ٱلْقِيَٰمَةِ ۚ كُلَّمَآ أَوْقَدُوا۟ نَارًۭا لِّلْحَرْبِ أَطْفَأَهَا ٱللَّهُ ۚ وَيَسْعَوْنَ فِى ٱلْأَرْضِ فَسَادًۭا ۚ وَٱللَّهُ لَا يُحِبُّ ٱلْمُفْسِدِينَ',
    highlightStartIndex: 21,
    highlightEndIndex: 25,
  },
  {
    wordOrderIndex: 159,
    surahName: 'Al-Ma\'idah',
    surahNum: 5,
    ayahNum: 45,
    arabicText: 'وَكَتَبْنَا عَلَيْهِمْ فِيهَآ أَنَّ ٱلنَّفْسَ بِٱلنَّفْسِ وَٱلْعَيْنَ بِٱلْعَيْنِ وَٱلْأَنفَ بِٱلْأَنفِ وَٱلْأُذُنَ بِٱلْأُذُنِ وَٱلسِّنَّ بِٱلسِّنِّ وَٱلْجُرُوحَ قِصَاصٌۭ ۚ فَمَن تَصَدَّقَ بِهِۦ فَهُوَ كَفَّارَةٌۭ لَّهُۥ ۚ وَمَن لَّمْ يَحْكُم بِمَآ أَنزَلَ ٱللَّهُ فَأُو۟لَٰٓئِكَ هُمُ ٱلظَّٰلِمُونَ',
    highlightStartIndex: 59,
    highlightEndIndex: 70,
  },
  {
    wordOrderIndex: 160,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 1,
    arabicText: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ ٱلْحَمْدُ لِلَّهِ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ وَجَعَلَ ٱلظُّلُمَٰتِ وَٱلنُّورَ ۖ ثُمَّ ٱلَّذِينَ كَفَرُوا۟ بِرَبِّهِمْ يَعْدِلُونَ',
    highlightStartIndex: 65,
    highlightEndIndex: 71,
  },
  {
    wordOrderIndex: 162,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 36,
    arabicText: 'فَأَزَلَّهُمَا ٱلشَّيْطَٰنُ عَنْهَا فَأَخْرَجَهُمَا مِمَّا كَانَا فِيهِ ۖ وَقُلْنَا ٱهْبِطُوا۟ بَعْضُكُمْ لِبَعْضٍ عَدُوٌّۭ ۖ وَلَكُمْ فِى ٱلْأَرْضِ مُسْتَقَرٌّۭ وَمَتَٰعٌ إِلَىٰ حِينٍۢ',
    highlightStartIndex: 15,
    highlightEndIndex: 27,
  },
  {
    wordOrderIndex: 163,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 12,
    arabicText: 'قُل لِّلَّذِينَ كَفَرُوا۟ سَتُغْلَبُونَ وَتُحْشَرُونَ إِلَىٰ جَهَنَّمَ ۚ وَبِئْسَ ٱلْمِهَادُ',
    highlightStartIndex: 61,
    highlightEndIndex: 70,
  },
  {
    wordOrderIndex: 165,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 39,
    arabicText: 'وَٱلَّذِينَ كَفَرُوا۟ وَكَذَّبُوا۟ بِـَٔايَٰتِنَآ أُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 64,
    highlightEndIndex: 73,
  },
  {
    wordOrderIndex: 166,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 116,
    arabicText: 'وَقَالُوا۟ ٱتَّخَذَ ٱللَّهُ وَلَدًۭا ۗ سُبْحَٰنَهُۥ ۖ بَل لَّهُۥ مَا فِى ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۖ كُلٌّۭ لَّهُۥ قَٰنِتُونَ',
    highlightStartIndex: 28,
    highlightEndIndex: 36,
  },
  {
    wordOrderIndex: 167,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 87,
    arabicText: 'وَلَقَدْ ءَاتَيْنَا مُوسَى ٱلْكِتَٰبَ وَقَفَّيْنَا مِنۢ بَعْدِهِۦ بِٱلرُّسُلِ ۖ وَءَاتَيْنَا عِيسَى ٱبْنَ مَرْيَمَ ٱلْبَيِّنَٰتِ وَأَيَّدْنَٰهُ بِرُوحِ ٱلْقُدُسِ ۗ أَفَكُلَّمَا جَآءَكُمْ رَسُولٌۢ بِمَا لَا تَهْوَىٰٓ أَنفُسُكُمُ ٱسْتَكْبَرْتُمْ فَفَرِيقًۭا كَذَّبْتُمْ وَفَرِيقًۭا تَقْتُلُونَ',
    highlightStartIndex: 100,
    highlightEndIndex: 105,
  },
  {
    wordOrderIndex: 170,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 230,
    arabicText: 'فَإِن طَلَّقَهَا فَلَا تَحِلُّ لَهُۥ مِنۢ بَعْدُ حَتَّىٰ تَنكِحَ زَوْجًا غَيْرَهُۥ ۗ فَإِن طَلَّقَهَا فَلَا جُنَاحَ عَلَيْهِمَآ أَن يَتَرَاجَعَآ إِن ظَنَّآ أَن يُقِيمَا حُدُودَ ٱللَّهِ ۗ وَتِلْكَ حُدُودُ ٱللَّهِ يُبَيِّنُهَا لِقَوْمٍۢ يَعْلَمُونَ',
    highlightStartIndex: 65,
    highlightEndIndex: 72,
  },
  {
    wordOrderIndex: 172,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 62,
    arabicText: 'إِنَّ ٱلَّذِينَ ءَامَنُوا۟ وَٱلَّذِينَ هَادُوا۟ وَٱلنَّصَٰرَىٰ وَٱلصَّٰبِـِٔينَ مَنْ ءَامَنَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَعَمِلَ صَٰلِحًۭا فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
    highlightStartIndex: 126,
    highlightEndIndex: 134,
  },
  {
    wordOrderIndex: 173,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 81,
    arabicText: 'بَلَىٰ مَن كَسَبَ سَيِّئَةًۭ وَأَحَٰطَتْ بِهِۦ خَطِيٓـَٔتُهُۥ فَأُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 11,
    highlightEndIndex: 17,
  },
  {
    wordOrderIndex: 174,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 36,
    arabicText: 'فَأَزَلَّهُمَا ٱلشَّيْطَٰنُ عَنْهَا فَأَخْرَجَهُمَا مِمَّا كَانَا فِيهِ ۖ وَقُلْنَا ٱهْبِطُوا۟ بَعْضُكُمْ لِبَعْضٍ عَدُوٌّۭ ۖ وَلَكُمْ فِى ٱلْأَرْضِ مُسْتَقَرٌّۭ وَمَتَٰعٌ إِلَىٰ حِينٍۢ',
    highlightStartIndex: 162,
    highlightEndIndex: 171,
  },
  {
    wordOrderIndex: 175,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 109,
    arabicText: 'وَدَّ كَثِيرٌۭ مِّنْ أَهْلِ ٱلْكِتَٰبِ لَوْ يَرُدُّونَكُم مِّنۢ بَعْدِ إِيمَٰنِكُمْ كُفَّارًا حَسَدًۭا مِّنْ عِندِ أَنفُسِهِم مِّنۢ بَعْدِ مَا تَبَيَّنَ لَهُمُ ٱلْحَقُّ ۖ فَٱعْفُوا۟ وَٱصْفَحُوا۟ حَتَّىٰ يَأْتِىَ ٱللَّهُ بِأَمْرِهِۦٓ ۗ إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌۭ',
    highlightStartIndex: 6,
    highlightEndIndex: 14,
  },
  {
    wordOrderIndex: 190,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 163,
    arabicText: 'وَإِلَٰهُكُمْ إِلَٰهٌۭ وَٰحِدٌۭ ۖ لَّآ إِلَٰهَ إِلَّا هُوَ ٱلرَّحْمَٰنُ ٱلرَّحِيمُ',
    highlightStartIndex: 23,
    highlightEndIndex: 31,
  },
  {
    wordOrderIndex: 192,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 7,
    arabicText: 'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
    highlightStartIndex: 40,
    highlightEndIndex: 46,
  },
  {
    wordOrderIndex: 194,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 88,
    arabicText: 'وَقَالُوا۟ قُلُوبُنَا غُلْفٌۢ ۚ بَل لَّعَنَهُمُ ٱللَّهُ بِكُفْرِهِمْ فَقَلِيلًۭا مَّا يُؤْمِنُونَ',
    highlightStartIndex: 69,
    highlightEndIndex: 80,
  },
  {
    wordOrderIndex: 195,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 29,
    arabicText: 'هُوَ ٱلَّذِى خَلَقَ لَكُم مَّا فِى ٱلْأَرْضِ جَمِيعًۭا ثُمَّ ٱسْتَوَىٰٓ إِلَى ٱلسَّمَآءِ فَسَوَّىٰهُنَّ سَبْعَ سَمَٰوَٰتٍۢ ۚ وَهُوَ بِكُلِّ شَىْءٍ عَلِيمٌۭ',
    highlightStartIndex: 45,
    highlightEndIndex: 54,
  },
  {
    wordOrderIndex: 196,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 126,
    arabicText: 'وَمَا جَعَلَهُ ٱللَّهُ إِلَّا بُشْرَىٰ لَكُمْ وَلِتَطْمَئِنَّ قُلُوبُكُم بِهِۦ ۗ وَمَا ٱلنَّصْرُ إِلَّا مِنْ عِندِ ٱللَّهِ ٱلْعَزِيزِ ٱلْحَكِيمِ',
    highlightStartIndex: 87,
    highlightEndIndex: 96,
  },
  {
    wordOrderIndex: 197,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 102,
    arabicText: 'وَٱتَّبَعُوا۟ مَا تَتْلُوا۟ ٱلشَّيَٰطِينُ عَلَىٰ مُلْكِ سُلَيْمَٰنَ ۖ وَمَا كَفَرَ سُلَيْمَٰنُ وَلَٰكِنَّ ٱلشَّيَٰطِينَ كَفَرُوا۟ يُعَلِّمُونَ ٱلنَّاسَ ٱلسِّحْرَ وَمَآ أُنزِلَ عَلَى ٱلْمَلَكَيْنِ بِبَابِلَ هَٰرُوتَ وَمَٰرُوتَ ۚ وَمَا يُعَلِّمَانِ مِنْ أَحَدٍ حَتَّىٰ يَقُولَآ إِنَّمَا نَحْنُ فِتْنَةٌۭ فَلَا تَكْفُرْ ۖ فَيَتَعَلَّمُونَ مِنْهُمَا مَا يُفَرِّقُونَ بِهِۦ بَيْنَ ٱلْمَرْءِ وَزَوْجِهِۦ ۚ وَمَا هُم بِضَآرِّينَ بِهِۦ مِنْ أَحَدٍ إِلَّا بِإِذْنِ ٱللَّهِ ۚ وَيَتَعَلَّمُونَ مَا يَضُرُّهُمْ وَلَا يَنفَعُهُمْ ۚ وَلَقَدْ عَلِمُوا۟ لَمَنِ ٱشْتَرَىٰهُ مَا لَهُۥ فِى ٱلْءَاخِرَةِ مِنْ خَلَٰقٍۢ ۚ وَلَبِئْسَ مَا شَرَوْا۟ بِهِۦٓ أَنفُسَهُمْ ۚ لَوْ كَانُوا۟ يَعْلَمُونَ',
    highlightStartIndex: 294,
    highlightEndIndex: 303,
  },
  {
    wordOrderIndex: 199,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 126,
    arabicText: 'وَمَا جَعَلَهُ ٱللَّهُ إِلَّا بُشْرَىٰ لَكُمْ وَلِتَطْمَئِنَّ قُلُوبُكُم بِهِۦ ۗ وَمَا ٱلنَّصْرُ إِلَّا مِنْ عِندِ ٱللَّهِ ٱلْعَزِيزِ ٱلْحَكِيمِ',
    highlightStartIndex: 87,
    highlightEndIndex: 96,
  },
  {
    wordOrderIndex: 200,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 45,
    arabicText: 'وَٱللَّهُ أَعْلَمُ بِأَعْدَآئِكُمْ ۚ وَكَفَىٰ بِٱللَّهِ وَلِيًّۭا وَكَفَىٰ بِٱللَّهِ نَصِيرًۭا',
    highlightStartIndex: 57,
    highlightEndIndex: 66,
  },
  {
    wordOrderIndex: 201,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 19,
    arabicText: 'قُلْ أَىُّ شَىْءٍ أَكْبَرُ شَهَٰدَةًۭ ۖ قُلِ ٱللَّهُ ۖ شَهِيدٌۢ بَيْنِى وَبَيْنَكُمْ ۚ وَأُوحِىَ إِلَىَّ هَٰذَا ٱلْقُرْءَانُ لِأُنذِرَكُم بِهِۦ وَمَنۢ بَلَغَ ۚ أَئِنَّكُمْ لَتَشْهَدُونَ أَنَّ مَعَ ٱللَّهِ ءَالِهَةً أُخْرَىٰ ۚ قُل لَّآ أَشْهَدُ ۚ قُلْ إِنَّمَا هُوَ إِلَٰهٌۭ وَٰحِدٌۭ وَإِنَّنِى بَرِىٓءٌۭ مِّمَّا تُشْرِكُونَ',
    highlightStartIndex: 87,
    highlightEndIndex: 96,
  },
  {
    wordOrderIndex: 202,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 22,
    arabicText: 'ٱلَّذِى جَعَلَ لَكُمُ ٱلْأَرْضَ فِرَٰشًۭا وَٱلسَّمَآءَ بِنَآءًۭ وَأَنزَلَ مِنَ ٱلسَّمَآءِ مَآءًۭ فَأَخْرَجَ بِهِۦ مِنَ ٱلثَّمَرَٰتِ رِزْقًۭا لَّكُمْ ۖ فَلَا تَجْعَلُوا۟ لِلَّهِ أَندَادًۭا وَأَنتُمْ تَعْلَمُونَ',
    highlightStartIndex: 101,
    highlightEndIndex: 111,
  },
  {
    wordOrderIndex: 205,
    surahName: 'Al-A\'raf',
    surahNum: 7,
    ayahNum: 29,
    arabicText: 'قُلْ أَمَرَ رَبِّى بِٱلْقِسْطِ ۖ وَأَقِيمُوا۟ وُجُوهَكُمْ عِندَ كُلِّ مَسْجِدٍۢ وَٱدْعُوهُ مُخْلِصِينَ لَهُ ٱلدِّينَ ۚ كَمَا بَدَأَكُمْ تَعُودُونَ',
    highlightStartIndex: 5,
    highlightEndIndex: 11,
  },
  {
    wordOrderIndex: 209,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 2,
    arabicText: 'هُوَ ٱلَّذِى خَلَقَكُم مِّن طِينٍۢ ثُمَّ قَضَىٰٓ أَجَلًۭا ۖ وَأَجَلٌۭ مُّسَمًّى عِندَهُۥ ۖ ثُمَّ أَنتُمْ تَمْتَرُونَ',
    highlightStartIndex: 49,
    highlightEndIndex: 57,
  },
  {
    wordOrderIndex: 210,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 31,
    arabicText: 'قَدْ خَسِرَ ٱلَّذِينَ كَذَّبُوا۟ بِلِقَآءِ ٱللَّهِ ۖ حَتَّىٰٓ إِذَا جَآءَتْهُمُ ٱلسَّاعَةُ بَغْتَةًۭ قَالُوا۟ يَٰحَسْرَتَنَا عَلَىٰ مَا فَرَّطْنَا فِيهَا وَهُمْ يَحْمِلُونَ أَوْزَارَهُمْ عَلَىٰ ظُهُورِهِمْ ۚ أَلَا سَآءَ مَا يَزِرُونَ',
    highlightStartIndex: 82,
    highlightEndIndex: 92,
  },
  {
    wordOrderIndex: 211,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 58,
    arabicText: 'قُل لَّوْ أَنَّ عِندِى مَا تَسْتَعْجِلُونَ بِهِۦ لَقُضِىَ ٱلْأَمْرُ بَيْنِى وَبَيْنَكُمْ ۗ وَٱللَّهُ أَعْلَمُ بِٱلظَّٰلِمِينَ',
    highlightStartIndex: 49,
    highlightEndIndex: 57,
  },
  {
    wordOrderIndex: 212,
    surahName: 'Al-Ma\'idah',
    surahNum: 5,
    ayahNum: 43,
    arabicText: 'وَكَيْفَ يُحَكِّمُونَكَ وَعِندَهُمُ ٱلتَّوْرَىٰةُ فِيهَا حُكْمُ ٱللَّهِ ثُمَّ يَتَوَلَّوْنَ مِنۢ بَعْدِ ذَٰلِكَ ۚ وَمَآ أُو۟لَٰٓئِكَ بِٱلْمُؤْمِنِينَ',
    highlightStartIndex: 57,
    highlightEndIndex: 63,
  },
  {
    wordOrderIndex: 214,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 18,
    arabicText: 'شَهِدَ ٱللَّهُ أَنَّهُۥ لَآ إِلَٰهَ إِلَّا هُوَ وَٱلْمَلَٰٓئِكَةُ وَأُو۟لُوا۟ ٱلْعِلْمِ قَآئِمًۢا بِٱلْقِسْطِ ۚ لَآ إِلَٰهَ إِلَّا هُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ',
    highlightStartIndex: 0,
    highlightEndIndex: 6,
  },
  {
    wordOrderIndex: 215,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 137,
    arabicText: 'قَدْ خَلَتْ مِن قَبْلِكُمْ سُنَنٌۭ فَسِيرُوا۟ فِى ٱلْأَرْضِ فَٱنظُرُوا۟ كَيْفَ كَانَ عَٰقِبَةُ ٱلْمُكَذِّبِينَ',
    highlightStartIndex: 85,
    highlightEndIndex: 94,
  },
  {
    wordOrderIndex: 216,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 183,
    arabicText: 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟ كُتِبَ عَلَيْكُمُ ٱلصِّيَامُ كَمَا كُتِبَ عَلَى ٱلَّذِينَ مِن قَبْلِكُمْ لَعَلَّكُمْ تَتَّقُونَ',
    highlightStartIndex: 34,
    highlightEndIndex: 40,
  },
  {
    wordOrderIndex: 217,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 31,
    arabicText: 'وَعَلَّمَ ءَادَمَ ٱلْأَسْمَآءَ كُلَّهَا ثُمَّ عَرَضَهُمْ عَلَى ٱلْمَلَٰٓئِكَةِ فَقَالَ أَنۢبِـُٔونِى بِأَسْمَآءِ هَٰٓؤُلَآءِ إِن كُنتُمْ صَٰدِقِينَ',
    highlightStartIndex: 0,
    highlightEndIndex: 9,
  },
  {
    wordOrderIndex: 220,
    surahName: 'Ibrahim',
    surahNum: 14,
    ayahNum: 24,
    arabicText: 'أَلَمْ تَرَ كَيْفَ ضَرَبَ ٱللَّهُ مَثَلًۭا كَلِمَةًۭ طَيِّبَةًۭ كَشَجَرَةٍۢ طَيِّبَةٍ أَصْلُهَا ثَابِتٌۭ وَفَرْعُهَا فِى ٱلسَّمَآءِ',
    highlightStartIndex: 19,
    highlightEndIndex: 25,
  },
  {
    wordOrderIndex: 223,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 45,
    arabicText: 'وَٱسْتَعِينُوا۟ بِٱلصَّبْرِ وَٱلصَّلَوٰةِ ۚ وَإِنَّهَا لَكَبِيرَةٌ إِلَّا عَلَى ٱلْخَٰشِعِينَ',
    highlightStartIndex: 16,
    highlightEndIndex: 27,
  },
  {
    wordOrderIndex: 224,
    surahName: 'Saba',
    surahNum: 34,
    ayahNum: 13,
    arabicText: 'يَعْمَلُونَ لَهُۥ مَا يَشَآءُ مِن مَّحَٰرِيبَ وَتَمَٰثِيلَ وَجِفَانٍۢ كَٱلْجَوَابِ وَقُدُورٍۢ رَّاسِيَٰتٍ ۚ ٱعْمَلُوٓا۟ ءَالَ دَاوُۥدَ شُكْرًۭا ۚ وَقَلِيلٌۭ مِّنْ عِبَادِىَ ٱلشَّكُورُ',
    highlightStartIndex: 136,
    highlightEndIndex: 144,
  },
  {
    wordOrderIndex: 226,
    surahName: 'Al-Isra',
    surahNum: 17,
    ayahNum: 1,
    arabicText: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ سُبْحَٰنَ ٱلَّذِىٓ أَسْرَىٰ بِعَبْدِهِۦ لَيْلًۭا مِّنَ ٱلْمَسْجِدِ ٱلْحَرَامِ إِلَى ٱلْمَسْجِدِ ٱلْأَقْصَا ٱلَّذِى بَٰرَكْنَا حَوْلَهُۥ لِنُرِيَهُۥ مِنْ ءَايَٰتِنَآ ۚ إِنَّهُۥ هُوَ ٱلسَّمِيعُ ٱلْبَصِيرُ',
    highlightStartIndex: 39,
    highlightEndIndex: 48,
  },
  {
    wordOrderIndex: 227,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 2,
    arabicText: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
    highlightStartIndex: 0,
    highlightEndIndex: 9,
  },
  {
    wordOrderIndex: 228,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 54,
    arabicText: 'وَإِذَا جَآءَكَ ٱلَّذِينَ يُؤْمِنُونَ بِـَٔايَٰتِنَا فَقُلْ سَلَٰمٌ عَلَيْكُمْ ۖ كَتَبَ رَبُّكُمْ عَلَىٰ نَفْسِهِ ٱلرَّحْمَةَ ۖ أَنَّهُۥ مَنْ عَمِلَ مِنكُمْ سُوٓءًۢا بِجَهَٰلَةٍۢ ثُمَّ تَابَ مِنۢ بَعْدِهِۦ وَأَصْلَحَ فَأَنَّهُۥ غَفُورٌۭ رَّحِيمٌۭ',
    highlightStartIndex: 61,
    highlightEndIndex: 68,
  },
  {
    wordOrderIndex: 230,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 17,
    arabicText: 'إِنَّمَا ٱلتَّوْبَةُ عَلَى ٱللَّهِ لِلَّذِينَ يَعْمَلُونَ ٱلسُّوٓءَ بِجَهَٰلَةٍۢ ثُمَّ يَتُوبُونَ مِن قَرِيبٍۢ فَأُو۟لَٰٓئِكَ يَتُوبُ ٱللَّهُ عَلَيْهِمْ ۗ وَكَانَ ٱللَّهُ عَلِيمًا حَكِيمًۭا',
    highlightStartIndex: 9,
    highlightEndIndex: 20,
  },
  {
    wordOrderIndex: 231,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 129,
    arabicText: 'رَبَّنَا وَٱبْعَثْ فِيهِمْ رَسُولًۭا مِّنْهُمْ يَتْلُوا۟ عَلَيْهِمْ ءَايَٰتِكَ وَيُعَلِّمُهُمُ ٱلْكِتَٰبَ وَٱلْحِكْمَةَ وَيُزَكِّيهِمْ ۚ إِنَّكَ أَنتَ ٱلْعَزِيزُ ٱلْحَكِيمُ',
    highlightStartIndex: 151,
    highlightEndIndex: 161,
  },
  {
    wordOrderIndex: 232,
    surahName: 'An-Naml',
    surahNum: 27,
    ayahNum: 40,
    arabicText: 'قَالَ ٱلَّذِى عِندَهُۥ عِلْمٌۭ مِّنَ ٱلْكِتَٰبِ أَنَا۠ ءَاتِيكَ بِهِۦ قَبْلَ أَن يَرْتَدَّ إِلَيْكَ طَرْفُكَ ۚ فَلَمَّا رَءَاهُ مُسْتَقِرًّا عِندَهُۥ قَالَ هَٰذَا مِن فَضْلِ رَبِّى لِيَبْلُوَنِىٓ ءَأَشْكُرُ أَمْ أَكْفُرُ ۖ وَمَن شَكَرَ فَإِنَّمَا يَشْكُرُ لِنَفْسِهِۦ ۖ وَمَن كَفَرَ فَإِنَّ رَبِّى غَنِىٌّۭ كَرِيمٌۭ',
    highlightStartIndex: 307,
    highlightEndIndex: 315,
  },
  {
    wordOrderIndex: 233,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 20,
    arabicText: 'يَكَادُ ٱلْبَرْقُ يَخْطَفُ أَبْصَٰرَهُمْ ۖ كُلَّمَآ أَضَآءَ لَهُم مَّشَوْا۟ فِيهِ وَإِذَآ أَظْلَمَ عَلَيْهِمْ قَامُوا۟ ۚ وَلَوْ شَآءَ ٱللَّهُ لَذَهَبَ بِسَمْعِهِمْ وَأَبْصَٰرِهِمْ ۚ إِنَّ ٱللَّهَ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌۭ',
    highlightStartIndex: 221,
    highlightEndIndex: 229,
  },
  {
    wordOrderIndex: 234,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 10,
    arabicText: 'فِى قُلُوبِهِم مَّرَضٌۭ فَزَادَهُمُ ٱللَّهُ مَرَضًۭا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌۢ بِمَا كَانُوا۟ يَكْذِبُونَ',
    highlightStartIndex: 72,
    highlightEndIndex: 80,
  },
  {
    wordOrderIndex: 235,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 165,
    arabicText: 'وَمِنَ ٱلنَّاسِ مَن يَتَّخِذُ مِن دُونِ ٱللَّهِ أَندَادًۭا يُحِبُّونَهُمْ كَحُبِّ ٱللَّهِ ۖ وَٱلَّذِينَ ءَامَنُوٓا۟ أَشَدُّ حُبًّۭا لِّلَّهِ ۗ وَلَوْ يَرَى ٱلَّذِينَ ظَلَمُوٓا۟ إِذْ يَرَوْنَ ٱلْعَذَابَ أَنَّ ٱلْقُوَّةَ لِلَّهِ جَمِيعًۭا وَأَنَّ ٱللَّهَ شَدِيدُ ٱلْعَذَابِ',
    highlightStartIndex: 253,
    highlightEndIndex: 260,
  },
  {
    wordOrderIndex: 236,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 128,
    arabicText: 'رَبَّنَا وَٱجْعَلْنَا مُسْلِمَيْنِ لَكَ وَمِن ذُرِّيَّتِنَآ أُمَّةًۭ مُّسْلِمَةًۭ لَّكَ وَأَرِنَا مَنَاسِكَنَا وَتُبْ عَلَيْنَآ ۖ إِنَّكَ أَنتَ ٱلتَّوَّابُ ٱلرَّحِيمُ',
    highlightStartIndex: 61,
    highlightEndIndex: 69,
  },
  {
    wordOrderIndex: 237,
    surahName: 'Al-Fatiha',
    surahNum: 1,
    ayahNum: 2,
    arabicText: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ',
    highlightStartIndex: 24,
    highlightEndIndex: 37,
  },
  {
    wordOrderIndex: 239,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 168,
    arabicText: 'يَٰٓأَيُّهَا ٱلنَّاسُ كُلُوا۟ مِمَّا فِى ٱلْأَرْضِ حَلَٰلًۭا طَيِّبًۭا وَلَا تَتَّبِعُوا۟ خُطُوَٰتِ ٱلشَّيْطَٰنِ ۚ إِنَّهُۥ لَكُمْ عَدُوٌّۭ مُّبِينٌ',
    highlightStartIndex: 140,
    highlightEndIndex: 148,
  },
  {
    wordOrderIndex: 241,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 108,
    arabicText: 'أَمْ تُرِيدُونَ أَن تَسْـَٔلُوا۟ رَسُولَكُمْ كَمَا سُئِلَ مُوسَىٰ مِن قَبْلُ ۗ وَمَن يَتَبَدَّلِ ٱلْكُفْرَ بِٱلْإِيمَٰنِ فَقَدْ ضَلَّ سَوَآءَ ٱلسَّبِيلِ',
    highlightStartIndex: 128,
    highlightEndIndex: 133,
  },
  {
    wordOrderIndex: 242,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 164,
    arabicText: 'لَقَدْ مَنَّ ٱللَّهُ عَلَى ٱلْمُؤْمِنِينَ إِذْ بَعَثَ فِيهِمْ رَسُولًۭا مِّنْ أَنفُسِهِمْ يَتْلُوا۟ عَلَيْهِمْ ءَايَٰتِهِۦ وَيُزَكِّيهِمْ وَيُعَلِّمُهُمُ ٱلْكِتَٰبَ وَٱلْحِكْمَةَ وَإِن كَانُوا۟ مِن قَبْلُ لَفِى ضَلَٰلٍۢ مُّبِينٍ',
    highlightStartIndex: 211,
    highlightEndIndex: 219,
  },
  {
    wordOrderIndex: 244,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 108,
    arabicText: 'أَمْ تُرِيدُونَ أَن تَسْـَٔلُوا۟ رَسُولَكُمْ كَمَا سُئِلَ مُوسَىٰ مِن قَبْلُ ۗ وَمَن يَتَبَدَّلِ ٱلْكُفْرَ بِٱلْإِيمَٰنِ فَقَدْ ضَلَّ سَوَآءَ ٱلسَّبِيلِ',
    highlightStartIndex: 97,
    highlightEndIndex: 106,
  },
  {
    wordOrderIndex: 245,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 85,
    arabicText: 'ثُمَّ أَنتُمْ هَٰٓؤُلَآءِ تَقْتُلُونَ أَنفُسَكُمْ وَتُخْرِجُونَ فَرِيقًۭا مِّنكُم مِّن دِيَٰرِهِمْ تَظَٰهَرُونَ عَلَيْهِم بِٱلْإِثْمِ وَٱلْعُدْوَٰنِ وَإِن يَأْتُوكُمْ أُسَٰرَىٰ تُفَٰدُوهُمْ وَهُوَ مُحَرَّمٌ عَلَيْكُمْ إِخْرَاجُهُمْ ۚ أَفَتُؤْمِنُونَ بِبَعْضِ ٱلْكِتَٰبِ وَتَكْفُرُونَ بِبَعْضٍۢ ۚ فَمَا جَزَآءُ مَن يَفْعَلُ ذَٰلِكَ مِنكُمْ إِلَّا خِزْىٌۭ فِى ٱلْحَيَوٰةِ ٱلدُّنْيَا ۖ وَيَوْمَ ٱلْقِيَٰمَةِ يُرَدُّونَ إِلَىٰٓ أَشَدِّ ٱلْعَذَابِ ۗ وَمَا ٱللَّهُ بِغَٰفِلٍ عَمَّا تَعْمَلُونَ',
    highlightStartIndex: 123,
    highlightEndIndex: 134,
  },
  {
    wordOrderIndex: 246,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 3,
    arabicText: 'ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا رَزَقْنَٰهُمْ يُنفِقُونَ',
    highlightStartIndex: 22,
    highlightEndIndex: 33,
  },
  {
    wordOrderIndex: 253,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 19,
    arabicText: 'قُلْ أَىُّ شَىْءٍ أَكْبَرُ شَهَٰدَةًۭ ۖ قُلِ ٱللَّهُ ۖ شَهِيدٌۢ بَيْنِى وَبَيْنَكُمْ ۚ وَأُوحِىَ إِلَىَّ هَٰذَا ٱلْقُرْءَانُ لِأُنذِرَكُم بِهِۦ وَمَنۢ بَلَغَ ۚ أَئِنَّكُمْ لَتَشْهَدُونَ أَنَّ مَعَ ٱللَّهِ ءَالِهَةً أُخْرَىٰ ۚ قُل لَّآ أَشْهَدُ ۚ قُلْ إِنَّمَا هُوَ إِلَٰهٌۭ وَٰحِدٌۭ وَإِنَّنِى بَرِىٓءٌۭ مِّمَّا تُشْرِكُونَ',
    highlightStartIndex: 151,
    highlightEndIndex: 157,
  },
  {
    wordOrderIndex: 254,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 173,
    arabicText: 'إِنَّمَا حَرَّمَ عَلَيْكُمُ ٱلْمَيْتَةَ وَٱلدَّمَ وَلَحْمَ ٱلْخِنزِيرِ وَمَآ أُهِلَّ بِهِۦ لِغَيْرِ ٱللَّهِ ۖ فَمَنِ ٱضْطُرَّ غَيْرَ بَاغٍۢ وَلَا عَادٍۢ فَلَآ إِثْمَ عَلَيْهِ ۚ إِنَّ ٱللَّهَ غَفُورٌۭ رَّحِيمٌ',
    highlightStartIndex: 9,
    highlightEndIndex: 16,
  },
  {
    wordOrderIndex: 255,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 205,
    arabicText: 'وَإِذَا تَوَلَّىٰ سَعَىٰ فِى ٱلْأَرْضِ لِيُفْسِدَ فِيهَا وَيُهْلِكَ ٱلْحَرْثَ وَٱلنَّسْلَ ۗ وَٱللَّهُ لَا يُحِبُّ ٱلْفَسَادَ',
    highlightStartIndex: 8,
    highlightEndIndex: 17,
  },
  {
    wordOrderIndex: 256,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 177,
    arabicText: '۞ لَّيْسَ ٱلْبِرَّ أَن تُوَلُّوا۟ وُجُوهَكُمْ قِبَلَ ٱلْمَشْرِقِ وَٱلْمَغْرِبِ وَلَٰكِنَّ ٱلْبِرَّ مَنْ ءَامَنَ بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ وَٱلْمَلَٰٓئِكَةِ وَٱلْكِتَٰبِ وَٱلنَّبِيِّۦنَ وَءَاتَى ٱلْمَالَ عَلَىٰ حُبِّهِۦ ذَوِى ٱلْقُرْبَىٰ وَٱلْيَتَٰمَىٰ وَٱلْمَسَٰكِينَ وَٱبْنَ ٱلسَّبِيلِ وَٱلسَّآئِلِينَ وَفِى ٱلرِّقَابِ وَأَقَامَ ٱلصَّلَوٰةَ وَءَاتَى ٱلزَّكَوٰةَ وَٱلْمُوفُونَ بِعَهْدِهِمْ إِذَا عَٰهَدُوا۟ ۖ وَٱلصَّٰبِرِينَ فِى ٱلْبَأْسَآءِ وَٱلضَّرَّآءِ وَحِينَ ٱلْبَأْسِ ۗ أُو۟لَٰٓئِكَ ٱلَّذِينَ صَدَقُوا۟ ۖ وَأُو۟لَٰٓئِكَ هُمُ ٱلْمُتَّقُونَ',
    highlightStartIndex: 328,
    highlightEndIndex: 337,
  },
  {
    wordOrderIndex: 261,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 50,
    arabicText: 'وَإِذْ فَرَقْنَا بِكُمُ ٱلْبَحْرَ فَأَنجَيْنَٰكُمْ وَأَغْرَقْنَآ ءَالَ فِرْعَوْنَ وَأَنتُمْ تَنظُرُونَ',
    highlightStartIndex: 24,
    highlightEndIndex: 33,
  },
  {
    wordOrderIndex: 262,
    surahName: 'Al-Qamar',
    surahNum: 54,
    ayahNum: 54,
    arabicText: 'إِنَّ ٱلْمُتَّقِينَ فِى جَنَّٰتٍۢ وَنَهَرٍۢ',
    highlightStartIndex: 34,
    highlightEndIndex: 43,
  },
  {
    wordOrderIndex: 263,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 117,
    arabicText: 'مَثَلُ مَا يُنفِقُونَ فِى هَٰذِهِ ٱلْحَيَوٰةِ ٱلدُّنْيَا كَمَثَلِ رِيحٍۢ فِيهَا صِرٌّ أَصَابَتْ حَرْثَ قَوْمٍۢ ظَلَمُوٓا۟ أَنفُسَهُمْ فَأَهْلَكَتْهُ ۚ وَمَا ظَلَمَهُمُ ٱللَّهُ وَلَٰكِنْ أَنفُسَهُمْ يَظْلِمُونَ',
    highlightStartIndex: 66,
    highlightEndIndex: 72,
  },
  {
    wordOrderIndex: 264,
    surahName: 'Al-A\'raf',
    surahNum: 7,
    ayahNum: 143,
    arabicText: 'وَلَمَّا جَآءَ مُوسَىٰ لِمِيقَٰتِنَا وَكَلَّمَهُۥ رَبُّهُۥ قَالَ رَبِّ أَرِنِىٓ أَنظُرْ إِلَيْكَ ۚ قَالَ لَن تَرَىٰنِى وَلَٰكِنِ ٱنظُرْ إِلَى ٱلْجَبَلِ فَإِنِ ٱسْتَقَرَّ مَكَانَهُۥ فَسَوْفَ تَرَىٰنِى ۚ فَلَمَّا تَجَلَّىٰ رَبُّهُۥ لِلْجَبَلِ جَعَلَهُۥ دَكًّۭا وَخَرَّ مُوسَىٰ صَعِقًۭا ۚ فَلَمَّآ أَفَاقَ قَالَ سُبْحَٰنَكَ تُبْتُ إِلَيْكَ وَأَنَا۠ أَوَّلُ ٱلْمُؤْمِنِينَ',
    highlightStartIndex: 143,
    highlightEndIndex: 152,
  },
  {
    wordOrderIndex: 265,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 35,
    arabicText: 'وَقُلْنَا يَٰٓـَٔادَمُ ٱسْكُنْ أَنتَ وَزَوْجُكَ ٱلْجَنَّةَ وَكُلَا مِنْهَا رَغَدًا حَيْثُ شِئْتُمَا وَلَا تَقْرَبَا هَٰذِهِ ٱلشَّجَرَةَ فَتَكُونَا مِنَ ٱلظَّٰلِمِينَ',
    highlightStartIndex: 124,
    highlightEndIndex: 135,
  },
  {
    wordOrderIndex: 266,
    surahName: 'Al-Qalam',
    surahNum: 68,
    ayahNum: 24,
    arabicText: 'أَن لَّا يَدْخُلَنَّهَا ٱلْيَوْمَ عَلَيْكُم مِّسْكِينٌۭ',
    highlightStartIndex: 44,
    highlightEndIndex: 55,
  },
  {
    wordOrderIndex: 268,
    surahName: 'An-Nisa',
    surahNum: 4,
    ayahNum: 131,
    arabicText: 'وَلِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۗ وَلَقَدْ وَصَّيْنَا ٱلَّذِينَ أُوتُوا۟ ٱلْكِتَٰبَ مِن قَبْلِكُمْ وَإِيَّاكُمْ أَنِ ٱتَّقُوا۟ ٱللَّهَ ۚ وَإِن تَكْفُرُوا۟ فَإِنَّ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ ۚ وَكَانَ ٱللَّهُ غَنِيًّا حَمِيدًۭا',
    highlightStartIndex: 251,
    highlightEndIndex: 259,
  },
  {
    wordOrderIndex: 269,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 282,
    arabicText: 'يَٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوٓا۟ إِذَا تَدَايَنتُم بِدَيْنٍ إِلَىٰٓ أَجَلٍۢ مُّسَمًّۭى فَٱكْتُبُوهُ ۚ وَلْيَكْتُب بَّيْنَكُمْ كَاتِبٌۢ بِٱلْعَدْلِ ۚ وَلَا يَأْبَ كَاتِبٌ أَن يَكْتُبَ كَمَا عَلَّمَهُ ٱللَّهُ ۚ فَلْيَكْتُبْ وَلْيُمْلِلِ ٱلَّذِى عَلَيْهِ ٱلْحَقُّ وَلْيَتَّقِ ٱللَّهَ رَبَّهُۥ وَلَا يَبْخَسْ مِنْهُ شَيْـًۭٔا ۚ فَإِن كَانَ ٱلَّذِى عَلَيْهِ ٱلْحَقُّ سَفِيهًا أَوْ ضَعِيفًا أَوْ لَا يَسْتَطِيعُ أَن يُمِلَّ هُوَ فَلْيُمْلِلْ وَلِيُّهُۥ بِٱلْعَدْلِ ۚ وَٱسْتَشْهِدُوا۟ شَهِيدَيْنِ مِن رِّجَالِكُمْ ۖ فَإِن لَّمْ يَكُونَا رَجُلَيْنِ فَرَجُلٌۭ وَٱمْرَأَتَانِ مِمَّن تَرْضَوْنَ مِنَ ٱلشُّهَدَآءِ أَن تَضِلَّ إِحْدَىٰهُمَا فَتُذَكِّرَ إِحْدَىٰهُمَا ٱلْأُخْرَىٰ ۚ وَلَا يَأْبَ ٱلشُّهَدَآءُ إِذَا مَا دُعُوا۟ ۚ وَلَا تَسْـَٔمُوٓا۟ أَن تَكْتُبُوهُ صَغِيرًا أَوْ كَبِيرًا إِلَىٰٓ أَجَلِهِۦ ۚ ذَٰلِكُمْ أَقْسَطُ عِندَ ٱللَّهِ وَأَقْوَمُ لِلشَّهَٰدَةِ وَأَدْنَىٰٓ أَلَّا تَرْتَابُوٓا۟ ۖ إِلَّآ أَن تَكُونَ تِجَٰرَةً حَاضِرَةًۭ تُدِيرُونَهَا بَيْنَكُمْ فَلَيْسَ عَلَيْكُمْ جُنَاحٌ أَلَّا تَكْتُبُوهَا ۗ وَأَشْهِدُوٓا۟ إِذَا تَبَايَعْتُمْ ۚ وَلَا يُضَآرَّ كَاتِبٌۭ وَلَا شَهِيدٌۭ ۚ وَإِن تَفْعَلُوا۟ فَإِنَّهُۥ فُسُوقٌۢ بِكُمْ ۗ وَٱتَّقُوا۟ ٱللَّهَ ۖ وَيُعَلِّمُكُمُ ٱللَّهُ ۗ وَٱللَّهُ بِكُلِّ شَىْءٍ عَلِيمٌۭ',
    highlightStartIndex: 543,
    highlightEndIndex: 552,
  },
  {
    wordOrderIndex: 270,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 58,
    arabicText: 'وَإِذْ قُلْنَا ٱدْخُلُوا۟ هَٰذِهِ ٱلْقَرْيَةَ فَكُلُوا۟ مِنْهَا حَيْثُ شِئْتُمْ رَغَدًۭا وَٱدْخُلُوا۟ ٱلْبَابَ سُجَّدًۭا وَقُولُوا۟ حِطَّةٌۭ نَّغْفِرْ لَكُمْ خَطَٰيَٰكُمْ ۚ وَسَنَزِيدُ ٱلْمُحْسِنِينَ',
    highlightStartIndex: 34,
    highlightEndIndex: 45,
  },
  {
    wordOrderIndex: 272,
    surahName: 'Al-Hadid',
    surahNum: 57,
    ayahNum: 1,
    arabicText: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ سَبَّحَ لِلَّهِ مَا فِى ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ ۖ وَهُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ',
    highlightStartIndex: 39,
    highlightEndIndex: 46,
  },
  {
    wordOrderIndex: 275,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 25,
    arabicText: 'وَبَشِّرِ ٱلَّذِينَ ءَامَنُوا۟ وَعَمِلُوا۟ ٱلصَّٰلِحَٰتِ أَنَّ لَهُمْ جَنَّٰتٍۢ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ ۖ كُلَّمَا رُزِقُوا۟ مِنْهَا مِن ثَمَرَةٍۢ رِّزْقًۭا ۙ قَالُوا۟ هَٰذَا ٱلَّذِى رُزِقْنَا مِن قَبْلُ ۖ وَأُتُوا۟ بِهِۦ مُتَشَٰبِهًۭا ۖ وَلَهُمْ فِيهَآ أَزْوَٰجٌۭ مُّطَهَّرَةٌۭ ۖ وَهُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 43,
    highlightEndIndex: 56,
  },
  {
    wordOrderIndex: 279,
    surahName: 'At-Tawbah',
    surahNum: 9,
    ayahNum: 13,
    arabicText: 'أَلَا تُقَٰتِلُونَ قَوْمًۭا نَّكَثُوٓا۟ أَيْمَٰنَهُمْ وَهَمُّوا۟ بِإِخْرَاجِ ٱلرَّسُولِ وَهُم بَدَءُوكُمْ أَوَّلَ مَرَّةٍ ۚ أَتَخْشَوْنَهُمْ ۚ فَٱللَّهُ أَحَقُّ أَن تَخْشَوْهُ إِن كُنتُم مُّؤْمِنِينَ',
    highlightStartIndex: 106,
    highlightEndIndex: 113,
  },
  {
    wordOrderIndex: 280,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 126,
    arabicText: 'وَإِذْ قَالَ إِبْرَٰهِۦمُ رَبِّ ٱجْعَلْ هَٰذَا بَلَدًا ءَامِنًۭا وَٱرْزُقْ أَهْلَهُۥ مِنَ ٱلثَّمَرَٰتِ مَنْ ءَامَنَ مِنْهُم بِٱللَّهِ وَٱلْيَوْمِ ٱلْءَاخِرِ ۖ قَالَ وَمَن كَفَرَ فَأُمَتِّعُهُۥ قَلِيلًۭا ثُمَّ أَضْطَرُّهُۥٓ إِلَىٰ عَذَابِ ٱلنَّارِ ۖ وَبِئْسَ ٱلْمَصِيرُ',
    highlightStartIndex: 258,
    highlightEndIndex: 268,
  },
  {
    wordOrderIndex: 281,
    surahName: 'Al-Ma\'idah',
    surahNum: 5,
    ayahNum: 19,
    arabicText: 'يَٰٓأَهْلَ ٱلْكِتَٰبِ قَدْ جَآءَكُمْ رَسُولُنَا يُبَيِّنُ لَكُمْ عَلَىٰ فَتْرَةٍۢ مِّنَ ٱلرُّسُلِ أَن تَقُولُوا۟ مَا جَآءَنَا مِنۢ بَشِيرٍۢ وَلَا نَذِيرٍۢ ۖ فَقَدْ جَآءَكُم بَشِيرٌۭ وَنَذِيرٌۭ ۗ وَٱللَّهُ عَلَىٰ كُلِّ شَىْءٍۢ قَدِيرٌۭ',
    highlightStartIndex: 148,
    highlightEndIndex: 156,
  },
  {
    wordOrderIndex: 282,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 38,
    arabicText: 'قُلْنَا ٱهْبِطُوا۟ مِنْهَا جَمِيعًۭا ۖ فَإِمَّا يَأْتِيَنَّكُم مِّنِّى هُدًۭى فَمَن تَبِعَ هُدَاىَ فَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ',
    highlightStartIndex: 105,
    highlightEndIndex: 111,
  },
  {
    wordOrderIndex: 283,
    surahName: 'Aal-Imran',
    surahNum: 3,
    ayahNum: 94,
    arabicText: 'فَمَنِ ٱفْتَرَىٰ عَلَى ٱللَّهِ ٱلْكَذِبَ مِنۢ بَعْدِ ذَٰلِكَ فَأُو۟لَٰٓئِكَ هُمُ ٱلظَّٰلِمُونَ',
    highlightStartIndex: 31,
    highlightEndIndex: 40,
  },
  {
    wordOrderIndex: 284,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 42,
    arabicText: 'وَلَا تَلْبِسُوا۟ ٱلْحَقَّ بِٱلْبَٰطِلِ وَتَكْتُمُوا۟ ٱلْحَقَّ وَأَنتُمْ تَعْلَمُونَ',
    highlightStartIndex: 27,
    highlightEndIndex: 39,
  },
  {
    wordOrderIndex: 285,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 201,
    arabicText: 'وَمِنْهُم مَّن يَقُولُ رَبَّنَآ ءَاتِنَا فِى ٱلدُّنْيَا حَسَنَةًۭ وَفِى ٱلْءَاخِرَةِ حَسَنَةًۭ وَقِنَا عَذَابَ ٱلنَّارِ',
    highlightStartIndex: 57,
    highlightEndIndex: 66,
  },
  {
    wordOrderIndex: 292,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 217,
    arabicText: 'يَسْـَٔلُونَكَ عَنِ ٱلشَّهْرِ ٱلْحَرَامِ قِتَالٍۢ فِيهِ ۖ قُلْ قِتَالٌۭ فِيهِ كَبِيرٌۭ ۖ وَصَدٌّ عَن سَبِيلِ ٱللَّهِ وَكُفْرٌۢ بِهِۦ وَٱلْمَسْجِدِ ٱلْحَرَامِ وَإِخْرَاجُ أَهْلِهِۦ مِنْهُ أَكْبَرُ عِندَ ٱللَّهِ ۚ وَٱلْفِتْنَةُ أَكْبَرُ مِنَ ٱلْقَتْلِ ۗ وَلَا يَزَالُونَ يُقَٰتِلُونَكُمْ حَتَّىٰ يَرُدُّوكُمْ عَن دِينِكُمْ إِنِ ٱسْتَطَٰعُوا۟ ۚ وَمَن يَرْتَدِدْ مِنكُمْ عَن دِينِهِۦ فَيَمُتْ وَهُوَ كَافِرٌۭ فَأُو۟لَٰٓئِكَ حَبِطَتْ أَعْمَٰلُهُمْ فِى ٱلدُّنْيَا وَٱلْءَاخِرَةِ ۖ وَأُو۟لَٰٓئِكَ أَصْحَٰبُ ٱلنَّارِ ۖ هُمْ فِيهَا خَٰلِدُونَ',
    highlightStartIndex: 30,
    highlightEndIndex: 40,
  },
  {
    wordOrderIndex: 293,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 184,
    arabicText: 'أَيَّامًۭا مَّعْدُودَٰتٍۢ ۚ فَمَن كَانَ مِنكُم مَّرِيضًا أَوْ عَلَىٰ سَفَرٍۢ فَعِدَّةٌۭ مِّنْ أَيَّامٍ أُخَرَ ۚ وَعَلَى ٱلَّذِينَ يُطِيقُونَهُۥ فِدْيَةٌۭ طَعَامُ مِسْكِينٍۢ ۖ فَمَن تَطَوَّعَ خَيْرًۭا فَهُوَ خَيْرٌۭ لَّهُۥ ۚ وَأَن تَصُومُوا۟ خَيْرٌۭ لَّكُمْ ۖ إِن كُنتُمْ تَعْلَمُونَ',
    highlightStartIndex: 154,
    highlightEndIndex: 161,
  },
  {
    wordOrderIndex: 294,
    surahName: 'At-Tawbah',
    surahNum: 9,
    ayahNum: 70,
    arabicText: 'أَلَمْ يَأْتِهِمْ نَبَأُ ٱلَّذِينَ مِن قَبْلِهِمْ قَوْمِ نُوحٍۢ وَعَادٍۢ وَثَمُودَ وَقَوْمِ إِبْرَٰهِيمَ وَأَصْحَٰبِ مَدْيَنَ وَٱلْمُؤْتَفِكَٰتِ ۚ أَتَتْهُمْ رُسُلُهُم بِٱلْبَيِّنَٰتِ ۖ فَمَا كَانَ ٱللَّهُ لِيَظْلِمَهُمْ وَلَٰكِن كَانُوٓا۟ أَنفُسَهُمْ يَظْلِمُونَ',
    highlightStartIndex: 18,
    highlightEndIndex: 24,
  },
  {
    wordOrderIndex: 295,
    surahName: 'Al-Baqarah',
    surahNum: 2,
    ayahNum: 133,
    arabicText: 'أَمْ كُنتُمْ شُهَدَآءَ إِذْ حَضَرَ يَعْقُوبَ ٱلْمَوْتُ إِذْ قَالَ لِبَنِيهِ مَا تَعْبُدُونَ مِنۢ بَعْدِى قَالُوا۟ نَعْبُدُ إِلَٰهَكَ وَإِلَٰهَ ءَابَآئِكَ إِبْرَٰهِۦمَ وَإِسْمَٰعِيلَ وَإِسْحَٰقَ إِلَٰهًۭا وَٰحِدًۭا وَنَحْنُ لَهُۥ مُسْلِمُونَ',
    highlightStartIndex: 206,
    highlightEndIndex: 215,
  },
  {
    wordOrderIndex: 296,
    surahName: 'Ash-Shu\'ara',
    surahNum: 26,
    ayahNum: 88,
    arabicText: 'يَوْمَ لَا يَنفَعُ مَالٌۭ وَلَا بَنُونَ',
    highlightStartIndex: 32,
    highlightEndIndex: 39,
  },
  {
    wordOrderIndex: 297,
    surahName: 'Ibrahim',
    surahNum: 14,
    ayahNum: 4,
    arabicText: 'وَمَآ أَرْسَلْنَا مِن رَّسُولٍ إِلَّا بِلِسَانِ قَوْمِهِۦ لِيُبَيِّنَ لَهُمْ ۖ فَيُضِلُّ ٱللَّهُ مَن يَشَآءُ وَيَهْدِى مَن يَشَآءُ ۚ وَهُوَ ٱلْعَزِيزُ ٱلْحَكِيمُ',
    highlightStartIndex: 39,
    highlightEndIndex: 48,
  },
  {
    wordOrderIndex: 299,
    surahName: 'An-Nur',
    surahNum: 24,
    ayahNum: 31,
    arabicText: 'وَقُل لِّلْمُؤْمِنَٰتِ يَغْضُضْنَ مِنْ أَبْصَٰرِهِنَّ وَيَحْفَظْنَ فُرُوجَهُنَّ وَلَا يُبْدِينَ زِينَتَهُنَّ إِلَّا مَا ظَهَرَ مِنْهَا ۖ وَلْيَضْرِبْنَ بِخُمُرِهِنَّ عَلَىٰ جُيُوبِهِنَّ ۖ وَلَا يُبْدِينَ زِينَتَهُنَّ إِلَّا لِبُعُولَتِهِنَّ أَوْ ءَابَآئِهِنَّ أَوْ ءَابَآءِ بُعُولَتِهِنَّ أَوْ أَبْنَآئِهِنَّ أَوْ أَبْنَآءِ بُعُولَتِهِنَّ أَوْ إِخْوَٰنِهِنَّ أَوْ بَنِىٓ إِخْوَٰنِهِنَّ أَوْ بَنِىٓ أَخَوَٰتِهِنَّ أَوْ نِسَآئِهِنَّ أَوْ مَا مَلَكَتْ أَيْمَٰنُهُنَّ أَوِ ٱلتَّٰبِعِينَ غَيْرِ أُو۟لِى ٱلْإِرْبَةِ مِنَ ٱلرِّجَالِ أَوِ ٱلطِّفْلِ ٱلَّذِينَ لَمْ يَظْهَرُوا۟ عَلَىٰ عَوْرَٰتِ ٱلنِّسَآءِ ۖ وَلَا يَضْرِبْنَ بِأَرْجُلِهِنَّ لِيُعْلَمَ مَا يُخْفِينَ مِن زِينَتِهِنَّ ۚ وَتُوبُوٓا۟ إِلَى ٱللَّهِ جَمِيعًا أَيُّهَ ٱلْمُؤْمِنُونَ لَعَلَّكُمْ تُفْلِحُونَ',
    highlightStartIndex: 520,
    highlightEndIndex: 530,
  },
  {
    wordOrderIndex: 300,
    surahName: 'Al-An\'am',
    surahNum: 6,
    ayahNum: 73,
    arabicText: 'وَهُوَ ٱلَّذِى خَلَقَ ٱلسَّمَٰوَٰتِ وَٱلْأَرْضَ بِٱلْحَقِّ ۖ وَيَوْمَ يَقُولُ كُن فَيَكُونُ ۚ قَوْلُهُ ٱلْحَقُّ ۚ وَلَهُ ٱلْمُلْكُ يَوْمَ يُنفَخُ فِى ٱلصُّورِ ۚ عَٰلِمُ ٱلْغَيْبِ وَٱلشَّهَٰدَةِ ۚ وَهُوَ ٱلْحَكِيمُ ٱلْخَبِيرُ',
    highlightStartIndex: 161,
    highlightEndIndex: 168,
  },
];

// Skipped — verb forms not standalone (9 words):
// 17, 29, 63, 87, 138, 168, 213, 243, 259

// Skipped — common particles/prepositions (38 words):
// 101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 114, 115, 116, 118, 119, 120, 140, 176, 177, 179, 180, 181, 183, 184, 185, 186, 187, 188, 189, 276, 277, 278, 286, 287, 289, 290

// Failed to match (need manual review):
// orderIndex 8 (اية)
// orderIndex 12 (سماء)
// orderIndex 15 (حياة)
// orderIndex 20 (سمع)
// orderIndex 26 (امن)
// orderIndex 31 (قوم)
// orderIndex 34 (ظالم)
// orderIndex 36 (صلاة)
// orderIndex 43 (غفر)
// orderIndex 45 (ظلم)
// orderIndex 52 (اخرة)
// orderIndex 55 (جزاء)
// orderIndex 56 (قلب)
// orderIndex 59 (عقل)
// orderIndex 60 (صدر)
// orderIndex 61 (جاء)
// orderIndex 62 (دخل)
// orderIndex 64 (رجع)
// orderIndex 65 (اتبع)
// orderIndex 71 (ليل)
// orderIndex 75 (ماء)
// orderIndex 78 (ارسل)
// orderIndex 79 (اخذ)
// orderIndex 82 (كافر)
// orderIndex 84 (منافق)
// orderIndex 86 (اتى)
// orderIndex 90 (زكاة)
// orderIndex 96 (شاء)
// orderIndex 98 (احب)
// orderIndex 99 (خاف)
// orderIndex 100 (رضي)
// orderIndex 121 (شيء)
// orderIndex 122 (مكان)
// orderIndex 131 (اطاع)
// orderIndex 135 (نجى)
// orderIndex 155 (سال)
// orderIndex 161 (ملك)
// orderIndex 164 (خالد)
// orderIndex 169 (نساء)
// orderIndex 171 (مال)
// orderIndex 191 (اله)
// orderIndex 193 (اخر)
// orderIndex 203 (اهلك)
// orderIndex 204 (احيا)
// orderIndex 206 (مات)
// orderIndex 208 (حي)
// orderIndex 218 (تلا)
// orderIndex 219 (نظر)
// orderIndex 221 (قتل)
// orderIndex 222 (قاتل)
// orderIndex 225 (سجد)
// orderIndex 240 (قران)
// orderIndex 247 (ذنب)
// orderIndex 248 (سوء)
// orderIndex 249 (ظلم)
// orderIndex 250 (دعاء)
// orderIndex 251 (خشي)
// orderIndex 257 (رد)
// orderIndex 258 (زاد)
// orderIndex 260 (عقل)
// orderIndex 271 (عذب)
// orderIndex 273 (اكل)
// orderIndex 291 (الرحمن)
