export const LESSONS = [
  // ── TIER 1: FOUNDATION (Lessons 1-10) ──
  {
    orderIndex: 1,
    title: 'Words You Already Know',
    subtitle: 'Today: Mercy, Patience, and words you already know',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 2,
    title: 'The Foundations',
    subtitle: 'Allah, His Book, His Messenger, and the Truth',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 3,
    title: 'Your World',
    subtitle: 'Earth, sky, soul, light, and life',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 4,
    title: 'Actions That Matter',
    subtitle: 'Your first Arabic verbs — to know, to do, to create',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 5,
    title: 'Rewards and Consequences',
    subtitle: 'Paradise, fire, punishment, reward, forgiveness',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 6,
    title: 'Faith and Belief',
    subtitle: 'To believe, to worship, and the roots of Iman',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 7,
    title: 'The People of the Qur\'an',
    subtitle: 'Nations, prophets, servants, and the stories they carry',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 8,
    title: 'Your Daily Worship',
    subtitle: 'Prayer, gratitude, provision, blessing, wisdom',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 9,
    title: 'Powerful Verbs',
    subtitle: 'To say, to call, to forgive, to remember',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 10,
    title: 'The Journey',
    subtitle: 'The path, the day, and the road ahead',
    wordCount: 5,
    isPublished: true,
  },

  // ── TIER 2: EXPANDED (Lessons 11-20) ──
  {
    orderIndex: 11,
    title: 'What Comes Next',
    subtitle: 'This world, the next, and the reckoning between',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 12,
    title: 'Heart and Mind',
    subtitle: 'The heart, the soul, sight, and reason',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 13,
    title: 'Coming and Going',
    subtitle: 'Verbs of motion — to come, to enter, to leave, to follow',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 14,
    title: 'Good and Evil',
    subtitle: 'The righteous, the great, and the distinction between good and evil',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 15,
    title: 'Day and Night',
    subtitle: 'Sun, moon, water, and the rhythm of creation',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 16,
    title: 'Seeing and Sending',
    subtitle: 'To see, to reveal, to send — how Allah acts in the world',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 17,
    title: 'Religion and Identity',
    subtitle: 'Deen, Muslim, Kafir, Munafiq — the labels the Qur\'an uses',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 18,
    title: 'Giving and Spending',
    subtitle: 'To give, to spend, and the grace of Allah',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 19,
    title: 'Power and Authority',
    subtitle: 'Kings, kingdoms, thrones, and divine dominion',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 20,
    title: 'Desire and Will',
    subtitle: 'To will, to want, to love, to fear, to be pleased',
    wordCount: 5,
    isPublished: true,
  },

  // ── TIER 3: INTERMEDIATE (Lessons 21-30) ──
  {
    orderIndex: 21,
    title: 'From, In, On',
    subtitle: 'The tiny words that connect everything in the Qur\'an',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 22,
    title: 'The Connecting Words',
    subtitle: 'Indeed, not, every, except — the glue of Quranic sentences',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 23,
    title: 'Who, Which, This, That',
    subtitle: 'The pointing words that unlock Quranic phrases',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 24,
    title: 'Saying No',
    subtitle: 'Three types of "not," questions, and hypotheticals',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 25,
    title: 'Things and Places',
    subtitle: 'Things, houses, mosques, and where life happens',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 26,
    title: 'Words and Speech',
    subtitle: 'Words, sayings, remembrance, and the power of language',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 27,
    title: 'Obedience and Rebellion',
    subtitle: 'To obey, to disobey, to repent, to be saved',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 28,
    title: 'Promises and Warnings',
    subtitle: 'Promises, warnings, glad tidings, and what lies ahead',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 29,
    title: 'Allah\'s Beautiful Names',
    subtitle: 'Al-Aleem, Ar-Rahim, Al-Ghafoor — patterns of divine names',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 30,
    title: 'Covenants and Testimony',
    subtitle: 'Promises, witnesses, judgment, and the people of the covenant',
    wordCount: 5,
    isPublished: true,
  },

  // ── TIER 4: ADVANCED (Lessons 31-40) ──
  {
    orderIndex: 31,
    title: 'The Essential Verb',
    subtitle: 'To be, to find, to ask — the verbs that hold sentences together',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 32,
    title: 'The Human Being',
    subtitle: 'Face, hand, eye, creation — the body in the Qur\'an',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 33,
    title: 'Angels and Devils',
    subtitle: 'Angels, Satan, Hellfire, and the companions of the hereafter',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 34,
    title: 'Family',
    subtitle: 'Children, brothers, women, and the bonds of family',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 35,
    title: 'Wealth and Deeds',
    subtitle: 'Wealth, deeds, earnings, and what truly matters',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 36,
    title: 'Then, Or, Until',
    subtitle: 'The connectors that chain Quranic events together',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 37,
    title: 'Before, After, Between',
    subtitle: 'Time and place words that structure the Qur\'an\'s message',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 38,
    title: 'O You Who Believe',
    subtitle: 'Breaking down the Qur\'an\'s most famous address',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 39,
    title: 'There Is No God But Allah',
    subtitle: 'Deconstructing the Shahada — you already know every word',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 40,
    title: 'Victory and Struggle',
    subtitle: 'Victory, trials, enemies, and the guardians of faith',
    wordCount: 5,
    isPublished: true,
  },

  // ── TIER 5: CONTEXTUAL (Lessons 41-50) ──
  {
    orderIndex: 41,
    title: 'Divine Actions',
    subtitle: 'To reveal, to bring forth, to destroy, to give life',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 42,
    title: 'Life and Death',
    subtitle: 'To die, to resurrect, to live — the cycle the Qur\'an describes',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 43,
    title: 'Judgment and Decree',
    subtitle: 'To decree, to judge, to testify, and the consequence',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 44,
    title: 'Teaching and Writing',
    subtitle: 'To write, to teach, to recite, to look — verbs of learning',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 45,
    title: 'Struggle and Patience',
    subtitle: 'Fighting, patience, gratitude, and prostration',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 46,
    title: 'Praise and Peace',
    subtitle: 'SubhanAllah, Alhamdulillah, Salam — words you say every day',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 47,
    title: 'More Divine Attributes',
    subtitle: 'Al-Aziz, Al-Karim, Al-Qadir — more of Allah\'s beautiful names',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 48,
    title: 'Communities and Peoples',
    subtitle: 'Ummah, worlds, offspring, and the Qur\'an itself',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 49,
    title: 'Going Astray',
    subtitle: 'Misguidance, shirk, disbelief — the Qur\'an\'s warnings',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 50,
    title: 'The Unseen',
    subtitle: 'The unseen, sin, evil, oppression, and the power of dua',
    wordCount: 5,
    isPublished: true,
  },

  // ── TIER 6: COMPLETION (Lessons 51-60) ──
  {
    orderIndex: 51,
    title: 'More Actions',
    subtitle: 'To fear reverentially, to leave, to reach, to forbid',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 52,
    title: 'Establishing and Increasing',
    subtitle: 'To establish prayer, to return, to increase, to reason',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 53,
    title: 'Nature',
    subtitle: 'Sea, rivers, wind, mountains, trees — Allah\'s signs in creation',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 54,
    title: 'People Types',
    subtitle: 'The poor, the rich, the transgressor — character in the Qur\'an',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 55,
    title: 'Punishment and Glorification',
    subtitle: 'To punish, to glorify, to eat — and the God-fearing ones',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 56,
    title: 'Position and Direction',
    subtitle: 'Above, below, beside, first — where things stand in the Qur\'an',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 57,
    title: 'Warnings and Truth',
    subtitle: 'Warners, fear, lies, falsehood, and good deeds',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 58,
    title: 'More Particles',
    subtitle: 'If, that, or, when — the final connecting words',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 59,
    title: 'The Most Merciful',
    subtitle: 'Ar-Rahman, Haram, and the roots of mercy across the Qur\'an',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 60,
    title: 'Your Journey Complete',
    subtitle: 'From Ilm to Aalim — 300 words, one incredible journey',
    wordCount: 5,
    isPublished: true,
  },
];
