export const LESSONS = [
  {
    orderIndex: 1,
    title: 'Words You Already Know',
    subtitle: 'Today: Mercy, Patience, and words you already know',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 2,
    title: 'The Source',
    subtitle: 'Allah, His Book, His Messenger, and the Truth',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 3,
    title: 'Your World',
    subtitle: 'Earth, sky, soul, light, and life',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 4,
    title: 'Actions That Matter',
    subtitle: 'Your first Arabic verbs — to know, to do, to create',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 5,
    title: 'Rewards and Consequences',
    subtitle: 'Paradise, fire, punishment, reward, forgiveness',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 6,
    title: 'Faith and Belief',
    subtitle: 'To believe, to worship, to fear Allah',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 7,
    title: 'The People of the Qur\'an',
    subtitle: 'Nations, prophets, servants, and the stories they carry',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 8,
    title: 'Your Daily Worship',
    subtitle: 'Prayer, gratitude, provision, blessing, wisdom',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 9,
    title: 'Powerful Verbs',
    subtitle: 'To say, to call, to forgive, to remember',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 10,
    title: 'The Journey',
    subtitle: 'Life, death, and the path forward',
    wordCount: 5,
    isPublished: true,
  },
];
