export const LESSONS = [
  {
    orderIndex: 1,
    title: 'Words You Already Know',
    subtitle: 'Today: Mercy, Patience, and words you already know',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 2,
    title: 'The Foundations',
    subtitle: 'The most important words in the Qur\'an',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 3,
    title: 'Your World',
    subtitle: 'Earth, sky, soul, light, and life',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 4,
    title: 'Actions That Matter',
    subtitle: 'Your first Arabic verbs — to know, to do, to create',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 5,
    title: 'Rewards and Consequences',
    subtitle: 'Paradise, fire, punishment, reward, forgiveness',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 6,
    title: 'Faith and Belief',
    subtitle: 'To believe, to worship, to fear Allah',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 7,
    title: 'People',
    subtitle: 'Nation, mankind, servant, prophet',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 8,
    title: 'Spiritual Life',
    subtitle: 'Prayer, gratitude, provision, blessing, wisdom',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 9,
    title: 'Powerful Verbs',
    subtitle: 'To say, to call, to forgive, to remember',
    wordCount: 5,
    isPublished: true,
  },
  {
    orderIndex: 10,
    title: 'The Journey',
    subtitle: 'Path, day, command, and the ultimate destination',
    wordCount: 5,
    isPublished: true,
  },
];
