import { IntroductionStyle } from '@prisma/client';

export interface WordSeedData {
  orderIndex: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  frequency: number;
  isUrduCognate: boolean;
  urduCognateNote: string | null;
  audioUrl: string;
  lessonOrderIndex: number;
  introduction: {
    style: IntroductionStyle;
    headline: string;
    body: string;
    ayahText?: string;
    ayahRef?: string;
    factStat?: string;
    quickCheckQuestion?: string;
    quickCheckOptions?: string[];
    quickCheckAnswer?: number;
  };
}

export const WORDS: WordSeedData[] = [
  // ── Lesson 1: "Words You Already Know" ──
  {
    orderIndex: 1,
    arabic: 'رَبّ',
    transliteration: 'Rabb',
    meaning: 'Lord, Sustainer',
    frequency: 975,
    isUrduCognate: true,
    urduCognateNote: 'Same word in Urdu — "Ya Rabb!" means "O Lord!"',
    audioUrl: '/audio/words/rabb.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'You say this in every dua',
      body: 'The word رَبّ (Rabb) means "Lord" or "Sustainer." You already use this word in Urdu every day — "Ya Rabb!" It appears 975 times in the Qur\'an, making it one of the most frequent words.',
    },
  },
  {
    orderIndex: 2,
    arabic: 'رَحْمَة',
    transliteration: 'Rahmah',
    meaning: 'Mercy',
    frequency: 339,
    isUrduCognate: true,
    urduCognateNote: 'From the same root as Ar-Rahman and Ar-Raheem',
    audioUrl: '/audio/words/rahmah.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The root of Bismillah',
      body: 'رَحْمَة (Rahmah) means "Mercy." You hear it every time you say "Bismillah ir-Rahman ir-Raheem." Let\'s see where it appears in the Qur\'an.',
      ayahText: 'وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ',
      ayahRef: 'Al-A\'raf 7:156',
    },
  },
  {
    orderIndex: 3,
    arabic: 'عِلْم',
    transliteration: 'Ilm',
    meaning: 'Knowledge',
    frequency: 382,
    isUrduCognate: true,
    urduCognateNote: 'Used constantly in Urdu — "ilm" means knowledge',
    audioUrl: '/audio/words/ilm.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s favorite topic',
      body: 'عِلْم (Ilm) means "Knowledge." You already use this word in Urdu all the time.',
      factStat: 'The word "Ilm" and its derivatives appear 780+ times in the Qur\'an. No other book in history emphasizes knowledge this much.',
    },
  },
  {
    orderIndex: 4,
    arabic: 'صَبْر',
    transliteration: 'Sabr',
    meaning: 'Patience',
    frequency: 103,
    isUrduCognate: true,
    urduCognateNote: 'Identical in Urdu — "sabr karo" means "be patient"',
    audioUrl: '/audio/words/sabr.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'صَبْر (Sabr) — you definitely know this one from Urdu. But do you know what it means in Arabic?',
      quickCheckQuestion: 'What does صَبْر (Sabr) mean?',
      quickCheckOptions: ['Patience', 'Speed', 'Strength', 'Wisdom'],
      quickCheckAnswer: 0,
    },
  },
  {
    orderIndex: 5,
    arabic: 'هُدَى',
    transliteration: 'Huda',
    meaning: 'Guidance',
    frequency: 144,
    isUrduCognate: true,
    urduCognateNote: 'Related to "hidayat" in Urdu — guidance',
    audioUrl: '/audio/words/huda.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Hidden in your daily prayer',
      body: 'هُدَى (Huda) means "Guidance." You say this in every prayer when you recite Al-Fatiha: "Ihdinas-siratal-mustaqeem" — "Guide us to the straight path." The word هُدَى is at the heart of that dua.',
    },
  },

  // ── Lesson 2: "The Source" ──
  {
    orderIndex: 6,
    arabic: 'اللَّه',
    transliteration: 'Allah',
    meaning: 'God',
    frequency: 2699,
    isUrduCognate: true,
    urduCognateNote: 'The same word used across all Muslim cultures',
    audioUrl: '/audio/words/allah.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The most frequent word',
      body: 'اللَّه (Allah) — the name of God. The most sacred and most frequently used noun in the entire Qur\'an.',
      factStat: 'Allah appears 2,699 times in the Qur\'an — more than any other noun. That\'s an average of 23 times per surah.',
    },
  },
  {
    orderIndex: 7,
    arabic: 'كِتَاب',
    transliteration: 'Kitab',
    meaning: 'Book',
    frequency: 260,
    isUrduCognate: true,
    urduCognateNote: 'Used in Urdu for book — "kitab"',
    audioUrl: '/audio/words/kitab.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Same word, same meaning',
      body: 'كِتَاب (Kitab) means "Book." This is exactly the same word you use in Urdu. When Allah refers to the Qur\'an, He often calls it "Al-Kitab" — The Book.',
    },
  },
  {
    orderIndex: 8,
    arabic: 'آيَة',
    transliteration: 'Ayah',
    meaning: 'Sign, Verse',
    frequency: 382,
    isUrduCognate: true,
    urduCognateNote: 'Used in Urdu to mean a verse of the Qur\'an',
    audioUrl: '/audio/words/ayah.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'More than just a verse',
      body: 'آيَة (Ayah) means "Sign" or "Verse." Every verse of the Qur\'an is called an Ayah because each one is a sign from Allah.',
      ayahText: 'إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِّقَوْمٍ يَتَفَكَّرُونَ',
      ayahRef: 'Ar-Ra\'d 13:3',
    },
  },
  {
    orderIndex: 9,
    arabic: 'رَسُول',
    transliteration: 'Rasool',
    meaning: 'Messenger',
    frequency: 332,
    isUrduCognate: true,
    urduCognateNote: 'Same word in Urdu — "Rasool Allah"',
    audioUrl: '/audio/words/rasool.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'In your Shahada, daily',
      body: 'رَسُول (Rasool) means "Messenger." You say this word multiple times every day in the Shahada and in Durood: "Muhammad ur Rasool Allah" — Muhammad is the Messenger of Allah.',
    },
  },
  {
    orderIndex: 10,
    arabic: 'حَقّ',
    transliteration: 'Haqq',
    meaning: 'Truth',
    frequency: 242,
    isUrduCognate: true,
    urduCognateNote: '"Haqq" is used in Urdu for truth and right',
    audioUrl: '/audio/words/haqq.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'حَقّ (Haqq) — you\'ve heard this many times. "Al-Haqq" is also one of Allah\'s names.',
      quickCheckQuestion: 'What does حَقّ (Haqq) mean?',
      quickCheckOptions: ['Truth', 'Peace', 'Book', 'Light'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 3: "Your World" ──
  {
    orderIndex: 11,
    arabic: 'أَرْض',
    transliteration: 'Ard',
    meaning: 'Earth',
    frequency: 461,
    isUrduCognate: false,
    urduCognateNote: 'Partially similar — "arz" is sometimes used in Urdu poetry',
    audioUrl: '/audio/words/ard.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The other half of creation',
      body: 'أَرْض (Ard) means "Earth" or "Land." The Qur\'an often pairs this word with سَمَاء (sky) to describe the entire creation.',
      factStat: '"Earth" appears 461 times in the Qur\'an — almost always paired with "sky" to represent all of creation.',
    },
  },
  {
    orderIndex: 12,
    arabic: 'سَمَاء',
    transliteration: 'Sama',
    meaning: 'Sky, Heaven',
    frequency: 310,
    isUrduCognate: false,
    urduCognateNote: 'Partially known — "asman" in Urdu comes from Persian, but "sama" is recognized',
    audioUrl: '/audio/words/sama.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Look up',
      body: 'سَمَاء (Sama) means "Sky" or "Heaven." In the Qur\'an, Allah often draws our attention upward.',
      ayahText: 'أَفَلَمْ يَنظُرُوا إِلَى السَّمَاءِ فَوْقَهُمْ كَيْفَ بَنَيْنَاهَا',
      ayahRef: 'Qaf 50:6',
    },
  },
  {
    orderIndex: 13,
    arabic: 'نَفْس',
    transliteration: 'Nafs',
    meaning: 'Self, Soul',
    frequency: 295,
    isUrduCognate: true,
    urduCognateNote: '"Nafs" is used in Urdu for self/ego — "nafs par qabu"',
    audioUrl: '/audio/words/nafs.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The Urdu word for \'nafs\'',
      body: 'نَفْس (Nafs) means "Self" or "Soul." In Urdu you say "nafs par qabu rakho" (control yourself). The Qur\'an talks about three types of nafs — the commanding self, the self-reproaching self, and the peaceful self.',
    },
  },
  {
    orderIndex: 14,
    arabic: 'نُور',
    transliteration: 'Noor',
    meaning: 'Light',
    frequency: 194,
    isUrduCognate: true,
    urduCognateNote: '"Noor" is a common name and word in Urdu meaning light',
    audioUrl: '/audio/words/noor.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A name you definitely know',
      body: 'نُور (Noor) means "Light." This is probably a name you know — many people are named Noor. There\'s an entire surah called An-Noor (The Light). When people say someone has "noor on their face," they\'re using this Qur\'anic word.',
    },
  },
  {
    orderIndex: 15,
    arabic: 'حَيَاة',
    transliteration: 'Hayat',
    meaning: 'Life',
    frequency: 190,
    isUrduCognate: true,
    urduCognateNote: '"Hayat" is used in Urdu for life — "hayat-e-insani"',
    audioUrl: '/audio/words/hayat.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'حَيَاة (Hayat) — a beautiful word you use in Urdu too.',
      quickCheckQuestion: 'What does حَيَاة (Hayat) mean?',
      quickCheckOptions: ['Life', 'Death', 'Time', 'World'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 4: "Actions That Matter" ──
  {
    orderIndex: 16,
    arabic: 'عَلِمَ',
    transliteration: 'Alima',
    meaning: 'to know',
    frequency: 382,
    isUrduCognate: true,
    urduCognateNote: 'Root of "ilm" (knowledge) and "aalim" (scholar)',
    audioUrl: '/audio/words/alima.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'You already know the root!',
      body: 'عَلِمَ (Alima) means "to know." Remember عِلْم (Ilm) from Lesson 1? Same root! Arabic builds families of meaning from roots. عِلْم = knowledge, عَلِمَ = to know, عَالِم = scholar. You already know all these from Urdu.',
    },
  },
  {
    orderIndex: 17,
    arabic: 'عَمِلَ',
    transliteration: 'Amila',
    meaning: 'to do, to work',
    frequency: 276,
    isUrduCognate: true,
    urduCognateNote: '"Amal" (deed/action) comes from this root',
    audioUrl: '/audio/words/amila.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Qur\'an\'s favorite phrase',
      body: 'عَمِلَ (Amila) means "to do" or "to work." The phrase "alladhina aamanu wa amilus-salihaat" (those who believe and do good deeds) appears dozens of times in the Qur\'an.',
      ayahText: 'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ',
      ayahRef: 'Al-Baqarah 2:277',
    },
  },
  {
    orderIndex: 18,
    arabic: 'خَلَقَ',
    transliteration: 'Khalaqa',
    meaning: 'to create',
    frequency: 184,
    isUrduCognate: true,
    urduCognateNote: '"Khalq" (creation) and "Khaliq" (Creator) come from this root',
    audioUrl: '/audio/words/khalaqa.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Did you know?',
      body: 'خَلَقَ (Khalaqa) means "to create." Al-Khaliq (The Creator) is one of Allah\'s 99 names.',
      factStat: 'The very first word revealed to Prophet Muhammad ﷺ was "Iqra" (Read), and in those first verses, خَلَقَ appears: "Who created man from a clinging substance."',
    },
  },
  {
    orderIndex: 19,
    arabic: 'هَدَى',
    transliteration: 'Hada',
    meaning: 'to guide',
    frequency: 144,
    isUrduCognate: true,
    urduCognateNote: 'Root of "hidayat" (guidance) in Urdu',
    audioUrl: '/audio/words/hada.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this in every prayer!',
      body: 'هَدَى (Hada) means "to guide." Remember هُدَى (Huda/guidance) from Lesson 1? Same root! In Al-Fatiha, you ask "Ihdina" (guide us) — that\'s this very verb. Every time you pray, you\'re using this word.',
    },
  },
  {
    orderIndex: 20,
    arabic: 'سَمِعَ',
    transliteration: 'Sami\'a',
    meaning: 'to hear',
    frequency: 78,
    isUrduCognate: true,
    urduCognateNote: '"Sami" (hearing) — As-Sami is one of Allah\'s names',
    audioUrl: '/audio/words/samia.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'سَمِعَ (Sami\'a) — As-Sami\' (The All-Hearing) is one of Allah\'s names. What does this verb mean?',
      quickCheckQuestion: 'What does سَمِعَ (Sami\'a) mean?',
      quickCheckOptions: ['to hear', 'to see', 'to speak', 'to know'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 5: "Rewards and Consequences" ──
  {
    orderIndex: 21,
    arabic: 'جَنَّة',
    transliteration: 'Jannah',
    meaning: 'Paradise, Garden',
    frequency: 147,
    isUrduCognate: true,
    urduCognateNote: '"Jannat" — same word used in Urdu for paradise',
    audioUrl: '/audio/words/jannah.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Your Urdu word for Paradise',
      body: 'جَنَّة (Jannah) means "Paradise" or "Garden." You know this word from Urdu — "Jannat." The literal meaning is "garden," and the Qur\'an describes it as gardens with rivers flowing beneath.',
    },
  },
  {
    orderIndex: 22,
    arabic: 'نَار',
    transliteration: 'Nar',
    meaning: 'Fire, Hell',
    frequency: 145,
    isUrduCognate: true,
    urduCognateNote: '"Naar" is used in Urdu — "jahannam ki nar"',
    audioUrl: '/audio/words/nar.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Qur\'an\'s warning',
      body: 'نَار (Nar) means "Fire" — referring to the Hellfire. In the Qur\'an, Jannah and Nar are often mentioned together as the two ultimate destinations.',
      ayahText: 'فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ',
      ayahRef: 'Al-Baqarah 2:24',
    },
  },
  {
    orderIndex: 23,
    arabic: 'عَذَاب',
    transliteration: 'Adhab',
    meaning: 'Punishment',
    frequency: 322,
    isUrduCognate: true,
    urduCognateNote: '"Azaab" in Urdu — same word, same meaning',
    audioUrl: '/audio/words/adhab.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'A word with weight',
      body: 'عَذَاب (Adhab) means "Punishment" — you know it as "azaab" in Urdu.',
      factStat: '"Adhab" appears 322 times in the Qur\'an. It\'s almost always followed by a qualifier: "adhab aleem" (painful), "adhab shadeed" (severe), or "adhab al-nar" (punishment of fire).',
    },
  },
  {
    orderIndex: 24,
    arabic: 'أَجْر',
    transliteration: 'Ajr',
    meaning: 'Reward',
    frequency: 105,
    isUrduCognate: true,
    urduCognateNote: '"Ajr" is used in Urdu for reward/compensation',
    audioUrl: '/audio/words/ajr.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A word you hear in khutbahs',
      body: 'أَجْر (Ajr) means "Reward." You hear this constantly in Islamic talks: "Allah will give you ajr for this." In the Qur\'an, believers are promised "ajr azeem" — a great reward.',
    },
  },
  {
    orderIndex: 25,
    arabic: 'مَغْفِرَة',
    transliteration: 'Maghfirah',
    meaning: 'Forgiveness',
    frequency: 127,
    isUrduCognate: true,
    urduCognateNote: '"Maghfirat" in Urdu — asking for Allah\'s forgiveness',
    audioUrl: '/audio/words/maghfirah.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'مَغْفِرَة (Maghfirah) — "Astaghfirullah" (I seek Allah\'s forgiveness) comes from the same root.',
      quickCheckQuestion: 'What does مَغْفِرَة (Maghfirah) mean?',
      quickCheckOptions: ['Forgiveness', 'Punishment', 'Patience', 'Mercy'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 6: "Faith and Belief" ──
  {
    orderIndex: 26,
    arabic: 'آمَنَ',
    transliteration: 'Aamana',
    meaning: 'to believe',
    frequency: 537,
    isUrduCognate: true,
    urduCognateNote: 'Root of "iman" (faith) and "mu\'min" (believer)',
    audioUrl: '/audio/words/aamana.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The most important verb',
      body: 'آمَنَ (Aamana) means "to believe." The root gives us "Iman" (faith), "Mu\'min" (believer), and "Ameen" (trustworthy).',
      factStat: '"Aamana" and its forms appear 537 times — making "belief" one of the most repeated concepts in the Qur\'an.',
    },
  },
  {
    orderIndex: 27,
    arabic: 'كَفَرَ',
    transliteration: 'Kafara',
    meaning: 'to disbelieve',
    frequency: 289,
    isUrduCognate: true,
    urduCognateNote: '"Kufr" in Urdu comes from this root — literally "covering" the truth',
    audioUrl: '/audio/words/kafara.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'See the contrast in the Qur\'an',
      body: 'كَفَرَ (Kafara) literally means "to cover" — as in covering the truth. The Qur\'an uses it for denial or disbelief, and often pairs آمَنَ (to believe) with كَفَرَ (to disbelieve) to show the two paths.',
      ayahText: 'هُوَ الَّذِي خَلَقَكُمْ فَمِنكُمْ كَافِرٌ وَمِنكُم مُّؤْمِنٌ',
      ayahRef: 'At-Taghabun 64:2',
    },
  },
  {
    orderIndex: 28,
    arabic: 'مُؤْمِن',
    transliteration: 'Mu\'min',
    meaning: 'Believer',
    frequency: 195,
    isUrduCognate: true,
    urduCognateNote: '"Momin" in Urdu — a person of faith',
    audioUrl: '/audio/words/mumin.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Your identity as a Muslim',
      body: 'مُؤْمِن (Mu\'min) means "Believer." This comes from the same root as آمَنَ (to believe) that you just learned. In Urdu, "Momin" is both a name and a title for a person of faith. Al-Mu\'min is also one of Allah\'s names — The Guardian of Faith.',
    },
  },
  {
    orderIndex: 29,
    arabic: 'عَبَدَ',
    transliteration: 'Abada',
    meaning: 'to worship',
    frequency: 122,
    isUrduCognate: true,
    urduCognateNote: '"Ibadat" (worship) in Urdu comes from this root',
    audioUrl: '/audio/words/abada.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The purpose of creation',
      body: 'عَبَدَ (Abada) means "to worship." The word "ibadat" in Urdu comes from this root. In one of the most famous ayahs, Allah says: "I did not create jinn and mankind except to worship Me." Every salah you pray is an act of \'ibadah.',
    },
  },
  {
    orderIndex: 30,
    arabic: 'اتَّقَى',
    transliteration: 'Ittaqa',
    meaning: 'to fear Allah, be righteous',
    frequency: 166,
    isUrduCognate: true,
    urduCognateNote: '"Taqwa" in Urdu — God-consciousness',
    audioUrl: '/audio/words/ittaqa.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'اتَّقَى (Ittaqa) — the root of "Taqwa," one of the most important concepts in Islam.',
      quickCheckQuestion: 'What does اتَّقَى (Ittaqa) relate to?',
      quickCheckOptions: ['God-consciousness / Taqwa', 'Physical strength', 'Wealth', 'Intelligence'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 7: "The People of the Qur'an" ──
  {
    orderIndex: 31,
    arabic: 'قَوْم',
    transliteration: 'Qawm',
    meaning: 'People, Nation',
    frequency: 383,
    isUrduCognate: true,
    urduCognateNote: '"Qaum" in Urdu means nation/people',
    audioUrl: '/audio/words/qawm.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A word from Pakistan\'s story',
      body: 'قَوْم (Qawm) means "People" or "Nation." Identical to the Urdu word "qaum." In the Qur\'an, prophets are always sent to their qawm — "Ya qawmi!" (O my people!) is a phrase you\'ll see repeatedly.',
    },
  },
  {
    orderIndex: 32,
    arabic: 'نَاس',
    transliteration: 'Nas',
    meaning: 'Mankind',
    frequency: 241,
    isUrduCognate: true,
    urduCognateNote: 'You know Surah An-Nas — "mankind"',
    audioUrl: '/audio/words/nas.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A surah you already know!',
      body: 'نَاس (Nas) means "Mankind" or "People." You already know this from Surah An-Nas, which you may have memorized: "Qul a\'udhu bi Rabbin-Nas" — "Say: I seek refuge in the Lord of mankind."',
    },
  },
  {
    orderIndex: 33,
    arabic: 'عَبْد',
    transliteration: 'Abd',
    meaning: 'Servant',
    frequency: 275,
    isUrduCognate: true,
    urduCognateNote: 'Common in names — Abdullah means "servant of Allah"',
    audioUrl: '/audio/words/abd.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The highest title',
      body: 'عَبْد (Abd) means "Servant." Abdullah (servant of Allah) is one of the most common Muslim names. The Qur\'an calls Prophet Muhammad ﷺ "Abduhu" (His servant).',
      ayahText: 'سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا',
      ayahRef: 'Al-Isra 17:1',
    },
  },
  {
    orderIndex: 34,
    arabic: 'ظَالِم',
    transliteration: 'Zalim',
    meaning: 'Oppressor',
    frequency: 110,
    isUrduCognate: true,
    urduCognateNote: '"Zalim" in Urdu — an unjust person',
    audioUrl: '/audio/words/zalim.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'A word with layers',
      body: 'ظَالِم (Zalim) means "Oppressor" or "Wrongdoer." You know this word from Urdu.',
      factStat: 'In Arabic, "zulm" literally means "to put something in the wrong place." So a zalim isn\'t just cruel — they\'re someone who puts things where they don\'t belong, including denying Allah\'s rights.',
    },
  },
  {
    orderIndex: 35,
    arabic: 'نَبِيّ',
    transliteration: 'Nabi',
    meaning: 'Prophet',
    frequency: 75,
    isUrduCognate: true,
    urduCognateNote: '"Nabi" in Urdu — prophet',
    audioUrl: '/audio/words/nabi.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'نَبِيّ (Nabi) — a word every Muslim knows.',
      quickCheckQuestion: 'What does نَبِيّ (Nabi) mean?',
      quickCheckOptions: ['Prophet', 'King', 'Scholar', 'Angel'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 8: "Your Daily Worship" ──
  {
    orderIndex: 36,
    arabic: 'صَلَاة',
    transliteration: 'Salah',
    meaning: 'Prayer',
    frequency: 99,
    isUrduCognate: true,
    urduCognateNote: 'You know this as "Namaz" — the Qur\'an calls it "Salah"',
    audioUrl: '/audio/words/salah.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your 5 daily connection',
      body: 'صَلَاة (Salah) means "Prayer." You know this as namaz. In the Qur\'an, Allah uses the beautiful word Salah. Every time the Qur\'an commands prayer, it uses this word. You perform salah 5 times a day — now you know the word Allah uses for it.',
    },
  },
  {
    orderIndex: 37,
    arabic: 'شُكْر',
    transliteration: 'Shukr',
    meaning: 'Gratitude',
    frequency: 75,
    isUrduCognate: true,
    urduCognateNote: '"Shukriya" (thank you) comes from this root',
    audioUrl: '/audio/words/shukr.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'You say this every day!',
      body: 'شُكْر (Shukr) means "Gratitude." Every time you say "shukriya" in Urdu, you\'re using this Arabic root. Ash-Shakoor (The Most Grateful) is one of Allah\'s names.',
    },
  },
  {
    orderIndex: 38,
    arabic: 'رِزْق',
    transliteration: 'Rizq',
    meaning: 'Provision',
    frequency: 123,
    isUrduCognate: true,
    urduCognateNote: '"Rizq" is used in Urdu — provision/sustenance from Allah',
    audioUrl: '/audio/words/rizq.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'More than just money',
      body: 'رِزْق (Rizq) means "Provision" or "Sustenance." Not just food — it includes wealth, health, children, knowledge. Everything Allah provides.',
      ayahText: 'إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ',
      ayahRef: 'Adh-Dhariyat 51:58',
    },
  },
  {
    orderIndex: 39,
    arabic: 'نِعْمَة',
    transliteration: 'Ni\'mah',
    meaning: 'Blessing',
    frequency: 144,
    isUrduCognate: true,
    urduCognateNote: '"Naimat" in Urdu — blessing, bounty',
    audioUrl: '/audio/words/nimah.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Count your blessings',
      body: 'نِعْمَة (Ni\'mah) means "Blessing" or "Favor." In Urdu, "naimat" carries the same meaning.',
      factStat: 'Allah challenges us: "If you tried to count Allah\'s blessings, you could never enumerate them" (Ibrahim 14:34). The word ni\'mah appears 144 times, reminding us constantly.',
    },
  },
  {
    orderIndex: 40,
    arabic: 'حِكْمَة',
    transliteration: 'Hikmah',
    meaning: 'Wisdom',
    frequency: 39,
    isUrduCognate: true,
    urduCognateNote: '"Hikmat" in Urdu — wisdom, a divine quality',
    audioUrl: '/audio/words/hikmah.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'حِكْمَة (Hikmah) — Al-Hakeem (The All-Wise) is one of Allah\'s names, from this same root.',
      quickCheckQuestion: 'What does حِكْمَة (Hikmah) mean?',
      quickCheckOptions: ['Wisdom', 'Power', 'Beauty', 'Justice'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 9: "Powerful Verbs" ──
  {
    orderIndex: 41,
    arabic: 'قَالَ',
    transliteration: 'Qala',
    meaning: 'to say',
    frequency: 1618,
    isUrduCognate: false,
    urduCognateNote: 'Not a direct cognate, but "qaul" (saying) is used in Urdu',
    audioUrl: '/audio/words/qala.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The #1 verb in the Qur\'an',
      body: 'قَالَ (Qala) means "to say" or "he said." This is the single most frequent verb in the entire Qur\'an.',
      factStat: '"Qala" appears 1,618 times — because the Qur\'an is full of dialogue. Allah speaks, prophets speak, angels speak, and even the disbelievers speak. When you see قَالَ, a conversation is happening.',
    },
  },
  {
    orderIndex: 42,
    arabic: 'دَعَا',
    transliteration: 'Da\'a',
    meaning: 'to call, to pray',
    frequency: 170,
    isUrduCognate: true,
    urduCognateNote: '"Dua" (supplication) comes from this root',
    audioUrl: '/audio/words/daa.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Every dua starts here',
      body: 'دَعَا (Da\'a) means "to call" or "to pray/supplicate." This is the root of "dua" — your personal prayers to Allah. Every time you make dua, you\'re using this verb.',
    },
  },
  {
    orderIndex: 43,
    arabic: 'غَفَرَ',
    transliteration: 'Ghafara',
    meaning: 'to forgive',
    frequency: 65,
    isUrduCognate: true,
    urduCognateNote: '"Astaghfar" and "maghfirat" come from this root',
    audioUrl: '/audio/words/ghafara.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A word you use daily',
      body: 'غَفَرَ (Ghafara) means "to forgive." Remember مَغْفِرَة (Maghfirah/forgiveness) from Lesson 5? Same root! And "Astaghfirullah" (I seek Allah\'s forgiveness) — you\'re using this verb every time you say it. Al-Ghafoor (The Most Forgiving) is one of Allah\'s most frequently mentioned names.',
    },
  },
  {
    orderIndex: 44,
    arabic: 'ذَكَرَ',
    transliteration: 'Dhakara',
    meaning: 'to remember, to mention',
    frequency: 84,
    isUrduCognate: true,
    urduCognateNote: '"Zikr" (remembrance of Allah) comes from this root',
    audioUrl: '/audio/words/dhakara.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Allah\'s beautiful promise',
      body: 'ذَكَرَ (Dhakara) means "to remember" or "to mention." "Zikr" (remembrance of Allah) comes from this root.',
      ayahText: 'فَاذْكُرُونِي أَذْكُرْكُمْ',
      ayahRef: 'Al-Baqarah 2:152',
    },
  },
  {
    orderIndex: 45,
    arabic: 'ظَلَمَ',
    transliteration: 'Zalama',
    meaning: 'to oppress, to wrong',
    frequency: 110,
    isUrduCognate: true,
    urduCognateNote: '"Zulm" (oppression) — same root as "zalim"',
    audioUrl: '/audio/words/zalama.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Quick check!',
      body: 'ظَلَمَ (Zalama) — remember ظَالِم (Zalim/oppressor) from Lesson 7? This is the verb form.',
      quickCheckQuestion: 'What does ظَلَمَ (Zalama) mean?',
      quickCheckOptions: ['to oppress / to wrong', 'to forgive', 'to create', 'to believe'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 10: "The Journey" ──
  {
    orderIndex: 46,
    arabic: 'مَوْت',
    transliteration: 'Mawt',
    meaning: 'Death',
    frequency: 165,
    isUrduCognate: true,
    urduCognateNote: '"Maut" in Urdu — death',
    audioUrl: '/audio/words/mawt.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'You know this one',
      body: 'مَوْت (Mawt) means "Death." You know this as "maut" in Urdu. The Qur\'an reminds us: every soul will taste death.',
      quickCheckQuestion: 'What does مَوْت (Mawt) mean?',
      quickCheckOptions: ['Death', 'Life', 'Time', 'Return'],
      quickCheckAnswer: 0,
    },
  },
  {
    orderIndex: 47,
    arabic: 'صِرَاط',
    transliteration: 'Sirat',
    meaning: 'Straight Path',
    frequency: 45,
    isUrduCognate: true,
    urduCognateNote: '"Sirat-e-mustaqeem" — the straight path from Al-Fatiha',
    audioUrl: '/audio/words/sirat.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this 17 times a day!',
      body: 'صِرَاط (Sirat) means "Path." You say "Ihdinas-sirat-al-mustaqeem" (Guide us to the straight path) in every rak\'ah of every prayer. If you pray all 5 prayers, you say this word at least 17 times a day.',
    },
  },
  {
    orderIndex: 48,
    arabic: 'يَوْم',
    transliteration: 'Yawm',
    meaning: 'Day',
    frequency: 325,
    isUrduCognate: false,
    urduCognateNote: 'Not a direct cognate, but "Yawm al-Qiyamah" is known',
    audioUrl: '/audio/words/yawm.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'In your Al-Fatiha',
      body: 'يَوْم (Yawm) means "Day." You know it from "Yawm al-Qiyamah" (Day of Judgment) and from Al-Fatiha: "Maliki Yawm id-Deen" (Master of the Day of Judgment).',
      ayahText: 'مَالِكِ يَوْمِ الدِّينِ',
      ayahRef: 'Al-Fatiha 1:4',
    },
  },
  {
    orderIndex: 49,
    arabic: 'أَمْر',
    transliteration: 'Amr',
    meaning: 'Command, Matter',
    frequency: 166,
    isUrduCognate: true,
    urduCognateNote: '"Amr" in Urdu can mean command or matter',
    audioUrl: '/audio/words/amr.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'One word, big meaning',
      body: 'أَمْر (Amr) means "Command" or "Matter/Affair." When Allah decides something, He says "kun" (be) — and that is His amr.',
      factStat: '"Amr" appears 166 times. It can mean Allah\'s command, a matter/affair, or an order. Context determines the meaning — this is how Arabic works: one word, many shades.',
    },
  },
  {
    orderIndex: 50,
    arabic: 'سَبِيل',
    transliteration: 'Sabeel',
    meaning: 'Path, Way',
    frequency: 176,
    isUrduCognate: true,
    urduCognateNote: '"Fi sabeel illah" — in the path of Allah',
    audioUrl: '/audio/words/sabeel.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A phrase you know by heart',
      body: 'سَبِيل (Sabeel) means "Path" or "Way" — your 50th word! You know the phrase "fi sabeel illah" (in the path of Allah). The Qur\'an constantly talks about the "sabeel of Allah" — and your path to understanding continues.',
    },
  },
];
