import { IntroductionStyle } from '@prisma/client';
import { WordSeedData } from './words-types';

export const WORDS_L41_L60: WordSeedData[] = [
  // ── Lesson 41: "Divine Actions" ──
  {
    orderIndex: 201,
    arabic: 'أَوْحَى',
    transliteration: 'Awha',
    meaning: 'to reveal, inspire',
    frequency: 72,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/awha.mp3',
    lessonOrderIndex: 41,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Every prophet received this',
      body: 'أَوْحَى (Awha) means "to reveal" or "to inspire." In Urdu, "wahi" (divine revelation) comes from this exact root. Every time you hear about how the Qur\'an was sent down, this is the word at work.',
    },
  },
  {
    orderIndex: 202,
    arabic: 'أَخْرَجَ',
    transliteration: 'Akhraja',
    meaning: 'to bring forth, expel',
    frequency: 99,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/akhraja.mp3',
    lessonOrderIndex: 41,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'From darkness into light',
      body: 'أَخْرَجَ (Akhraja) means "to bring forth" or "to expel." Allah uses this word to describe bringing people from darkness into light, and bringing produce from the earth.',
      ayahText: 'وَأَوْحَيْنَا إِلَىٰ مُوسَىٰ أَنْ أَلْقِ عَصَاكَ',
      ayahRef: 'Al-A\'raf 7:117',
    },
  },
  {
    orderIndex: 203,
    arabic: 'أَهْلَكَ',
    transliteration: 'Ahlaka',
    meaning: 'to destroy',
    frequency: 51,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ahlaka.mp3',
    lessonOrderIndex: 41,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Destruction has a pattern',
      body: 'أَهْلَكَ (Ahlaka) means "to destroy." In Urdu, "halaak" comes from this root. In the Qur\'an, this word appears most often when Allah describes what happened to nations that rejected their prophets.',
      factStat: 'The Qur\'an mentions the destruction of over 10 ancient civilizations — Ad, Thamud, the people of Lut, Fir\'awn — all using forms of this root.',
    },
  },
  {
    orderIndex: 204,
    arabic: 'أَحْيَا',
    transliteration: 'Ahya',
    meaning: 'to give life',
    frequency: 51,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ahya.mp3',
    lessonOrderIndex: 41,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The opposite of death, from your Lesson 3 root',
      body: 'أَحْيَا (Ahya) means "to give life." Remember حَيَاة (Hayat/life) from Lesson 3? Same root! Allah is Al-Muhyi — the One who gives life. Every spring when rain brings dead land back to life, the Qur\'an calls that أَحْيَا.',
    },
  },
  {
    orderIndex: 205,
    arabic: 'أَمَرَ',
    transliteration: 'Amara',
    meaning: 'to command',
    frequency: 77,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/amara.mp3',
    lessonOrderIndex: 41,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Think "amr" in Urdu',
      body: 'أَمَرَ (Amara) — you know "amr" (command) from Urdu. "Amr bil ma\'roof" means commanding good.',
      quickCheckQuestion: 'What does أَمَرَ (Amara) mean?',
      quickCheckOptions: ['to command', 'to create', 'to forgive', 'to worship'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 42: "Life and Death" ──
  {
    orderIndex: 206,
    arabic: 'مَاتَ',
    transliteration: 'Mata',
    meaning: 'to die',
    frequency: 39,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/mata.mp3',
    lessonOrderIndex: 42,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The Urdu word "maut" starts here',
      body: 'مَاتَ (Mata) means "to die." In Urdu, "maut" (death) comes from this root. The Qur\'an reminds us that every soul shall taste death — it\'s not a punishment, but a return to Allah.',
    },
  },
  {
    orderIndex: 207,
    arabic: 'بَعَثَ',
    transliteration: 'Ba\'atha',
    meaning: 'to raise, resurrect',
    frequency: 52,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/baatha.mp3',
    lessonOrderIndex: 42,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The promise after death',
      body: 'بَعَثَ (Ba\'atha) means "to raise" or "to resurrect." After مَاتَ (death) comes بَعَثَ (resurrection). Allah uses this word for both sending prophets and raising the dead on the Day of Judgment.',
      ayahText: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ',
      ayahRef: 'Aal-e-Imran 3:185',
    },
  },
  {
    orderIndex: 208,
    arabic: 'حَيّ',
    transliteration: 'Hayy',
    meaning: 'Living, Alive',
    frequency: 23,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hayy.mp3',
    lessonOrderIndex: 42,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'An attribute only Allah truly owns',
      body: 'حَيّ (Hayy) means "Living" or "Alive." Al-Hayy (The Ever-Living) is one of Allah\'s names — the only being whose life has no beginning and no end.',
      factStat: 'Al-Hayy appears alongside Al-Qayyum (The Self-Sustaining) in Ayat al-Kursi, the most powerful ayah in the Qur\'an. Together they mean: He lives and sustains everything.',
    },
  },
  {
    orderIndex: 209,
    arabic: 'أَجَل',
    transliteration: 'Ajal',
    meaning: 'Term, Appointed time',
    frequency: 52,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ajal.mp3',
    lessonOrderIndex: 42,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your time is already written',
      body: 'أَجَل (Ajal) means "appointed time" or "term." In Urdu, you say "ajal aa gayi" when someone\'s time comes. The Qur\'an teaches that every person and every nation has an ajal — a fixed term that cannot be advanced or delayed.',
    },
  },
  {
    orderIndex: 210,
    arabic: 'سَاعَة',
    transliteration: 'Sa\'ah',
    meaning: 'Hour (of Judgment)',
    frequency: 47,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/saah.mp3',
    lessonOrderIndex: 42,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Not just any hour',
      body: 'سَاعَة (Sa\'ah) means "hour," but in the Qur\'an it almost always refers to THE Hour — the Day of Judgment. "As-Sa\'ah" is one of its most common names.',
      quickCheckQuestion: 'In the Qur\'an, "As-Sa\'ah" usually refers to what?',
      quickCheckOptions: ['The Day of Judgment', 'Prayer time', 'Sunrise', 'Midnight'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 43: "Judgment and Decree" ──
  {
    orderIndex: 211,
    arabic: 'قَضَى',
    transliteration: 'Qada',
    meaning: 'to decree, judge',
    frequency: 59,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qada.mp3',
    lessonOrderIndex: 43,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Qazi comes from this root',
      body: 'قَضَى (Qada) means "to decree" or "to judge." The Urdu word "qazi" (judge) and "qaza namaz" (make-up prayer) both come from this root.',
      factStat: 'In Islamic theology, "qada and qadr" (decree and destiny) are two of the six articles of faith. Both come from roots about Allah\'s judgment and measurement.',
    },
  },
  {
    orderIndex: 212,
    arabic: 'حَكَمَ',
    transliteration: 'Hakama',
    meaning: 'to judge',
    frequency: 45,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hakama.mp3',
    lessonOrderIndex: 43,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'From Hakeem to Hukm — same root',
      body: 'حَكَمَ (Hakama) means "to judge." Remember حَكِيم (Hakeem/Wise) from Lesson 29 and حُكْم (Hukm/judgment) from Lesson 30? This is the verb they all come from. In Urdu, "haakim" (ruler) is from the same family.',
    },
  },
  {
    orderIndex: 213,
    arabic: 'ظَنَّ',
    transliteration: 'Zanna',
    meaning: 'to think, assume',
    frequency: 47,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/zanna.mp3',
    lessonOrderIndex: 43,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'A warning about assumptions',
      body: 'ظَنَّ (Zanna) means "to think" or "to assume." The Qur\'an warns against basing your beliefs on ظَنّ (assumptions) instead of عِلْم (knowledge).',
      ayahText: 'إِنَّ الظَّنَّ لَا يُغْنِي مِنَ الْحَقِّ شَيْئًا',
      ayahRef: 'Yunus 10:36',
    },
  },
  {
    orderIndex: 214,
    arabic: 'شَهِدَ',
    transliteration: 'Shahida',
    meaning: 'to testify',
    frequency: 44,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shahida.mp3',
    lessonOrderIndex: 43,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your Shahada is built on this',
      body: 'شَهِدَ (Shahida) means "to testify" or "to bear witness." The Shahada — your declaration of faith — literally means "testimony." Every time you say "Ashhadu an la ilaha illallah," you are performing شَهِدَ.',
    },
  },
  {
    orderIndex: 215,
    arabic: 'عَاقِبَة',
    transliteration: 'Aqibah',
    meaning: 'Consequence, End',
    frequency: 32,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aqibah.mp3',
    lessonOrderIndex: 43,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'What happens in the end',
      body: 'عَاقِبَة (Aqibah) — in Urdu, "anjaam" and "aaqibat" are used similarly. The Qur\'an repeatedly asks: "Have you not seen the عَاقِبَة of those before you?"',
      quickCheckQuestion: 'What does عَاقِبَة (Aqibah) mean?',
      quickCheckOptions: ['Consequence / End', 'Beginning', 'Patience', 'Wisdom'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 44: "Teaching and Writing" ──
  {
    orderIndex: 216,
    arabic: 'كَتَبَ',
    transliteration: 'Kataba',
    meaning: 'to write, prescribe',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kataba.mp3',
    lessonOrderIndex: 44,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Kitab came from here',
      body: 'كَتَبَ (Kataba) means "to write" or "to prescribe." Remember كِتَاب (Kitab/Book) from Lesson 2? This is the verb it comes from. In Urdu, "kitaab likhna" is literally "writing a book" — both words from the same Arabic root.',
    },
  },
  {
    orderIndex: 217,
    arabic: 'عَلَّمَ',
    transliteration: 'Allama',
    meaning: 'to teach',
    frequency: 41,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/allama.mp3',
    lessonOrderIndex: 44,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'From knowing to teaching — one letter changes everything',
      body: 'عَلَّمَ (Allama) means "to teach." It\'s the intensive form of عَلِمَ (to know) from Lesson 4. Adding the doubling (shaddah) transforms "to know" into "to MAKE someone know."',
      factStat: 'In Surah Ar-Rahman, the very first thing Allah mentions is teaching: عَلَّمَ الْقُرْآنَ (He taught the Qur\'an). Teaching comes even before creating humans!',
    },
  },
  {
    orderIndex: 218,
    arabic: 'تَلَا',
    transliteration: 'Tala',
    meaning: 'to recite',
    frequency: 61,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/tala.mp3',
    lessonOrderIndex: 44,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The art of recitation',
      body: 'تَلَا (Tala) means "to recite." In Urdu, "tilawat" (Qur\'an recitation) comes from this root. This word carries a sense of following — when you recite, you are following Allah\'s words.',
      ayahText: 'عَلَّمَ الْإِنسَانَ مَا لَمْ يَعْلَمْ',
      ayahRef: 'Al-Alaq 96:5',
    },
  },
  {
    orderIndex: 219,
    arabic: 'نَظَرَ',
    transliteration: 'Nazara',
    meaning: 'to look, see',
    frequency: 87,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nazara.mp3',
    lessonOrderIndex: 44,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Not just seeing — truly looking',
      body: 'نَظَرَ (Nazara) means "to look" or "to reflect." In Urdu, "nazar" (sight) comes from this root. The Qur\'an constantly asks people to look at creation and think — "Afala yanzurun?" (Do they not look?). It\'s not passive seeing; it\'s active reflection.',
    },
  },
  {
    orderIndex: 220,
    arabic: 'ضَرَبَ',
    transliteration: 'Daraba',
    meaning: 'to strike, set forth',
    frequency: 55,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/daraba.mp3',
    lessonOrderIndex: 44,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'This word has a surprising Qur\'anic meaning',
      body: 'ضَرَبَ (Daraba) means "to strike," but in the Qur\'an its most common use is "daraba mathalan" — to set forth a parable or example.',
      quickCheckQuestion: 'What does "daraba mathalan" mean in the Qur\'an?',
      quickCheckOptions: ['to set forth a parable', 'to strike someone', 'to travel far', 'to build a house'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 45: "Struggle and Patience" ──
  {
    orderIndex: 221,
    arabic: 'قَتَلَ',
    transliteration: 'Qatala',
    meaning: 'to kill',
    frequency: 83,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qatala.mp3',
    lessonOrderIndex: 45,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'One of the first crimes in human history',
      body: 'قَتَلَ (Qatala) means "to kill." The Qur\'an uses this word when telling the story of Qabil and Habil (Cain and Abel) — the first murder in human history.',
      factStat: 'The Qur\'an declares: "Whoever kills a soul... it is as if he has killed all of mankind" (Al-Ma\'idah 5:32). This one word carries the weight of all humanity.',
    },
  },
  {
    orderIndex: 222,
    arabic: 'قَاتَلَ',
    transliteration: 'Qatala III',
    meaning: 'to fight',
    frequency: 54,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qatala-iii.mp3',
    lessonOrderIndex: 45,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Same root, different form — mutual action',
      body: 'قَاتَلَ (Qatala Form III) means "to fight." Notice the added alif after the first letter? That\'s Form III in Arabic — it turns a solo action into a mutual one. قَتَلَ = to kill (one person does it), قَاتَلَ = to fight (both sides engaged). You know "muqatala" (fighting) in Urdu.',
    },
  },
  {
    orderIndex: 223,
    arabic: 'صَبَرَ',
    transliteration: 'Sabara',
    meaning: 'to be patient',
    frequency: 58,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sabara.mp3',
    lessonOrderIndex: 45,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The verb behind your favorite virtue',
      body: 'صَبَرَ (Sabara) means "to be patient." Remember صَبْر (Sabr/patience) from Lesson 1? This is the verb form. When life gets hard, your elders say "sabr karo" — that\'s this word. The Qur\'an promises that Allah is with those who are patient.',
    },
  },
  {
    orderIndex: 224,
    arabic: 'شَكَرَ',
    transliteration: 'Shakara',
    meaning: 'to be grateful',
    frequency: 46,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shakara.mp3',
    lessonOrderIndex: 45,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Sabr and Shukr — the Qur\'an\'s power pair',
      body: 'شَكَرَ (Shakara) means "to be grateful." In Urdu, "shukriya" and "shukr" come from this root. The Qur\'an pairs patience (sabr) and gratitude (shukr) as the two responses a believer should have to every situation.',
      ayahText: 'إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِّكُلِّ صَبَّارٍ شَكُورٍ',
      ayahRef: 'Ibrahim 14:5',
    },
  },
  {
    orderIndex: 225,
    arabic: 'سَجَدَ',
    transliteration: 'Sajada',
    meaning: 'to prostrate',
    frequency: 35,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sajada.mp3',
    lessonOrderIndex: 45,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'You do this multiple times a day',
      body: 'سَجَدَ (Sajada) — "sajdah" in Urdu comes from this word. You perform sujood in every rakat of every prayer.',
      quickCheckQuestion: 'What does سَجَدَ (Sajada) mean?',
      quickCheckOptions: ['to prostrate', 'to stand', 'to bow', 'to sit'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 46: "Praise and Peace" ──
  {
    orderIndex: 226,
    arabic: 'سُبْحَان',
    transliteration: 'Subhan',
    meaning: 'Glory be',
    frequency: 41,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/subhan.mp3',
    lessonOrderIndex: 46,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this in every sujood',
      body: 'سُبْحَان (Subhan) means "Glory be" — declaring Allah is free from any imperfection. Every time you go into sujood, you say "Subhana Rabbiyal A\'la" (Glory be to my Lord, the Most High). This word is on your lips every single prayer.',
    },
  },
  {
    orderIndex: 227,
    arabic: 'حَمْد',
    transliteration: 'Hamd',
    meaning: 'Praise',
    frequency: 43,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hamd.mp3',
    lessonOrderIndex: 46,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Al-Fatiha opens with this word',
      body: 'حَمْد (Hamd) means "Praise." You say "Alhamdulillah" (All praise is for Allah) countless times daily. In Urdu, "hamd" means a poem praising Allah. The name Muhammad and Ahmad both come from this same root — "the praised one."',
    },
  },
  {
    orderIndex: 228,
    arabic: 'سَلَام',
    transliteration: 'Salam',
    meaning: 'Peace',
    frequency: 41,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/salam.mp3',
    lessonOrderIndex: 46,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The greeting of Jannah',
      body: 'سَلَام (Salam) means "Peace." You greet everyone with "Assalamu Alaikum" — peace be upon you. As-Salam is also one of Allah\'s 99 names.',
      factStat: 'In Jannah, the greeting of its inhabitants will be "Salam" (peace). The angels will greet the believers saying: "Salamun Alaikum — enter Paradise for what you used to do."',
    },
  },
  {
    orderIndex: 229,
    arabic: 'تَقْوَى',
    transliteration: 'Taqwa',
    meaning: 'God-consciousness',
    frequency: 17,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/taqwa.mp3',
    lessonOrderIndex: 46,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The ultimate spiritual goal',
      body: 'تَقْوَى (Taqwa) means "God-consciousness" — being aware of Allah in every action. Remember اتَّقَى (Ittaqa/to fear Allah) from Lesson 6? Taqwa is the noun form. The Qur\'an calls it the best provision for the journey of life.',
      ayahText: 'وَتَزَوَّدُوا فَإِنَّ خَيْرَ الزَّادِ التَّقْوَىٰ',
      ayahRef: 'Al-Baqarah 2:197',
    },
  },
  {
    orderIndex: 230,
    arabic: 'تَوْبَة',
    transliteration: 'Tawbah',
    meaning: 'Repentance',
    frequency: 17,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/tawbah.mp3',
    lessonOrderIndex: 46,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'An entire surah is named after this',
      body: 'تَوْبَة (Tawbah) means "Repentance" — turning back to Allah. Surah At-Tawbah is the 9th surah of the Qur\'an. In Urdu, "tauba karna" means to repent.',
      quickCheckQuestion: 'What does تَوْبَة (Tawbah) mean?',
      quickCheckOptions: ['Repentance', 'Punishment', 'Reward', 'Fasting'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 47: "More Divine Attributes" ──
  {
    orderIndex: 231,
    arabic: 'عَزِيز',
    transliteration: 'Aziz',
    meaning: 'Mighty, Powerful',
    frequency: 63,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aziz.mp3',
    lessonOrderIndex: 47,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A name Pakistanis know well',
      body: 'عَزِيز (Aziz) means "Mighty" or "Powerful." In Urdu, "aziz" also means "dear" or "beloved." As a name of Allah, Al-Aziz means the Almighty — the One whose power cannot be overcome. You hear it paired with Hakeem: "Azizun Hakeem" (Mighty, Wise).',
    },
  },
  {
    orderIndex: 232,
    arabic: 'كَرِيم',
    transliteration: 'Karim',
    meaning: 'Noble, Generous',
    frequency: 28,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/karim.mp3',
    lessonOrderIndex: 47,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Generosity as a divine quality',
      body: 'كَرِيم (Karim) means "Noble" or "Generous." Al-Karim is one of Allah\'s names, and you hear it in "Al-Qur\'an al-Karim" (the Noble Qur\'an). In Pakistani culture, calling someone "karim" is one of the highest compliments — it means they give without being asked.',
    },
  },
  {
    orderIndex: 233,
    arabic: 'قَدِير',
    transliteration: 'Qadir',
    meaning: 'Capable, Able',
    frequency: 44,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qadir.mp3',
    lessonOrderIndex: 47,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Power without limits',
      body: 'قَدِير (Qadir) means "Capable" or "All-Powerful." Al-Qadir is one of Allah\'s names. In Urdu, "qudrat" (power/nature) comes from this root.',
      factStat: 'The phrase "inna Allaha ala kulli shay\'in Qadir" (Indeed Allah is capable of all things) appears over 30 times in the Qur\'an — more than almost any other phrase.',
    },
  },
  {
    orderIndex: 234,
    arabic: 'أَلِيم',
    transliteration: 'Alim',
    meaning: 'Painful',
    frequency: 72,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/alim.mp3',
    lessonOrderIndex: 47,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The most common companion of "adhab"',
      body: 'أَلِيم (Alim) means "Painful." Remember عَذَاب (Adhab/punishment) from Lesson 5? The most frequent phrase in the Qur\'an combining them is "adhab alim" — a painful punishment.',
      ayahText: 'إِنَّ اللَّهَ عَزِيزٌ حَكِيمٌ',
      ayahRef: 'Al-Anfal 8:10',
    },
  },
  {
    orderIndex: 235,
    arabic: 'شَدِيد',
    transliteration: 'Shadid',
    meaning: 'Severe, Intense',
    frequency: 36,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shadid.mp3',
    lessonOrderIndex: 47,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Another qualifier for punishment',
      body: 'شَدِيد (Shadid) means "Severe" or "Intense." The Qur\'an uses "shadid al-iqab" (severe in punishment) and "shadid al-quwa" (intense in power).',
      quickCheckQuestion: 'What does شَدِيد (Shadid) mean?',
      quickCheckOptions: ['Severe / Intense', 'Gentle', 'Quick', 'Hidden'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 48: "Communities and Peoples" ──
  {
    orderIndex: 236,
    arabic: 'أُمَّة',
    transliteration: 'Ummah',
    meaning: 'Community, Nation',
    frequency: 64,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ummah.mp3',
    lessonOrderIndex: 48,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The Muslim Ummah — you use this every day',
      body: 'أُمَّة (Ummah) means "Community" or "Nation." This is identical to the Urdu word. When people say "the Muslim Ummah," they\'re using this Qur\'anic word. The Qur\'an calls this ummah "the best community raised for mankind."',
    },
  },
  {
    orderIndex: 237,
    arabic: 'عَالَمِين',
    transliteration: 'Alamin',
    meaning: 'Worlds, All peoples',
    frequency: 73,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/alamin.mp3',
    lessonOrderIndex: 48,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this in Al-Fatiha\'s very first ayah',
      body: 'عَالَمِين (Alamin) means "Worlds" or "All peoples." "Alhamdulillahi Rabbil Alamin" — you recite this in every rakat of every prayer. Allah is not Lord of just one nation; He is Lord of all worlds — humans, jinn, angels, and everything we cannot even perceive.',
    },
  },
  {
    orderIndex: 238,
    arabic: 'ذُرِّيَّة',
    transliteration: 'Dhurriyyah',
    meaning: 'Offspring, Progeny',
    frequency: 28,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dhurriyyah.mp3',
    lessonOrderIndex: 48,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The prophets\' beautiful dua for children',
      body: 'ذُرِّيَّة (Dhurriyyah) means "Offspring" or "Progeny." Many prophets in the Qur\'an made dua for righteous dhurriyyah — Ibrahim, Zakariya, and others.',
      ayahText: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ',
      ayahRef: 'Al-Furqan 25:74',
    },
  },
  {
    orderIndex: 239,
    arabic: 'مُبِين',
    transliteration: 'Mubin',
    meaning: 'Clear, Manifest',
    frequency: 72,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/mubin.mp3',
    lessonOrderIndex: 48,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s favorite adjective for itself',
      body: 'مُبِين (Mubin) means "Clear" or "Manifest." The Qur\'an calls itself "Al-Kitab al-Mubin" (The Clear Book) and describes Islam as "Al-Haqq al-Mubin" (The Clear Truth).',
      factStat: 'مُبِين appears 72 times in the Qur\'an — almost always describing something Allah wants to be absolutely clear: a clear book, a clear warner, a clear enemy (Shaytan), a clear victory.',
    },
  },
  {
    orderIndex: 240,
    arabic: 'قُرْآن',
    transliteration: 'Qur\'an',
    meaning: 'Quran, Recitation',
    frequency: 68,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/quran.mp3',
    lessonOrderIndex: 48,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The word you\'ve been studying all along',
      body: 'قُرْآن (Qur\'an) literally means "Recitation" — it comes from the root meaning "to recite." The first word revealed was "Iqra" (Recite!), and the Book itself is called "The Recitation."',
      quickCheckQuestion: 'What does the word "Qur\'an" literally mean?',
      quickCheckOptions: ['Recitation', 'Book', 'Revelation', 'Scripture'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 49: "Going Astray" ──
  {
    orderIndex: 241,
    arabic: 'ضَلَّ',
    transliteration: 'Dalla',
    meaning: 'to go astray',
    frequency: 53,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dalla.mp3',
    lessonOrderIndex: 49,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The opposite of هُدَى from Lesson 1',
      body: 'ضَلَّ (Dalla) means "to go astray." Remember هُدَى (Huda/guidance) — your 5th word ever? ضَلَّ is its opposite. The Qur\'an is built on this contrast: guidance vs. misguidance.',
      factStat: 'In Al-Fatiha, you ask to be on the straight path — "not the path of those who went astray (dallin)." You\'ve been saying this word in every prayer since you were a child.',
    },
  },
  {
    orderIndex: 242,
    arabic: 'ضَلَال',
    transliteration: 'Dalal',
    meaning: 'Misguidance, Error',
    frequency: 38,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dalal.mp3',
    lessonOrderIndex: 49,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'From "gumrah" in Urdu to Dalal in Arabic',
      body: 'ضَلَال (Dalal) means "Misguidance" or "Error." This is the noun form of ضَلَّ. In Urdu, "dalalat" is used in the same way. The Qur\'an contrasts هُدَى (guidance) with ضَلَال (misguidance) as the two paths humans can take.',
    },
  },
  {
    orderIndex: 243,
    arabic: 'أَشْرَكَ',
    transliteration: 'Ashraka',
    meaning: 'to associate partners',
    frequency: 71,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ashraka.mp3',
    lessonOrderIndex: 49,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The one sin Allah won\'t forgive',
      body: 'أَشْرَكَ (Ashraka) means "to associate partners" with Allah. "Shirk" in Urdu comes from this root. The Qur\'an calls it the greatest sin — the one thing Allah will not forgive if a person dies upon it.',
      ayahText: 'إِنَّ اللَّهَ لَا يَغْفِرُ أَن يُشْرَكَ بِهِ',
      ayahRef: 'An-Nisa 4:48',
    },
  },
  {
    orderIndex: 244,
    arabic: 'كُفْر',
    transliteration: 'Kufr',
    meaning: 'Disbelief',
    frequency: 37,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kufr.mp3',
    lessonOrderIndex: 49,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The noun behind a word you learned in Lesson 6',
      body: 'كُفْر (Kufr) means "Disbelief." Remember كَفَرَ (Kafara/to disbelieve) from Lesson 6? This is the noun form. The literal meaning is "covering" — covering the truth. In everyday Urdu, you hear "kufr" used often, but understanding its Qur\'anic root adds depth to your comprehension.',
    },
  },
  {
    orderIndex: 245,
    arabic: 'إِثْم',
    transliteration: 'Ithm',
    meaning: 'Sin, Crime',
    frequency: 35,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ithm.mp3',
    lessonOrderIndex: 49,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'A word for sinful acts',
      body: 'إِثْم (Ithm) means "Sin" or "Crime." The Qur\'an distinguishes between different types of wrongdoing — إِثْم is a deliberate sin, something done knowingly.',
      quickCheckQuestion: 'What does إِثْم (Ithm) mean?',
      quickCheckOptions: ['Sin / Crime', 'Reward', 'Blessing', 'Forgiveness'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 50: "The Unseen" ──
  {
    orderIndex: 246,
    arabic: 'غَيْب',
    transliteration: 'Ghayb',
    meaning: 'Unseen',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ghayb.mp3',
    lessonOrderIndex: 50,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Believing in what you cannot see',
      body: 'غَيْب (Ghayb) means "The Unseen." In Urdu, "ghayb" is used the same way — "ilm-ul-ghayb" (knowledge of the unseen). In Surah Al-Baqarah, the very first quality of the righteous is that they "believe in the ghayb."',
    },
  },
  {
    orderIndex: 247,
    arabic: 'ذَنْب',
    transliteration: 'Dhanb',
    meaning: 'Sin, Fault',
    frequency: 37,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dhanb.mp3',
    lessonOrderIndex: 50,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The word prophets used when asking forgiveness',
      body: 'ذَنْب (Dhanb) means "Sin" or "Fault." This is the word Musa (AS) and other prophets used when they asked Allah for forgiveness — "Rabbighfir li dhanbi."',
      ayahText: 'رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا',
      ayahRef: 'Aal-e-Imran 3:147',
    },
  },
  {
    orderIndex: 248,
    arabic: 'سُوء',
    transliteration: 'Su\'',
    meaning: 'Evil, Harm',
    frequency: 50,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/su.mp3',
    lessonOrderIndex: 50,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Hidden in a surah you may have memorized',
      body: 'سُوء (Su\') means "Evil" or "Harm." If you\'ve memorized Surah Al-Falaq, you say "min sharri ma khalaq" — seeking refuge from the evil of what He created.',
      factStat: 'The Qur\'an uses three different words for wrongdoing: سُوء (harm/evil), إِثْم (deliberate sin), and ذَنْب (fault). Each has a distinct shade of meaning — Arabic is incredibly precise about moral vocabulary.',
    },
  },
  {
    orderIndex: 249,
    arabic: 'ظُلْم',
    transliteration: 'Zulm',
    meaning: 'Injustice, Oppression',
    frequency: 20,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/zulm.mp3',
    lessonOrderIndex: 50,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Full circle from Lesson 7',
      body: 'ظُلْم (Zulm) means "Injustice" or "Oppression." Remember ظَالِم (Zalim/oppressor) from Lesson 7 and ظَلَمَ (Zalama/to oppress) from Lesson 9? This is the noun — the concept itself. In Urdu, "zulm" is one of the most emotionally charged words. The Qur\'an promises that Allah will never do zulm to anyone.',
    },
  },
  {
    orderIndex: 250,
    arabic: 'دُعَاء',
    transliteration: 'Du\'a\'',
    meaning: 'Supplication',
    frequency: 22,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dua.mp3',
    lessonOrderIndex: 50,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Your most personal connection with Allah',
      body: 'دُعَاء (Du\'a\') means "Supplication" — calling upon Allah. In Urdu, "dua karna" is something you do every single day. The Prophet ﷺ called dua "the essence of worship."',
      quickCheckQuestion: 'What does دُعَاء (Du\'a\') mean?',
      quickCheckOptions: ['Supplication / Calling upon Allah', 'Fasting', 'Charity', 'Pilgrimage'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 51: "More Actions" ──
  {
    orderIndex: 251,
    arabic: 'خَشِيَ',
    transliteration: 'Khashiya',
    meaning: 'to fear reverentially',
    frequency: 40,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/khashiya.mp3',
    lessonOrderIndex: 51,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A deeper kind of fear',
      body: 'خَشِيَ (Khashiya) means "to fear reverentially." In Urdu, "khashiyat" means a respectful awe. This is not the fear of danger — it\'s the fear that comes from truly knowing Allah\'s greatness. The Qur\'an says only scholars truly have this خَشِيَة of Allah.',
    },
  },
  {
    orderIndex: 252,
    arabic: 'تَرَكَ',
    transliteration: 'Taraka',
    meaning: 'to leave, abandon',
    frequency: 40,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/taraka.mp3',
    lessonOrderIndex: 51,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'What people leave behind',
      body: 'تَرَكَ (Taraka) means "to leave" or "to abandon." In Urdu, "tark karna" (to abandon) uses this root. The Qur\'an uses this word for leaving behind inheritance, abandoning falsehood, and forsaking Allah\'s path.',
      ayahText: 'وَتَرَكْنَا عَلَيْهِ فِي الْآخِرِينَ',
      ayahRef: 'As-Saffat 37:78',
    },
  },
  {
    orderIndex: 253,
    arabic: 'بَلَغَ',
    transliteration: 'Balagha',
    meaning: 'to reach',
    frequency: 40,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/balagha.mp3',
    lessonOrderIndex: 51,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Where "balaghat" (eloquence) comes from',
      body: 'بَلَغَ (Balagha) means "to reach." In Urdu, "baligh" means mature (reached adulthood). And "balaghat" (eloquence) literally means speech that reaches people\'s hearts.',
      factStat: 'The Qur\'an uses بَلَغَ in powerful contexts: "When he reached the setting of the sun..." (Surah Al-Kahf, about Dhul-Qarnayn). It turns simple journeys into epic narratives.',
    },
  },
  {
    orderIndex: 254,
    arabic: 'حَرَّمَ',
    transliteration: 'Harrama',
    meaning: 'to forbid',
    frequency: 39,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/harrama.mp3',
    lessonOrderIndex: 51,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Halal and Haram — the daily choices',
      body: 'حَرَّمَ (Harrama) means "to forbid." In Urdu and daily life, you constantly hear "haram hai" (it\'s forbidden). The Qur\'an uses this word to set clear boundaries — what Allah has made halal vs. what He has made haram. Understanding this word helps you recognize those boundaries when you read.',
    },
  },
  {
    orderIndex: 255,
    arabic: 'تَوَلَّى',
    transliteration: 'Tawalla',
    meaning: 'to turn away',
    frequency: 78,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/tawalla.mp3',
    lessonOrderIndex: 51,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The opposite of answering the call',
      body: 'تَوَلَّى (Tawalla) means "to turn away." The Qur\'an uses this word to describe people who heard the truth but turned their backs on it.',
      quickCheckQuestion: 'What does تَوَلَّى (Tawalla) mean?',
      quickCheckOptions: ['to turn away', 'to come closer', 'to stand firm', 'to remember'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 52: "Establishing and Increasing" ──
  {
    orderIndex: 256,
    arabic: 'أَقَامَ',
    transliteration: 'Aqama',
    meaning: 'to establish',
    frequency: 54,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aqama.mp3',
    lessonOrderIndex: 52,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You hear this before every prayer',
      body: 'أَقَامَ (Aqama) means "to establish." The iqamah (call to begin prayer) comes from this root. And "aqimus-salah" (establish prayer) is one of the most repeated commands in the Qur\'an. It does not just mean "pray" — it means establish prayer as a consistent practice in your life.',
    },
  },
  {
    orderIndex: 257,
    arabic: 'رَدَّ',
    transliteration: 'Radda',
    meaning: 'to return, repel',
    frequency: 36,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/radda.mp3',
    lessonOrderIndex: 52,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'From "radd-e-amal" to Qur\'anic Arabic',
      body: 'رَدَّ (Radda) means "to return" or "to repel." In Urdu, "radd karna" means to reject or return. "Radd-e-amal" (reaction) literally means "returning an action." The Qur\'an uses it for repelling evil and returning to Allah.',
    },
  },
  {
    orderIndex: 258,
    arabic: 'زَادَ',
    transliteration: 'Zada',
    meaning: 'to increase',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/zada.mp3',
    lessonOrderIndex: 52,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Growth goes both ways in the Qur\'an',
      body: 'زَادَ (Zada) means "to increase." In Urdu, "ziyadah" (more/extra) comes from this root. The Qur\'an uses this word in both positive and negative ways.',
      factStat: 'The Qur\'an says the righteous increase in guidance, but the stubborn increase in misguidance. Same word, opposite outcomes — depending on which path you choose.',
    },
  },
  {
    orderIndex: 259,
    arabic: 'نَسِيَ',
    transliteration: 'Nasiya',
    meaning: 'to forget',
    frequency: 35,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nasiya.mp3',
    lessonOrderIndex: 52,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Why humans are called "insan"',
      body: 'نَسِيَ (Nasiya) means "to forget." Some scholars say the word "insan" (human) comes from this root — because humans are forgetful by nature. The Qur\'an warns against forgetting Allah\'s signs.',
      ayahText: 'نَسُوا اللَّهَ فَنَسِيَهُمْ',
      ayahRef: 'At-Tawbah 9:67',
    },
  },
  {
    orderIndex: 260,
    arabic: 'عَقَلَ',
    transliteration: 'Aqala',
    meaning: 'to reason, understand',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aqala.mp3',
    lessonOrderIndex: 52,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The Qur\'an\'s constant challenge to think',
      body: 'عَقَلَ (Aqala) means "to reason" or "to understand." In Urdu, "aql" (intellect) comes from this root. The Qur\'an repeatedly asks: "Afala ta\'qiloon?" — "Will you not reason?"',
      quickCheckQuestion: 'What does "Afala ta\'qiloon" mean?',
      quickCheckOptions: ['Will you not reason?', 'Will you not pray?', 'Will you not fast?', 'Will you not give?'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 53: "Nature" ──
  {
    orderIndex: 261,
    arabic: 'بَحْر',
    transliteration: 'Bahr',
    meaning: 'Sea',
    frequency: 41,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/bahr.mp3',
    lessonOrderIndex: 53,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Poetry and the sea share a name',
      body: 'بَحْر (Bahr) means "Sea." In Urdu, "bahr" is also used for the meter of poetry — because both are vast and deep. The Qur\'an uses the sea as a sign of Allah\'s power, describing ships sailing through it by His permission.',
    },
  },
  {
    orderIndex: 262,
    arabic: 'نَهْر',
    transliteration: 'Nahr',
    meaning: 'River',
    frequency: 54,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nahr.mp3',
    lessonOrderIndex: 53,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Rivers flowing beneath Paradise',
      body: 'نَهْر (Nahr) means "River." One of the most repeated descriptions of Jannah in the Qur\'an mentions rivers — rivers of water, milk, honey, and wine.',
      ayahText: 'تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ',
      ayahRef: 'Al-Baqarah 2:25',
    },
  },
  {
    orderIndex: 263,
    arabic: 'رِيح',
    transliteration: 'Rih',
    meaning: 'Wind',
    frequency: 29,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rih.mp3',
    lessonOrderIndex: 53,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Wind as both mercy and punishment',
      body: 'رِيح (Rih) means "Wind." The Qur\'an uses wind in two powerful ways — as a carrier of rain (mercy) and as a destroyer of nations (punishment).',
      factStat: 'When wind brings mercy, the Qur\'an often uses the plural "riyah" (winds). When it brings destruction, it uses the singular "rih" (wind). Even grammar carries meaning in the Qur\'an.',
    },
  },
  {
    orderIndex: 264,
    arabic: 'جَبَل',
    transliteration: 'Jabal',
    meaning: 'Mountain',
    frequency: 39,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/jabal.mp3',
    lessonOrderIndex: 53,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Mountains as pegs holding the earth',
      body: 'جَبَل (Jabal) means "Mountain." If you\'ve been to the northern areas of Pakistan — Hunza, Gilgit, Nanga Parbat — you\'ve stood before جِبَال. The Qur\'an describes mountains as "pegs" (awtad) that stabilize the earth, something modern geology confirms.',
    },
  },
  {
    orderIndex: 265,
    arabic: 'شَجَرَة',
    transliteration: 'Shajarah',
    meaning: 'Tree',
    frequency: 26,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shajarah.mp3',
    lessonOrderIndex: 53,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'A tree that changed human history',
      body: 'شَجَرَة (Shajarah) means "Tree." In Urdu, "shajar" means trees. The Qur\'an mentions the forbidden tree in Jannah that Adam (AS) was told not to approach.',
      quickCheckQuestion: 'What does شَجَرَة (Shajarah) mean?',
      quickCheckOptions: ['Tree', 'Flower', 'River', 'Mountain'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 54: "People Types" ──
  {
    orderIndex: 266,
    arabic: 'مِسْكِين',
    transliteration: 'Miskin',
    meaning: 'Poor, Needy',
    frequency: 22,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/miskin.mp3',
    lessonOrderIndex: 54,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A word Urdu speakers use with compassion',
      body: 'مِسْكِين (Miskin) means "Poor" or "Needy." In Urdu, "miskin" describes someone humble and needy. The Qur\'an repeatedly commands feeding the مِسْكِين and treating them with kindness — it\'s not just charity, it\'s a test of your faith.',
    },
  },
  {
    orderIndex: 267,
    arabic: 'فَاسِق',
    transliteration: 'Fasiq',
    meaning: 'Transgressor',
    frequency: 24,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/fasiq.mp3',
    lessonOrderIndex: 54,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'When someone crosses the line',
      body: 'فَاسِق (Fasiq) means "Transgressor" — someone who deliberately crosses Allah\'s limits. In Urdu, "fasiq" carries the same meaning. The Qur\'an uses this word to describe those who know the truth but choose to violate it anyway.',
      ayahText: 'وَمَا يُضِلُّ بِهِ إِلَّا الْفَاسِقِينَ',
      ayahRef: 'Al-Baqarah 2:26',
    },
  },
  {
    orderIndex: 268,
    arabic: 'غَنِيّ',
    transliteration: 'Ghani',
    meaning: 'Self-Sufficient, Rich',
    frequency: 20,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ghani.mp3',
    lessonOrderIndex: 54,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Allah is Al-Ghani — He needs nothing',
      body: 'غَنِيّ (Ghani) means "Self-Sufficient" or "Rich." Al-Ghani is one of Allah\'s names — He is free of any need from creation.',
      factStat: 'The Qur\'an flips our understanding: true richness is not wealth. Allah says He is Al-Ghani (Self-Sufficient) and we are the fuqara (needy ones). Spiritual poverty before Allah is actually the highest state.',
    },
  },
  {
    orderIndex: 269,
    arabic: 'رَجُل',
    transliteration: 'Rajul',
    meaning: 'Man',
    frequency: 29,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rajul.mp3',
    lessonOrderIndex: 54,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The Qur\'an\'s word for individual men of faith',
      body: 'رَجُل (Rajul) means "Man." The Qur\'an often highlights individual righteous men — like the believing man from Fir\'awn\'s family who stood up alone for truth. When the Qur\'an says "rajul," it\'s often spotlighting courage and individual conviction.',
    },
  },
  {
    orderIndex: 270,
    arabic: 'قَرْيَة',
    transliteration: 'Qaryah',
    meaning: 'Town, Village',
    frequency: 57,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qaryah.mp3',
    lessonOrderIndex: 54,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Ancient towns with lessons for today',
      body: 'قَرْيَة (Qaryah) means "Town" or "Village." The Qur\'an tells stories of entire towns that were destroyed for their disobedience — each one a warning.',
      quickCheckQuestion: 'What does قَرْيَة (Qaryah) mean?',
      quickCheckOptions: ['Town / Village', 'Mountain', 'Desert', 'Palace'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 55: "Punishment and Glorification" ──
  {
    orderIndex: 271,
    arabic: 'عَذَّبَ',
    transliteration: 'Adhdhaba',
    meaning: 'to punish',
    frequency: 41,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/adhdhaba.mp3',
    lessonOrderIndex: 55,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The verb behind "azaab"',
      body: 'عَذَّبَ (Adhdhaba) means "to punish." Remember عَذَاب (Adhab/punishment) from Lesson 5? This is the verb it comes from. In Urdu, "azaab dena" uses this same root. The doubled middle letter (shaddah) makes it intensive — severe punishment.',
    },
  },
  {
    orderIndex: 272,
    arabic: 'سَبَّحَ',
    transliteration: 'Sabbaha',
    meaning: 'to glorify',
    frequency: 42,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sabbaha.mp3',
    lessonOrderIndex: 55,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your tasbeeh after every prayer',
      body: 'سَبَّحَ (Sabbaha) means "to glorify." After every prayer, you say "SubhanAllah" 33 times — that\'s this root. "Tasbeeh" (the prayer beads and the act) comes from سَبَّحَ. The Qur\'an says everything in the heavens and earth glorifies Allah.',
    },
  },
  {
    orderIndex: 273,
    arabic: 'أَكَلَ',
    transliteration: 'Akala',
    meaning: 'to eat, consume',
    frequency: 93,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/akala.mp3',
    lessonOrderIndex: 55,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Eating appears 93 times in the Qur\'an',
      body: 'أَكَلَ (Akala) means "to eat" or "to consume." The Qur\'an addresses food and eating extensively — what to eat, how to eat, and what not to consume.',
      factStat: 'Beyond literal eating, the Qur\'an uses أَكَلَ metaphorically: "eating" someone\'s wealth unjustly, or "eating" the property of orphans. It makes exploitation vivid and visceral.',
    },
  },
  {
    orderIndex: 274,
    arabic: 'مُتَّقِين',
    transliteration: 'Muttaqin',
    meaning: 'God-fearing ones',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/muttaqin.mp3',
    lessonOrderIndex: 55,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The people the Qur\'an was sent for',
      body: 'مُتَّقِين (Muttaqin) means "the God-fearing ones." Remember تَقْوَى (Taqwa) from Lesson 46 and اتَّقَى (Ittaqa) from Lesson 6? This is the plural describing people who live with taqwa. The Qur\'an declares itself "guidance for the Muttaqin."',
      ayahText: 'هُدًى لِّلْمُتَّقِينَ',
      ayahRef: 'Al-Baqarah 2:2',
    },
  },
  {
    orderIndex: 275,
    arabic: 'صَالِحَات',
    transliteration: 'Salihat',
    meaning: 'Righteous deeds',
    frequency: 62,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/salihat.mp3',
    lessonOrderIndex: 55,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Half of the Qur\'an\'s most famous phrase',
      body: 'صَالِحَات (Salihat) means "Righteous deeds." The phrase "alladhina aamanu wa amilus-salihat" (those who believe and do good deeds) is one of the most repeated in the entire Qur\'an.',
      quickCheckQuestion: 'In "aamanu wa amilus-salihat," what does salihat mean?',
      quickCheckOptions: ['Righteous deeds', 'Prayers', 'Fasting', 'Pilgrimage'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 56: "Position and Direction" ──
  {
    orderIndex: 276,
    arabic: 'فَوْقَ',
    transliteration: 'Fawqa',
    meaning: 'Above, Over',
    frequency: 25,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/fawqa.mp3',
    lessonOrderIndex: 56,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Even a mosquito appears "above" in the Qur\'an',
      body: 'فَوْقَ (Fawqa) means "Above" or "Over." The Qur\'an uses spatial language powerfully to describe hierarchy, status, and physical position.',
      factStat: 'In Al-Baqarah 2:26, Allah says He is not shy to set forth a parable of even a mosquito or "ma fawqaha" (what is above it/smaller). فَوْقَ here means "beyond" — showing the word\'s flexibility.',
    },
  },
  {
    orderIndex: 277,
    arabic: 'تَحْت',
    transliteration: 'Taht',
    meaning: 'Under, Beneath',
    frequency: 48,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/taht.mp3',
    lessonOrderIndex: 56,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Beneath the trees of Paradise',
      body: 'تَحْت (Taht) means "Under" or "Beneath." The most famous use is in the description of Paradise: gardens beneath which rivers flow.',
      ayahText: 'جَنَّاتٍ تَجْرِي مِن تَحْتِهَا الْأَنْهَارُ',
      ayahRef: 'Al-Baqarah 2:25',
    },
  },
  {
    orderIndex: 278,
    arabic: 'دُونَ',
    transliteration: 'Dun',
    meaning: 'Below, Besides',
    frequency: 135,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dun.mp3',
    lessonOrderIndex: 56,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A word that appears 135 times',
      body: 'دُونَ (Dun) means "Below," "Besides," or "Other than." In Urdu, "is ke dun" means "other than this." The Qur\'an\'s most important use is "min duni-llah" (besides Allah) — warning against worshipping anything other than Allah.',
    },
  },
  {
    orderIndex: 279,
    arabic: 'أَوَّل',
    transliteration: 'Awwal',
    meaning: 'First',
    frequency: 61,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/awwal.mp3',
    lessonOrderIndex: 56,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Al-Awwal — one of Allah\'s beautiful names',
      body: 'أَوَّل (Awwal) means "First." Al-Awwal is one of Allah\'s names — He is The First, before whom there was nothing. In Urdu, "awwal darjay ka" means "first class." The Qur\'an says the first house established for worship was in Makkah.',
    },
  },
  {
    orderIndex: 280,
    arabic: 'مَصِير',
    transliteration: 'Masir',
    meaning: 'Destination, Return',
    frequency: 28,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/masir.mp3',
    lessonOrderIndex: 56,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Where everything ends up',
      body: 'مَصِير (Masir) means "Destination" or "Final Return." The Qur\'an uses this word to remind us that everyone has a masir — a final destination. "Wa ilallahil-masir" — and to Allah is the final return.',
      quickCheckQuestion: 'What does مَصِير (Masir) mean?',
      quickCheckOptions: ['Destination / Final Return', 'Beginning', 'Journey', 'Speed'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 57: "Warnings and Truth" ──
  {
    orderIndex: 281,
    arabic: 'نَذِير',
    transliteration: 'Nadhir',
    meaning: 'Warner',
    frequency: 58,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nadhir.mp3',
    lessonOrderIndex: 57,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Every prophet\'s primary job title',
      body: 'نَذِير (Nadhir) means "Warner." In Urdu, "nazeer" is used for a warning example. Every prophet was sent as a نَذِير — someone who warns people about the consequences of their actions before it\'s too late.',
    },
  },
  {
    orderIndex: 282,
    arabic: 'خَوْف',
    transliteration: 'Khawf',
    meaning: 'Fear',
    frequency: 26,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/khawf.mp3',
    lessonOrderIndex: 57,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s promise to remove this',
      body: 'خَوْف (Khawf) means "Fear." In Urdu, "khauf" is used exactly the same way. But here\'s the beautiful part — the Qur\'an promises believers freedom from it.',
      factStat: 'The phrase "la khawfun alayhim wa la hum yahzanun" (no fear upon them, nor shall they grieve) appears 13 times in the Qur\'an — one of Allah\'s most repeated promises to the righteous.',
    },
  },
  {
    orderIndex: 283,
    arabic: 'كَذِب',
    transliteration: 'Kadhib',
    meaning: 'Lie, Falsehood',
    frequency: 33,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kadhib.mp3',
    lessonOrderIndex: 57,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'What deniers did to every prophet',
      body: 'كَذِب (Kadhib) means "Lie" or "Falsehood." In Urdu, "kazzab" (great liar) comes from this root. The Qur\'an uses "kadhdhaba" (to deny/call a liar) as one of its key verbs — every prophet was accused of lying.',
      ayahText: 'كَذَّبَتْ قَبْلَهُمْ قَوْمُ نُوحٍ وَعَادٌ وَفِرْعَوْنُ',
      ayahRef: 'Sad 38:12',
    },
  },
  {
    orderIndex: 284,
    arabic: 'بَاطِل',
    transliteration: 'Batil',
    meaning: 'Falsehood, Void',
    frequency: 26,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/batil.mp3',
    lessonOrderIndex: 57,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The opposite of Haqq from Lesson 2',
      body: 'بَاطِل (Batil) means "Falsehood" or "Void." Remember حَقّ (Haqq/Truth) from Lesson 2? بَاطِل is its opposite. In Urdu, "baatil" means invalid or false. The Qur\'an declares: "Truth has come and falsehood has vanished" — Haqq always defeats Batil.',
    },
  },
  {
    orderIndex: 285,
    arabic: 'حَسَنَة',
    transliteration: 'Hasanah',
    meaning: 'Good Deed',
    frequency: 25,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hasanah.mp3',
    lessonOrderIndex: 57,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'What wipes away bad deeds',
      body: 'حَسَنَة (Hasanah) means "Good Deed." In Urdu, "nek hasanat" means good deeds. The Qur\'an promises that good deeds erase bad ones.',
      quickCheckQuestion: 'What does حَسَنَة (Hasanah) mean?',
      quickCheckOptions: ['Good Deed', 'Bad Deed', 'Punishment', 'Trial'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 58: "More Particles" ──
  {
    orderIndex: 286,
    arabic: 'إِنْ',
    transliteration: 'In',
    meaning: 'If',
    frequency: 578,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/in.mp3',
    lessonOrderIndex: 58,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Two letters, 578 appearances',
      body: 'إِنْ (In) means "If." It\'s one of the smallest and most frequent words in the Qur\'an. Arabic particles may be tiny, but they hold entire sentences together.',
      factStat: 'إِنْ (if) vs إِنَّ (indeed) — they look almost identical but have completely opposite functions. إِنْ introduces uncertainty (if), while إِنَّ introduces certainty (indeed). One dot changes everything.',
    },
  },
  {
    orderIndex: 287,
    arabic: 'أَنْ',
    transliteration: 'An',
    meaning: 'That',
    frequency: 578,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/an-that.mp3',
    lessonOrderIndex: 58,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The glue of Arabic sentences',
      body: 'أَنْ (An) means "That." Like its Urdu equivalent "ke" (that), this word connects ideas. "Allah commanded THAT you pray" — أَنْ links the command to the action. Once you spot it, you\'ll see it everywhere in the Qur\'an.',
    },
  },
  {
    orderIndex: 288,
    arabic: 'أَنَّ',
    transliteration: 'Anna',
    meaning: 'That (emphatic)',
    frequency: 362,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/anna.mp3',
    lessonOrderIndex: 58,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The emphatic "that" — adding certainty',
      body: 'أَنَّ (Anna) means "That" with emphasis — used when stating facts or confirmed truths. While أَنْ is neutral, أَنَّ adds weight and certainty to what follows.',
      ayahText: 'وَاعْلَمُوا أَنَّ اللَّهَ مَعَ الْمُتَّقِينَ',
      ayahRef: 'Al-Baqarah 2:194',
    },
  },
  {
    orderIndex: 289,
    arabic: 'أَمْ',
    transliteration: 'Am',
    meaning: 'Or (in questions)',
    frequency: 137,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/am.mp3',
    lessonOrderIndex: 58,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'When the Qur\'an asks you to choose',
      body: 'أَمْ (Am) means "Or" — specifically in questions that present a choice. The Qur\'an uses this particle powerfully: "Are those who know equal to those who do not know? أَمْ (Or) are they the same?" It forces reflection by presenting two starkly different options.',
    },
  },
  {
    orderIndex: 290,
    arabic: 'لَمَّا',
    transliteration: 'Lamma',
    meaning: 'When, Since',
    frequency: 156,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/lamma.mp3',
    lessonOrderIndex: 58,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Timing matters in the Qur\'an',
      body: 'لَمَّا (Lamma) means "When" or "Since." The Qur\'an uses it to mark pivotal moments in stories: "When the messenger came to them..." It signals that something important is about to happen.',
      quickCheckQuestion: 'What does لَمَّا (Lamma) mean?',
      quickCheckOptions: ['When / Since', 'Because', 'However', 'Before'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 59: "The Most Merciful" ──
  {
    orderIndex: 291,
    arabic: 'الرَّحْمَن',
    transliteration: 'Ar-Rahman',
    meaning: 'The Most Merciful',
    frequency: 45,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ar-rahman.mp3',
    lessonOrderIndex: 59,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this name before everything you do',
      body: 'الرَّحْمَن (Ar-Rahman) means "The Most Merciful." Remember رَحْمَة (Rahmah/mercy) from Lesson 1 and رَحِيم (Raheem) from Lesson 29? Same root, but الرَّحْمَن is the most intense form — mercy that overwhelms. Every time you say "Bismillah ir-Rahman ir-Raheem," you begin with this name.',
    },
  },
  {
    orderIndex: 292,
    arabic: 'حَرَام',
    transliteration: 'Haram',
    meaning: 'Forbidden, Sacred',
    frequency: 17,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/haram.mp3',
    lessonOrderIndex: 59,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Two opposite meanings in one word',
      body: 'حَرَام (Haram) means both "Forbidden" and "Sacred." In Urdu, you know it as "haram" (not allowed). But "Al-Masjid al-Haram" means "The Sacred Mosque." The connection? Both meanings involve something set apart — something you cannot violate.',
    },
  },
  {
    orderIndex: 293,
    arabic: 'طَعَام',
    transliteration: 'Ta\'am',
    meaning: 'Food',
    frequency: 24,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/taam.mp3',
    lessonOrderIndex: 59,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an cares about what you eat',
      body: 'طَعَام (Ta\'am) means "Food." The Qur\'an discusses food extensively — what is halal, the importance of feeding the poor, and even food as a sign of Allah\'s blessing.',
      factStat: 'Surah Al-Ma\'idah (The Table Spread) is named after food. The disciples of Isa (AS) asked for a table of food from heaven — طَعَام became the center of an entire surah.',
    },
  },
  {
    orderIndex: 294,
    arabic: 'نَبَأ',
    transliteration: 'Naba\'',
    meaning: 'News, Tidings',
    frequency: 29,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/naba.mp3',
    lessonOrderIndex: 59,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'An entire surah is named after this word',
      body: 'نَبَأ (Naba\') means "News" or "Tidings." Surah An-Naba\' (The News) is the 78th surah, and it opens by asking: "About what are they asking one another? About the great news."',
      ayahText: 'عَمَّ يَتَسَاءَلُونَ عَنِ النَّبَإِ الْعَظِيمِ',
      ayahRef: 'An-Naba\' 78:1-2',
    },
  },
  {
    orderIndex: 295,
    arabic: 'وَاحِد',
    transliteration: 'Wahid',
    meaning: 'One, Single',
    frequency: 24,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/wahid.mp3',
    lessonOrderIndex: 59,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The core message of the entire Qur\'an',
      body: 'وَاحِد (Wahid) means "One." "Ilahun Wahid" (One God) — the central message of the Qur\'an. Al-Wahid is one of Allah\'s names. The entire book revolves around this one concept: there is only One God.',
      quickCheckQuestion: 'What does وَاحِد (Wahid) mean?',
      quickCheckOptions: ['One / Single', 'Many', 'Great', 'Eternal'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 60: "Your Journey Complete" ──
  {
    orderIndex: 296,
    arabic: 'بَنُون',
    transliteration: 'Banun',
    meaning: 'Sons, Children',
    frequency: 80,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/banun.mp3',
    lessonOrderIndex: 60,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Wealth and children — the Qur\'an\'s test pair',
      body: 'بَنُون (Banun) means "Sons" or "Children." The Qur\'an repeatedly pairs "amwal wa banun" (wealth and children) as the two things people chase most.',
      factStat: 'The Qur\'an says "wealth and children are the adornment of this life, but lasting good deeds are better in reward" (Al-Kahf 18:46). بَنُون is a test, not a trophy.',
    },
  },
  {
    orderIndex: 297,
    arabic: 'لِسَان',
    transliteration: 'Lisan',
    meaning: 'Tongue, Language',
    frequency: 25,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/lisan.mp3',
    lessonOrderIndex: 60,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The tool you\'re sharpening right now',
      body: 'لِسَان (Lisan) means "Tongue" or "Language." In Urdu, "zubaan" is used similarly, but "lisan" also appears in formal Urdu. The Qur\'an was revealed in "lisanin arabiyyin mubin" (a clear Arabic tongue). By learning these 300 words, you are training your لِسَان to understand Allah\'s words.',
    },
  },
  {
    orderIndex: 298,
    arabic: 'بَيِّنَة',
    transliteration: 'Bayyinah',
    meaning: 'Clear Evidence',
    frequency: 55,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/bayyinah.mp3',
    lessonOrderIndex: 60,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'An entire surah bears this name',
      body: 'بَيِّنَة (Bayyinah) means "Clear Evidence." Surah Al-Bayyinah is the 98th surah. The Qur\'an uses this word to describe the undeniable proofs Allah sends through His messengers.',
      ayahText: 'لَمْ يَكُنِ الَّذِينَ كَفَرُوا مِنْ أَهْلِ الْكِتَابِ وَالْمُشْرِكِينَ مُنفَكِّينَ حَتَّىٰ تَأْتِيَهُمُ الْبَيِّنَةُ',
      ayahRef: 'Al-Bayyinah 98:1',
    },
  },
  {
    orderIndex: 299,
    arabic: 'رِجَال',
    transliteration: 'Rijal',
    meaning: 'Men',
    frequency: 28,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rijal.mp3',
    lessonOrderIndex: 60,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The plural you just learned the singular of',
      body: 'رِجَال (Rijal) means "Men" — the plural of رَجُل (Rajul) from Lesson 54. The Qur\'an praises "Rijalun la tulhihim tijaratun" — men whom neither trade nor sale distracts from remembering Allah.',
      quickCheckQuestion: 'What is رِجَال (Rijal) the plural of?',
      quickCheckOptions: ['رَجُل (Rajul) — Man', 'رَحْمَة (Rahmah) — Mercy', 'رَسُول (Rasool) — Messenger', 'رَبّ (Rabb) — Lord'],
      quickCheckAnswer: 0,
    },
  },
  {
    orderIndex: 300,
    arabic: 'عَالِم',
    transliteration: 'Aalim',
    meaning: 'Scholar, Knower',
    frequency: 140,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aalim.mp3',
    lessonOrderIndex: 60,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Word 1 was عِلْم. Word 300 is عَالِم. You\'ve come full circle.',
      body: 'عَالِم (Aalim) means "Scholar" or "Knower." Your very first word in Lesson 1 was عِلْم (knowledge). Then عَلِمَ (to know) in Lesson 4, عَلِيم (All-Knowing) in Lesson 29, عَلَّمَ (to teach) in Lesson 44 — and now عَالِم. Same root: ع-ل-م. You started this journey seeking knowledge. You end it as someone who knows. The Qur\'an has made you a student of its language, and that is the beginning of true عِلْم.',
    },
  },
];
