import { IntroductionStyle } from '@prisma/client';
import { WordSeedData } from './words-types';

export const WORDS_L21_L40: WordSeedData[] = [
  // ── Lesson 21: "From, In, On" ──
  {
    orderIndex: 101,
    arabic: 'مِن',
    transliteration: 'Min',
    meaning: 'from, of',
    frequency: 3226,
    audioUrl: '/audio/words/min.mp3',
    lessonOrderIndex: 21,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The most common word in the entire Qur\'an',
      body: 'مِن (Min) means "from" or "of." This tiny two-letter word is everywhere in the Qur\'an. It connects ideas, shows origin, and describes belonging.',
      factStat: 'مِن appears 3,226 times in the Qur\'an — that\'s more than any other particle. You\'ll find it on almost every page.',
    },
  },
  {
    orderIndex: 102,
    arabic: 'فِي',
    transliteration: 'Fi',
    meaning: 'in, within',
    frequency: 1701,
    audioUrl: '/audio/words/fi.mp3',
    lessonOrderIndex: 21,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Fi Amanillah — you say this daily',
      body: 'فِي (Fi) means "in" or "within." When you say "Fi Amanillah" (in the protection of Allah), that opening word is this exact Qur\'anic word. In Urdu too, "fi sadi" (per cent) uses this same Arabic "fi."',
    },
  },
  {
    orderIndex: 103,
    arabic: 'عَلَى',
    transliteration: 'Ala',
    meaning: 'upon, on',
    frequency: 1445,
    audioUrl: '/audio/words/ala.mp3',
    lessonOrderIndex: 21,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Upon everything, He has power',
      body: 'عَلَى (Ala) means "upon" or "on." One of the most powerful phrases in the Qur\'an uses this word to describe Allah\'s limitless ability.',
      ayahText: 'إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ',
      ayahRef: 'Al-Baqarah 2:20',
    },
  },
  {
    orderIndex: 104,
    arabic: 'إِلَى',
    transliteration: 'Ila',
    meaning: 'to, toward',
    frequency: 742,
    audioUrl: '/audio/words/ila.mp3',
    lessonOrderIndex: 21,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Every journey has a direction',
      body: 'إِلَى (Ila) means "to" or "toward." The Qur\'an often reminds us that our ultimate journey is إِلَى اللَّهِ — toward Allah. This word carries the sense of movement, purpose, and return. You hear it in "inna lillahi wa inna ilayhi raji\'oon" — we belong to Allah and to Him we return.',
    },
  },
  {
    orderIndex: 105,
    arabic: 'عَن',
    transliteration: 'An',
    meaning: 'from, about',
    frequency: 465,
    audioUrl: '/audio/words/an.mp3',
    lessonOrderIndex: 21,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Test your preposition knowledge',
      body: 'عَن (An) means "from" or "about." It\'s different from مِن — عَن often implies distance or separation, like turning away from something.',
      quickCheckQuestion: 'What does عَن (An) mean?',
      quickCheckOptions: ['from, about', 'in, within', 'to, toward', 'upon, on'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 22: "The Connecting Words" ──
  {
    orderIndex: 106,
    arabic: 'إِنَّ',
    transliteration: 'Inna',
    meaning: 'Indeed, Verily',
    frequency: 1682,
    audioUrl: '/audio/words/inna.mp3',
    lessonOrderIndex: 22,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s spotlight word',
      body: 'إِنَّ (Inna) means "Indeed" or "Verily." Whenever the Qur\'an wants to emphasize something important, it opens with إِنَّ. Think of it as Allah putting a spotlight on what comes next.',
      factStat: 'إِنَّ appears 1,682 times in the Qur\'an. Nearly every major declaration — about Allah\'s mercy, power, or promises — begins with this word.',
    },
  },
  {
    orderIndex: 107,
    arabic: 'لَا',
    transliteration: 'La',
    meaning: 'No, Not',
    frequency: 1364,
    audioUrl: '/audio/words/la.mp3',
    lessonOrderIndex: 22,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'La ilaha illallah starts with this',
      body: 'لَا (La) means "No" or "Not." You use this in Urdu all the time — "la-jawab" (unanswerable), "la-ilaj" (incurable). And of course, the Shahada itself begins with لَا — the most powerful negation in Islam.',
    },
  },
  {
    orderIndex: 108,
    arabic: 'كُلّ',
    transliteration: 'Kull',
    meaning: 'Every, All',
    frequency: 373,
    audioUrl: '/audio/words/kull.mp3',
    lessonOrderIndex: 22,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Every soul shall taste death',
      body: 'كُلّ (Kull) means "Every" or "All." The Qur\'an uses this word to make universal statements — no exceptions.',
      ayahText: 'كُلُّ نَفْسٍ ذَائِقَةُ الْمَوْتِ',
      ayahRef: 'Aal-e-Imran 3:185',
    },
  },
  {
    orderIndex: 109,
    arabic: 'إِلَّا',
    transliteration: 'Illa',
    meaning: 'Except',
    frequency: 661,
    audioUrl: '/audio/words/illa.mp3',
    lessonOrderIndex: 22,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The exception that changes everything',
      body: 'إِلَّا (Illa) means "Except." In the Shahada, you say "La ilaha illa Allah" — there is no god except Allah. This small word creates the most important exception in Islam. You also hear it in Surah Al-Asr: everyone is at loss, إِلَّا — except those who believe.',
    },
  },
  {
    orderIndex: 110,
    arabic: 'قَدْ',
    transliteration: 'Qad',
    meaning: 'Certainly, Already',
    frequency: 406,
    audioUrl: '/audio/words/qad.mp3',
    lessonOrderIndex: 22,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Qad aflaha — you hear this every Jumu\'ah',
      body: 'قَدْ (Qad) means "Certainly" or "Already." You hear it in "Qad aflaha al-mu\'minoon" — Certainly, the believers have succeeded. It adds emphasis or confirms something is done.',
      quickCheckQuestion: 'What does قَدْ (Qad) mean?',
      quickCheckOptions: ['Certainly, Already', 'Never, Not', 'Perhaps, Maybe', 'Soon, Later'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 23: "Who, Which, This, That" ──
  {
    orderIndex: 111,
    arabic: 'الَّذِي',
    transliteration: 'Alladhi',
    meaning: 'who, which, that',
    frequency: 1442,
    audioUrl: '/audio/words/alladhi.mp3',
    lessonOrderIndex: 23,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s connector word',
      body: 'الَّذِي (Alladhi) means "who," "which," or "that." It connects descriptions to nouns — like "those WHO believe" or "the book WHICH we sent down." Its plural الَّذِينَ is one of the most common words in the Qur\'an.',
      factStat: 'الَّذِي and its forms (الَّذِينَ, الَّتِي, etc.) appear over 1,400 times in the Qur\'an. You literally cannot read a single page without encountering it.',
    },
  },
  {
    orderIndex: 112,
    arabic: 'هَذَا',
    transliteration: 'Hadha',
    meaning: 'this',
    frequency: 317,
    audioUrl: '/audio/words/hadha.mp3',
    lessonOrderIndex: 23,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Hadha kitab — point and say it',
      body: 'هَذَا (Hadha) means "this." You may have heard "hadha" in Arabic conversations or Islamic classes. In Urdu, we say "yeh" for "this," but in Arabic it\'s هَذَا. "Hadha al-Kitab" means "this book" — and that\'s exactly how the Qur\'an refers to itself.',
    },
  },
  {
    orderIndex: 113,
    arabic: 'ذَلِكَ',
    transliteration: 'Dhalika',
    meaning: 'that',
    frequency: 520,
    audioUrl: '/audio/words/dhalika.mp3',
    lessonOrderIndex: 23,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The very second word of Al-Baqarah',
      body: 'ذَلِكَ (Dhalika) means "that." The second verse of Al-Baqarah opens with this word, pointing to the Qur\'an with reverence and certainty.',
      ayahText: 'ذَٰلِكَ الْكِتَابُ لَا رَيْبَ فِيهِ',
      ayahRef: 'Al-Baqarah 2:2',
    },
  },
  {
    orderIndex: 114,
    arabic: 'مَنْ',
    transliteration: 'Man',
    meaning: 'who, whoever',
    frequency: 606,
    audioUrl: '/audio/words/man.mp3',
    lessonOrderIndex: 23,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Whoever does good, it\'s for their own soul',
      body: 'مَنْ (Man) means "who" or "whoever." The Qur\'an uses this word to set up universal principles — whoever does good, whoever believes, whoever is patient. It makes you feel personally addressed. "Man amana" — whoever believes. That\'s you.',
    },
  },
  {
    orderIndex: 115,
    arabic: 'مَا',
    transliteration: 'Ma',
    meaning: 'what, that which',
    frequency: 1266,
    audioUrl: '/audio/words/ma.mp3',
    lessonOrderIndex: 23,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Two letters, massive impact',
      body: 'مَا (Ma) means "what" or "that which." It\'s also used for negation in some contexts. Despite being just two letters, it\'s one of the most versatile words in Arabic.',
      quickCheckQuestion: 'What does مَا (Ma) mean?',
      quickCheckOptions: ['what, that which', 'who, whoever', 'this', 'that'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 24: "Saying No" ──
  {
    orderIndex: 116,
    arabic: 'لَمْ',
    transliteration: 'Lam',
    meaning: 'did not',
    frequency: 353,
    audioUrl: '/audio/words/lam.mp3',
    lessonOrderIndex: 24,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Arabic has three types of "not"',
      body: 'لَمْ (Lam) means "did not" — it negates the past. Arabic is precise about time: لَمْ for "did not," لَا for "does not," and لَنْ for "will never." Each carries a different weight.',
      factStat: 'Arabic has at least 7 different words for negation, each with its own nuance. لَمْ is used 353 times in the Qur\'an, always negating a past action.',
    },
  },
  {
    orderIndex: 117,
    arabic: 'لَنْ',
    transliteration: 'Lan',
    meaning: 'will never',
    frequency: 104,
    audioUrl: '/audio/words/lan.mp3',
    lessonOrderIndex: 24,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'You will never attain goodness until...',
      body: 'لَنْ (Lan) means "will never" — it\'s the strongest future negation in Arabic. When Allah uses لَنْ, it carries absolute certainty. Here it\'s used to inspire generosity.',
      ayahText: 'لَن تَنَالُوا الْبِرَّ حَتَّىٰ تُنفِقُوا مِمَّا تُحِبُّونَ',
      ayahRef: 'Aal-e-Imran 3:92',
    },
  },
  {
    orderIndex: 118,
    arabic: 'بَلْ',
    transliteration: 'Bal',
    meaning: 'rather, but',
    frequency: 122,
    audioUrl: '/audio/words/bal.mp3',
    lessonOrderIndex: 24,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Balke — you use this in Urdu!',
      body: 'بَلْ (Bal) means "rather" or "but." In Urdu, you say "balke" (rather/in fact), which comes directly from this Arabic word. In the Qur\'an, بَلْ is used to correct a wrong assumption — "No! Rather, the truth is..."',
    },
  },
  {
    orderIndex: 119,
    arabic: 'هَلْ',
    transliteration: 'Hal',
    meaning: 'is? did?',
    frequency: 93,
    audioUrl: '/audio/words/hal.mp3',
    lessonOrderIndex: 24,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The question that opens Surah Ad-Dahr',
      body: 'هَلْ (Hal) turns any sentence into a yes/no question. "Hal ata ala al-insan" — Has there come upon man a period of time? The Qur\'an uses هَلْ to make you stop and think. Next time you hear it in recitation, know a question is coming.',
    },
  },
  {
    orderIndex: 120,
    arabic: 'لَوْ',
    transliteration: 'Law',
    meaning: 'if (hypothetical)',
    frequency: 184,
    audioUrl: '/audio/words/law.mp3',
    lessonOrderIndex: 24,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The word for "what if"',
      body: 'لَوْ (Law) means "if" in a hypothetical sense — something that didn\'t happen or is unlikely. The Prophet ﷺ said: "Don\'t say \'law\' (if only), for it opens the door for Shaytan."',
      quickCheckQuestion: 'What kind of "if" does لَوْ (Law) express?',
      quickCheckOptions: ['Hypothetical — something unlikely or didn\'t happen', 'Certain — something that will happen', 'Conditional — if you do X, then Y', 'Temporal — when something happens'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 25: "Things and Places" ──
  {
    orderIndex: 121,
    arabic: 'شَيْء',
    transliteration: 'Shay\'',
    meaning: 'Thing',
    frequency: 283,
    audioUrl: '/audio/words/shay.mp3',
    lessonOrderIndex: 25,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Every single thing belongs to Allah',
      body: 'شَيْء (Shay\') means "thing." Small word, huge scope. The Qur\'an uses it to remind us that Allah\'s power covers every شَيْء — everything.',
      factStat: 'The phrase "kulla shay\'in" (everything) appears over 60 times in the Qur\'an. Allah is described as having power over every شَيْء, knowledge of every شَيْء, and creating every شَيْء.',
    },
  },
  {
    orderIndex: 122,
    arabic: 'مَكَان',
    transliteration: 'Makan',
    meaning: 'Place',
    frequency: 25,
    audioUrl: '/audio/words/makan.mp3',
    lessonOrderIndex: 25,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Makan — identical in Urdu',
      body: 'مَكَان (Makan) means "place." In Urdu, you say "makan" for house and "makaan" for place/dwelling. It comes from the Arabic root ك-و-ن (to be) — a مَكَان is literally "a place where something exists."',
    },
  },
  {
    orderIndex: 123,
    arabic: 'بَيْت',
    transliteration: 'Bayt',
    meaning: 'House',
    frequency: 65,
    audioUrl: '/audio/words/bayt.mp3',
    lessonOrderIndex: 25,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The first house built for mankind',
      body: 'بَيْت (Bayt) means "House." The Ka\'bah is called "Bayt Allah" — the House of Allah. This word connects you to the most sacred place on earth.',
      ayahText: 'إِنَّ أَوَّلَ بَيْتٍ وُضِعَ لِلنَّاسِ لَلَّذِي بِبَكَّةَ مُبَارَكًا',
      ayahRef: 'Aal-e-Imran 3:96',
    },
  },
  {
    orderIndex: 124,
    arabic: 'مَسْجِد',
    transliteration: 'Masjid',
    meaning: 'Mosque',
    frequency: 28,
    audioUrl: '/audio/words/masjid.mp3',
    lessonOrderIndex: 25,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The place of prostration',
      body: 'مَسْجِد (Masjid) means "Mosque" — literally "place of prostration." It comes from the root سَجَدَ (to prostrate). Arabic builds place-nouns using the مَفْعِل pattern: where you prostrate = مَسْجِد. You go to one every week, maybe every day. Now you know what its name really means.',
    },
  },
  {
    orderIndex: 125,
    arabic: 'دَار',
    transliteration: 'Dar',
    meaning: 'Abode, Dwelling',
    frequency: 48,
    audioUrl: '/audio/words/dar.mp3',
    lessonOrderIndex: 25,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Dar-us-Salaam rings a bell?',
      body: 'دَار (Dar) means "Abode" or "Dwelling." Paradise is called "Dar us-Salaam" (the Abode of Peace). In Urdu, "dar" is used in words like "dar-ul-hukumat" (capital city).',
      quickCheckQuestion: 'What does دَار (Dar) mean?',
      quickCheckOptions: ['Abode, Dwelling', 'Door, Gate', 'Road, Path', 'Garden, Park'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 26: "Words and Speech" ──
  {
    orderIndex: 126,
    arabic: 'كَلِمَة',
    transliteration: 'Kalimah',
    meaning: 'Word',
    frequency: 28,
    audioUrl: '/audio/words/kalimah.mp3',
    lessonOrderIndex: 26,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Kalimah — the first thing you learned as a Muslim',
      body: 'كَلِمَة (Kalimah) means "Word." The very first thing you learned in Islam was the Kalimah — the word of testimony. In Urdu, "kalimah" is used exactly the same way. In the Qur\'an, Allah\'s promises are called His "kalimaat" (words).',
    },
  },
  {
    orderIndex: 127,
    arabic: 'قَوْل',
    transliteration: 'Qawl',
    meaning: 'Saying, Word',
    frequency: 92,
    audioUrl: '/audio/words/qawl.mp3',
    lessonOrderIndex: 26,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'When Allah quotes someone, this word appears',
      body: 'قَوْل (Qawl) means "saying" or "speech." Whenever the Qur\'an reports what someone said, this root appears. "Qaala" (he said) is one of the most frequent verbs in the Qur\'an.',
      factStat: 'The verb قَالَ (he said) from the same root appears over 1,700 times in the Qur\'an. Allah uses it to quote prophets, angels, believers, and even disbelievers.',
    },
  },
  {
    orderIndex: 128,
    arabic: 'حَدِيث',
    transliteration: 'Hadith',
    meaning: 'Speech, Narration',
    frequency: 28,
    audioUrl: '/audio/words/hadith.mp3',
    lessonOrderIndex: 26,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'More than just Prophet\'s sayings',
      body: 'حَدِيث (Hadith) means "speech" or "narration." While you know it as the sayings of the Prophet ﷺ, in the Qur\'an itself, Allah uses this word to refer to His own speech — the Qur\'an.',
      ayahText: 'اللَّهُ نَزَّلَ أَحْسَنَ الْحَدِيثِ كِتَابًا مُّتَشَابِهًا',
      ayahRef: 'Az-Zumar 39:23',
    },
  },
  {
    orderIndex: 129,
    arabic: 'ذِكْر',
    transliteration: 'Dhikr',
    meaning: 'Remembrance',
    frequency: 76,
    audioUrl: '/audio/words/dhikr.mp3',
    lessonOrderIndex: 26,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'After every salah, you do this',
      body: 'ذِكْر (Dhikr) means "Remembrance." After every prayer, you do dhikr — SubhanAllah, Alhamdulillah, Allahu Akbar. The Qur\'an itself is called "The Dhikr" — the Reminder. Every tasbeeh you count, every dua you make, is an act of ذِكْر.',
    },
  },
  {
    orderIndex: 130,
    arabic: 'اسْم',
    transliteration: 'Ism',
    meaning: 'Name',
    frequency: 39,
    audioUrl: '/audio/words/ism.mp3',
    lessonOrderIndex: 26,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Bismillah starts with this word',
      body: 'اسْم (Ism) means "Name." "Bismillah" literally means "In the name of Allah" — "bi" (in) + "ism" (name) + "illah" (of Allah). You say this word dozens of times every day.',
      quickCheckQuestion: 'What does اسْم (Ism) mean?',
      quickCheckOptions: ['Name', 'Sign', 'Word', 'Book'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 27: "Obedience and Rebellion" ──
  {
    orderIndex: 131,
    arabic: 'أَطَاعَ',
    transliteration: 'Ata\'a',
    meaning: 'to obey',
    frequency: 72,
    audioUrl: '/audio/words/ataa.mp3',
    lessonOrderIndex: 27,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Itaa\'at — the Urdu word comes from here',
      body: 'أَطَاعَ (Ata\'a) means "to obey." In Urdu, you say "itaa\'at karna" (to obey). Same root, same meaning. The Qur\'an pairs obedience to Allah with obedience to the Messenger — "Ati\'ullah wa ati\'ur Rasool."',
    },
  },
  {
    orderIndex: 132,
    arabic: 'عَصَى',
    transliteration: 'Asa',
    meaning: 'to disobey',
    frequency: 27,
    audioUrl: '/audio/words/asa.mp3',
    lessonOrderIndex: 27,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The opposite of obedience',
      body: 'عَصَى (Asa) means "to disobey." The Qur\'an pairs it with أَطَاعَ (obey) — two paths, two outcomes. Disobedience leads to consequences, but Allah always opens the door to repentance.',
      ayahText: 'وَمَن يَعْصِ اللَّهَ وَرَسُولَهُ فَإِنَّ لَهُ نَارَ جَهَنَّمَ',
      ayahRef: 'Al-Jinn 72:23',
    },
  },
  {
    orderIndex: 133,
    arabic: 'كَذَّبَ',
    transliteration: 'Kadhdhaba',
    meaning: 'to deny, reject',
    frequency: 176,
    audioUrl: '/audio/words/kadhdhaba.mp3',
    lessonOrderIndex: 27,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The doubled letter makes it intense',
      body: 'كَذَّبَ (Kadhdhaba) means "to deny" or "to reject." Notice the doubled ذّ — in Arabic, doubling a letter intensifies the meaning. كَذَبَ means "to lie," but كَذَّبَ means "to call someone a liar" or "to reject the truth."',
      factStat: 'كَذَّبَ and its forms appear 176 times in the Qur\'an. It\'s most frequent in the stories of previous nations who rejected their prophets — a recurring warning.',
    },
  },
  {
    orderIndex: 134,
    arabic: 'تَابَ',
    transliteration: 'Taba',
    meaning: 'to repent',
    frequency: 63,
    audioUrl: '/audio/words/taba.mp3',
    lessonOrderIndex: 27,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The door that never closes',
      body: 'تَابَ (Taba) means "to repent" — literally "to turn back." There is an entire surah called At-Tawbah (The Repentance). No matter how far someone has gone, تَابَ is always available. After every sin, after every mistake, you can turn back. Allah is called At-Tawwab — the One who constantly accepts repentance.',
    },
  },
  {
    orderIndex: 135,
    arabic: 'نَجَّى',
    transliteration: 'Najja',
    meaning: 'to save, deliver',
    frequency: 37,
    audioUrl: '/audio/words/najja.mp3',
    lessonOrderIndex: 27,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Najaat — salvation comes from this root',
      body: 'نَجَّى (Najja) means "to save" or "to deliver." In Urdu, "najaat" (salvation) comes from this root. The Qur\'an uses it when describing how Allah saved the prophets and the believers.',
      quickCheckQuestion: 'What does نَجَّى (Najja) mean?',
      quickCheckOptions: ['to save, deliver', 'to punish', 'to test', 'to forgive'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 28: "Promises and Warnings" ──
  {
    orderIndex: 136,
    arabic: 'وَعَدَ',
    transliteration: 'Wa\'ada',
    meaning: 'to promise',
    frequency: 70,
    audioUrl: '/audio/words/waada.mp3',
    lessonOrderIndex: 28,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Waada karna — same word in Urdu',
      body: 'وَعَدَ (Wa\'ada) means "to promise." In Urdu, "waada" means exactly the same thing. When Allah makes a وَعْد (promise), it is absolutely certain. "Wa\'adallahu" — Allah has promised — appears throughout the Qur\'an, always followed by something beautiful.',
    },
  },
  {
    orderIndex: 137,
    arabic: 'وَعْد',
    transliteration: 'Wa\'d',
    meaning: 'Promise',
    frequency: 49,
    audioUrl: '/audio/words/wad.mp3',
    lessonOrderIndex: 28,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Allah never breaks His promise',
      body: 'وَعْد (Wa\'d) means "Promise." This is the noun form of وَعَدَ (to promise). In the Qur\'an, every promise of Allah is described as absolutely true and unbreakable.',
      factStat: 'The phrase "wa\'dallahi haqqan" (the promise of Allah is true) and similar affirmations appear repeatedly in the Qur\'an. Allah even says "Inna Allaha la yukhliful mi\'aad" — Allah never breaks His promise.',
    },
  },
  {
    orderIndex: 138,
    arabic: 'أَنْذَرَ',
    transliteration: 'Andhara',
    meaning: 'to warn',
    frequency: 44,
    audioUrl: '/audio/words/andhara.mp3',
    lessonOrderIndex: 28,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Every prophet was a warner',
      body: 'أَنْذَرَ (Andhara) means "to warn." The Qur\'an describes every prophet as a "nadhir" (warner). The Prophet Muhammad ﷺ himself is called "nadhir mubeen" — a clear warner.',
      ayahText: 'إِنَّا أَرْسَلْنَاكَ بِالْحَقِّ بَشِيرًا وَنَذِيرًا',
      ayahRef: 'Al-Baqarah 2:119',
    },
  },
  {
    orderIndex: 139,
    arabic: 'بَشَّرَ',
    transliteration: 'Bashshara',
    meaning: 'to give glad tidings',
    frequency: 38,
    audioUrl: '/audio/words/bashshara.mp3',
    lessonOrderIndex: 28,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Basharat — the good news you love to hear',
      body: 'بَشَّرَ (Bashshara) means "to give glad tidings." In Urdu, "basharat" or "khush-khabri" carries this meaning. The Qur\'an always pairs warning (indhaar) with glad tidings (bishaarah). Every prophet warned AND gave good news. The balance is beautiful — hope always accompanies the warning.',
    },
  },
  {
    orderIndex: 140,
    arabic: 'سَوْفَ',
    transliteration: 'Sawfa',
    meaning: 'shall, will',
    frequency: 42,
    audioUrl: '/audio/words/sawfa.mp3',
    lessonOrderIndex: 28,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The future is coming',
      body: 'سَوْفَ (Sawfa) means "shall" or "will." It pushes a verb into the future tense. "Sawfa ta\'lamoon" — you SHALL know. It carries weight and certainty about what is to come.',
      quickCheckQuestion: 'What does سَوْفَ (Sawfa) indicate?',
      quickCheckOptions: ['Future — something that will happen', 'Past — something that already happened', 'Negation — something that won\'t happen', 'Question — asking if something happened'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 29: "Allah's Beautiful Names" ──
  {
    orderIndex: 141,
    arabic: 'عَلِيم',
    transliteration: 'Aleem',
    meaning: 'All-Knowing',
    frequency: 101,
    audioUrl: '/audio/words/aleem.mp3',
    lessonOrderIndex: 29,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'From Ilm to Aleem — you know this pattern',
      body: 'عَلِيم (Aleem) means "All-Knowing." Remember عِلْم (Ilm/knowledge) from Lesson 1? Same root! عِلْم = knowledge, عَلِمَ = to know, عَلِيم = the ultimate knower. In Urdu, "Aleem" is a common name meaning "the knowledgeable one." As a Name of Allah, it means the One whose knowledge has no limit.',
    },
  },
  {
    orderIndex: 142,
    arabic: 'رَحِيم',
    transliteration: 'Rahim',
    meaning: 'Most Merciful',
    frequency: 112,
    audioUrl: '/audio/words/rahim.mp3',
    lessonOrderIndex: 29,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'You say this name before every surah',
      body: 'رَحِيم (Rahim) means "Most Merciful." You say "Bismillah ir-Rahman ir-Rahim" before every surah. Rahim describes Allah\'s special, ongoing mercy for the believers.',
      ayahText: 'إِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ',
      ayahRef: 'Al-Baqarah 2:173',
    },
  },
  {
    orderIndex: 143,
    arabic: 'غَفُور',
    transliteration: 'Ghafoor',
    meaning: 'Most Forgiving',
    frequency: 62,
    audioUrl: '/audio/words/ghafoor.mp3',
    lessonOrderIndex: 29,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The name Allah pairs with Rahim most often',
      body: 'غَفُور (Ghafoor) means "Most Forgiving." It follows the فَعُول pattern, which means "one who does something excessively." So غَفُور doesn\'t just mean "forgiving" — it means "overwhelmingly, constantly forgiving."',
      factStat: 'The pairing "Ghafoor ur-Rahim" (Most Forgiving, Most Merciful) appears 72 times in the Qur\'an — the most frequent pair of divine names. Allah chose to pair forgiveness with mercy more than any other combination.',
    },
  },
  {
    orderIndex: 144,
    arabic: 'سَمِيع',
    transliteration: 'Sami\'',
    meaning: 'All-Hearing',
    frequency: 39,
    audioUrl: '/audio/words/sami.mp3',
    lessonOrderIndex: 29,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Sami\'Allahu liman hamidah — you say it in every rakat',
      body: 'سَمِيع (Sami\') means "All-Hearing." Every time you rise from ruku\', you say "Sami\'Allahu liman hamidah" — Allah hears the one who praises Him. That\'s this word in action. Your quiet duas, your silent tears, your whispered prayers — As-Sami\' hears them all.',
    },
  },
  {
    orderIndex: 145,
    arabic: 'حَكِيم',
    transliteration: 'Hakim',
    meaning: 'All-Wise',
    frequency: 84,
    audioUrl: '/audio/words/hakim.mp3',
    lessonOrderIndex: 29,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Hikmat comes from the same root',
      body: 'حَكِيم (Hakim) means "All-Wise." In Urdu, "hikmat" (wisdom) and "hakim" (wise person/doctor) both come from this root. When paired with عَلِيم, it means Allah not only knows everything but acts with perfect wisdom.',
      quickCheckQuestion: 'What does حَكِيم (Hakim) mean as a Name of Allah?',
      quickCheckOptions: ['All-Wise', 'All-Powerful', 'All-Seeing', 'All-Merciful'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 30: "Covenants and Testimony" ──
  {
    orderIndex: 146,
    arabic: 'عَهْد',
    transliteration: 'Ahd',
    meaning: 'Covenant, Promise',
    frequency: 29,
    audioUrl: '/audio/words/ahd.mp3',
    lessonOrderIndex: 30,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Ahd — the Urdu word for a solemn vow',
      body: 'عَهْد (Ahd) means "Covenant" or "Promise." In Urdu, "ahd karna" means to make a solemn vow. In the Qur\'an, Allah speaks of the covenant He made with the Children of Israel and the covenant between Allah and the believers. An ahd is weightier than a simple promise — it\'s a binding commitment.',
    },
  },
  {
    orderIndex: 147,
    arabic: 'شَهِيد',
    transliteration: 'Shahid',
    meaning: 'Witness, Martyr',
    frequency: 40,
    audioUrl: '/audio/words/shahid.mp3',
    lessonOrderIndex: 30,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Witness first, martyr second',
      body: 'شَهِيد (Shahid) means "Witness" — and by extension, "Martyr." The original meaning is someone who bears witness. A martyr is called shahid because they witness the truth and give their life testifying to it.',
      factStat: 'The root ش-ه-د appears in the Shahada (testimony of faith), the word "shahid" (witness/martyr), and "mashhad" (a scene). All revolve around the concept of witnessing and testifying to truth.',
    },
  },
  {
    orderIndex: 148,
    arabic: 'حُكْم',
    transliteration: 'Hukm',
    meaning: 'Judgment, Rule',
    frequency: 30,
    audioUrl: '/audio/words/hukm.mp3',
    lessonOrderIndex: 30,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Judgment belongs to Allah alone',
      body: 'حُكْم (Hukm) means "Judgment" or "Rule." From the same root as حَكِيم (All-Wise). In the Qur\'an, ultimate حُكْم belongs to Allah — He is the final Judge and Lawgiver.',
      ayahText: 'إِنِ الْحُكْمُ إِلَّا لِلَّهِ',
      ayahRef: 'Yusuf 12:40',
    },
  },
  {
    orderIndex: 149,
    arabic: 'مَثَل',
    transliteration: 'Mathal',
    meaning: 'Parable, Example',
    frequency: 87,
    audioUrl: '/audio/words/mathal.mp3',
    lessonOrderIndex: 30,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Allah teaches through stories and examples',
      body: 'مَثَل (Mathal) means "Parable" or "Example." In Urdu, "misaal" comes from the same root. The Qur\'an is filled with parables — the light of faith, the spider\'s web, the rain that brings life. Allah says He strikes these examples "for people so they may reflect." Every مَثَل is a lesson wrapped in imagery.',
    },
  },
  {
    orderIndex: 150,
    arabic: 'أَهْل',
    transliteration: 'Ahl',
    meaning: 'Family, People of',
    frequency: 127,
    audioUrl: '/audio/words/ahl.mp3',
    lessonOrderIndex: 30,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Ahl-e-Kitab — you\'ve heard this phrase',
      body: 'أَهْل (Ahl) means "Family" or "People of." In Urdu, "ahl-e-khanah" means family members. The Qur\'an uses "Ahl al-Kitab" (People of the Book) for Jews and Christians.',
      quickCheckQuestion: 'What does أَهْل (Ahl) mean?',
      quickCheckOptions: ['Family, People of', 'House, Home', 'Friend, Companion', 'Leader, Chief'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 31: "The Essential Verb" ──
  {
    orderIndex: 151,
    arabic: 'كَانَ',
    transliteration: 'Kana',
    meaning: 'to be, was',
    frequency: 1358,
    audioUrl: '/audio/words/kana.mp3',
    lessonOrderIndex: 31,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The verb that describes Allah\'s eternal nature',
      body: 'كَانَ (Kana) means "to be" or "was." When the Qur\'an says "Kana Allahu Ghafuran Rahima," it doesn\'t mean Allah WAS forgiving — it means He always has been and continues to be. كَانَ with Allah implies permanence.',
      factStat: 'كَانَ appears 1,358 times in the Qur\'an — making it the most frequent verb after قَالَ (to say). Almost every description of Allah\'s attributes uses كَانَ.',
    },
  },
  {
    orderIndex: 152,
    arabic: 'لَيْسَ',
    transliteration: 'Laysa',
    meaning: 'is not',
    frequency: 89,
    audioUrl: '/audio/words/laysa.mp3',
    lessonOrderIndex: 31,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'There is nothing like Him',
      body: 'لَيْسَ (Laysa) means "is not." It negates a state of being. The most powerful use of لَيْسَ in the Qur\'an affirms Allah\'s absolute uniqueness — nothing is like Him.',
      ayahText: 'لَيْسَ كَمِثْلِهِ شَيْءٌ وَهُوَ السَّمِيعُ الْبَصِيرُ',
      ayahRef: 'Ash-Shura 42:11',
    },
  },
  {
    orderIndex: 153,
    arabic: 'فَعَلَ',
    transliteration: 'Fa\'ala',
    meaning: 'to do',
    frequency: 88,
    audioUrl: '/audio/words/faala.mp3',
    lessonOrderIndex: 31,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Fe\'l — every Arabic grammar class starts here',
      body: 'فَعَلَ (Fa\'ala) means "to do." In Urdu grammar, "fe\'l" (verb) comes from this word. Arabic grammar uses فَعَلَ as the template for all verb patterns — fa\'ala, fa\'\'ala, af\'ala. If you\'ve ever studied Arabic basics, this was your first verb.',
    },
  },
  {
    orderIndex: 154,
    arabic: 'وَجَدَ',
    transliteration: 'Wajada',
    meaning: 'to find',
    frequency: 106,
    audioUrl: '/audio/words/wajada.mp3',
    lessonOrderIndex: 31,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'He found you lost, and guided you',
      body: 'وَجَدَ (Wajada) means "to find." In Surah Ad-Duha, Allah reminds the Prophet ﷺ: "Did He not find you an orphan and give you shelter? And He found you lost and guided you." This tender verb describes Allah finding us in our most vulnerable moments and lifting us up.',
    },
  },
  {
    orderIndex: 155,
    arabic: 'سَأَلَ',
    transliteration: 'Sa\'ala',
    meaning: 'to ask',
    frequency: 106,
    audioUrl: '/audio/words/saala.mp3',
    lessonOrderIndex: 31,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Sawaal comes from this root',
      body: 'سَأَلَ (Sa\'ala) means "to ask." In Urdu, "sawaal" (question) comes directly from this root. The Qur\'an uses this both for asking questions and for asking Allah in dua.',
      quickCheckQuestion: 'What does سَأَلَ (Sa\'ala) mean?',
      quickCheckOptions: ['to ask', 'to answer', 'to say', 'to listen'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 32: "The Human Being" ──
  {
    orderIndex: 156,
    arabic: 'إِنْسَان',
    transliteration: 'Insan',
    meaning: 'Human, Mankind',
    frequency: 71,
    audioUrl: '/audio/words/insan.mp3',
    lessonOrderIndex: 32,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Insaan — exactly the same in Urdu',
      body: 'إِنْسَان (Insan) means "Human" or "Mankind." This is one of those words that\'s identical in Urdu and Arabic. Some scholars say it comes from "uns" (companionship) — humans are social beings. Others link it to "nisyan" (forgetfulness) — humans forget, which is why we need reminders.',
    },
  },
  {
    orderIndex: 157,
    arabic: 'وَجْه',
    transliteration: 'Wajh',
    meaning: 'Face',
    frequency: 71,
    audioUrl: '/audio/words/wajh.mp3',
    lessonOrderIndex: 32,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Wherever you turn, there is the Face of Allah',
      body: 'وَجْه (Wajh) means "Face." In the Qur\'an, it\'s used literally for human faces and metaphorically for the "Face" (presence/essence) of Allah. One of the most beautiful verses uses this word.',
      ayahText: 'فَأَيْنَمَا تُوَلُّوا فَثَمَّ وَجْهُ اللَّهِ',
      ayahRef: 'Al-Baqarah 2:115',
    },
  },
  {
    orderIndex: 158,
    arabic: 'يَد',
    transliteration: 'Yad',
    meaning: 'Hand',
    frequency: 120,
    audioUrl: '/audio/words/yad.mp3',
    lessonOrderIndex: 32,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Two letters, 120 appearances',
      body: 'يَد (Yad) means "Hand." Despite being one of the shortest words in Arabic, it carries deep significance in the Qur\'an — from the "Hand of Allah" being above their hands to "what your right hand possesses."',
      factStat: 'يَد and its plural أَيْدِي appear 120 times in the Qur\'an. The "hand" is used metaphorically for power, giving, covenant, and action — making it one of the most symbolically rich body words.',
    },
  },
  {
    orderIndex: 159,
    arabic: 'عَيْن',
    transliteration: 'Ayn',
    meaning: 'Eye, Spring',
    frequency: 57,
    audioUrl: '/audio/words/ayn.mp3',
    lessonOrderIndex: 32,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your eyes and the springs of Paradise',
      body: 'عَيْن (Ayn) means both "Eye" and "Spring (of water)." In Urdu, "ain" is used the same way. The Qur\'an describes Paradise as having flowing springs (\'uyoon). The same word for what you see with is used for what gives life to the earth. Beautiful, isn\'t it?',
    },
  },
  {
    orderIndex: 160,
    arabic: 'خَلْق',
    transliteration: 'Khalq',
    meaning: 'Creation',
    frequency: 52,
    audioUrl: '/audio/words/khalq.mp3',
    lessonOrderIndex: 32,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Remember خَلَقَ from Lesson 4?',
      body: 'خَلْق (Khalq) means "Creation." You learned the verb خَلَقَ (to create) earlier. خَلْق is the noun — the act or result of creation. Same root, different pattern.',
      quickCheckQuestion: 'What does خَلْق (Khalq) mean?',
      quickCheckOptions: ['Creation', 'Knowledge', 'Mercy', 'Guidance'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 33: "Angels and Devils" ──
  {
    orderIndex: 161,
    arabic: 'مَلَك',
    transliteration: 'Malak',
    meaning: 'Angel',
    frequency: 88,
    audioUrl: '/audio/words/malak.mp3',
    lessonOrderIndex: 33,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Not to be confused with Malik (King)',
      body: 'مَلَك (Malak) means "Angel." Be careful — مَلَك (Malak) is angel, but مَلِك (Malik) is king! One vowel changes the entire meaning. Angels are mentioned throughout the Qur\'an as obedient servants of Allah.',
      factStat: 'The Qur\'an names only a few angels by name — Jibreel, Mikail, and the Angel of Death. But مَلَك and its plural مَلَائِكَة appear 88 times, showing how central angels are to Islamic belief.',
    },
  },
  {
    orderIndex: 162,
    arabic: 'شَيْطَان',
    transliteration: 'Shaytan',
    meaning: 'Satan, Devil',
    frequency: 80,
    audioUrl: '/audio/words/shaytan.mp3',
    lessonOrderIndex: 33,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Shaitan — the same in every language you speak',
      body: 'شَيْطَان (Shaytan) means "Satan" or "Devil." You know this word from Urdu, English ("Satan"), and daily life — "A\'udhu billahi min ash-Shaytanir rajeem." The Qur\'an warns about Shaytan\'s tricks in detail so you can recognize and resist them.',
    },
  },
  {
    orderIndex: 163,
    arabic: 'جَهَنَّم',
    transliteration: 'Jahannam',
    meaning: 'Hellfire',
    frequency: 77,
    audioUrl: '/audio/words/jahannam.mp3',
    lessonOrderIndex: 33,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The warning that motivates change',
      body: 'جَهَنَّم (Jahannam) means "Hellfire." The Qur\'an mentions it as a warning to inspire us toward good — not to paralyze with fear, but to motivate positive action.',
      ayahText: 'وَاتَّقُوا النَّارَ الَّتِي أُعِدَّتْ لِلْكَافِرِينَ',
      ayahRef: 'Aal-e-Imran 3:131',
    },
  },
  {
    orderIndex: 164,
    arabic: 'خَالِد',
    transliteration: 'Khalid',
    meaning: 'Abiding forever',
    frequency: 74,
    audioUrl: '/audio/words/khalid.mp3',
    lessonOrderIndex: 33,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A popular name with a powerful meaning',
      body: 'خَالِد (Khalid) means "Abiding forever" or "Eternal." Many people are named Khalid, meaning "the eternal one." In the Qur\'an, it\'s used for both the people of Paradise (khalidina fiha — abiding therein forever) and as a warning for those in the Fire. The akhirah is forever — that\'s why our choices in this life matter so much.',
    },
  },
  {
    orderIndex: 165,
    arabic: 'أَصْحَاب',
    transliteration: 'Ashab',
    meaning: 'Companions, People of',
    frequency: 78,
    audioUrl: '/audio/words/ashab.mp3',
    lessonOrderIndex: 33,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Ashab-ul-Kahf — the famous cave companions',
      body: 'أَصْحَاب (Ashab) means "Companions" or "People of." The Qur\'an uses it in famous phrases — Ashab al-Kahf (Companions of the Cave), Ashab an-Nar (People of the Fire), Ashab al-Jannah (People of Paradise).',
      quickCheckQuestion: 'What does أَصْحَاب (Ashab) mean?',
      quickCheckOptions: ['Companions, People of', 'Angels, Messengers', 'Kings, Rulers', 'Scholars, Teachers'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 34: "Family" ──
  {
    orderIndex: 166,
    arabic: 'وَلَد',
    transliteration: 'Walad',
    meaning: 'Child, Offspring',
    frequency: 56,
    audioUrl: '/audio/words/walad.mp3',
    lessonOrderIndex: 34,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Walid/Walida — your parents in Urdu',
      body: 'وَلَد (Walad) means "Child" or "Offspring." In Urdu, "walid" means father (the one who begets) and "walida" means mother. The root و-ل-د is all about birth and parentage. You already use this family of words every day.',
    },
  },
  {
    orderIndex: 167,
    arabic: 'ابْن',
    transliteration: 'Ibn',
    meaning: 'Son',
    frequency: 63,
    audioUrl: '/audio/words/ibn.mp3',
    lessonOrderIndex: 34,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Every Muslim scholar\'s name has this',
      body: 'ابْن (Ibn) means "Son." You see it in countless names — Ibn Kathir, Ibn Taymiyyah, Ibn Sina, Ibn Battuta. It\'s the "bin" in names like "Muhammad bin Abdullah." When you see "Ibn" in a name, you now know it means "son of."',
      factStat: 'The Qur\'an famously says "Isa ibn Maryam" (Jesus son of Mary) — using ابْن to establish lineage through his mother, since he had no earthly father. This phrase appears 23 times.',
    },
  },
  {
    orderIndex: 168,
    arabic: 'أَخ',
    transliteration: 'Akh',
    meaning: 'Brother',
    frequency: 75,
    audioUrl: '/audio/words/akh.mp3',
    lessonOrderIndex: 34,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The believers are but brothers',
      body: 'أَخ (Akh) means "Brother." The Qur\'an uses this word both for biological brothers and for brotherhood in faith — a powerful concept that unites all Muslims as one family.',
      ayahText: 'إِنَّمَا الْمُؤْمِنُونَ إِخْوَةٌ فَأَصْلِحُوا بَيْنَ أَخَوَيْكُمْ',
      ayahRef: 'Al-Hujurat 49:10',
    },
  },
  {
    orderIndex: 169,
    arabic: 'نِسَاء',
    transliteration: 'Nisa\'',
    meaning: 'Women',
    frequency: 59,
    audioUrl: '/audio/words/nisa.mp3',
    lessonOrderIndex: 34,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'An entire surah is named after women',
      body: 'نِسَاء (Nisa\') means "Women." Surah An-Nisa (The Women) is the 4th and one of the longest surahs in the Qur\'an, dealing with women\'s rights, inheritance, and family law. The fact that Allah dedicated an entire surah to women shows their importance in Islam.',
    },
  },
  {
    orderIndex: 170,
    arabic: 'زَوْج',
    transliteration: 'Zawj',
    meaning: 'Spouse, Pair',
    frequency: 76,
    audioUrl: '/audio/words/zawj.mp3',
    lessonOrderIndex: 34,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Not just spouse — everything comes in pairs',
      body: 'زَوْج (Zawj) means "Spouse" or "Pair." The Qur\'an uses it for husband, wife, and even for pairs in nature — "And of everything We created pairs." It reminds us that balance and partnership are built into creation.',
      quickCheckQuestion: 'What does زَوْج (Zawj) mean?',
      quickCheckOptions: ['Spouse, Pair', 'Child, Offspring', 'Brother, Sibling', 'Friend, Companion'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 35: "Wealth and Deeds" ──
  {
    orderIndex: 171,
    arabic: 'مَال',
    transliteration: 'Mal',
    meaning: 'Wealth, Property',
    frequency: 86,
    audioUrl: '/audio/words/mal.mp3',
    lessonOrderIndex: 35,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Maal — the Urdu word for wealth',
      body: 'مَال (Mal) means "Wealth" or "Property." In Urdu, "maal" is used the same way — "maal-o-daulat" (wealth and riches). The Qur\'an often mentions مَال alongside children as the two things people love most — then reminds us that good deeds are better and more lasting.',
    },
  },
  {
    orderIndex: 172,
    arabic: 'عَمَل',
    transliteration: 'Amal',
    meaning: 'Deed, Work',
    frequency: 71,
    audioUrl: '/audio/words/amal.mp3',
    lessonOrderIndex: 35,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Your deeds are being recorded right now',
      body: 'عَمَل (Amal) means "Deed" or "Work." Remember عَمِلَ (to do/work) from Lesson 4? عَمَل is the noun — the deed itself. The phrase "amilus-salihaat" (do good deeds) is one of the Qur\'an\'s most repeated calls to action.',
      factStat: 'The phrase "alladhina amanu wa amilus-salihaat" (those who believe and do good deeds) appears over 50 times in the Qur\'an. Faith and action are never separated — belief without deeds is incomplete.',
    },
  },
  {
    orderIndex: 173,
    arabic: 'كَسَبَ',
    transliteration: 'Kasaba',
    meaning: 'to earn',
    frequency: 62,
    audioUrl: '/audio/words/kasaba.mp3',
    lessonOrderIndex: 35,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'You earn what you work for — good or bad',
      body: 'كَسَبَ (Kasaba) means "to earn." The Qur\'an uses this for earning both rewards and sins. Every soul earns what it puts forward. Your spiritual account balance is built one deed at a time.',
      ayahText: 'لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ',
      ayahRef: 'Al-Baqarah 2:286',
    },
  },
  {
    orderIndex: 174,
    arabic: 'مَتَاع',
    transliteration: 'Mata\'',
    meaning: 'Provision, Enjoyment',
    frequency: 35,
    audioUrl: '/audio/words/mata.mp3',
    lessonOrderIndex: 35,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'This dunya is just temporary enjoyment',
      body: 'مَتَاع (Mata\') means "Provision" or "Enjoyment." The Qur\'an uses this word to describe worldly life — "mata\'ul hayatid-dunya" (the enjoyment of worldly life). It\'s not saying enjoyment is bad — it\'s saying it\'s temporary. Real, lasting reward is with Allah. This perspective shift changes how you see your daily hustle.',
    },
  },
  {
    orderIndex: 175,
    arabic: 'كَثِير',
    transliteration: 'Kathir',
    meaning: 'Much, Many',
    frequency: 42,
    audioUrl: '/audio/words/kathir.mp3',
    lessonOrderIndex: 35,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Ibn Kathir — the famous scholar\'s name means this',
      body: 'كَثِير (Kathir) means "Much" or "Many." You\'ve heard it in the name "Ibn Kathir" — the famous Qur\'an commentator whose name literally means "son of abundance." In the Qur\'an, it\'s used to describe both blessings and people.',
      quickCheckQuestion: 'What does كَثِير (Kathir) mean?',
      quickCheckOptions: ['Much, Many', 'Few, Little', 'Big, Large', 'Strong, Powerful'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 36: "Then, Or, Until" ──
  {
    orderIndex: 176,
    arabic: 'ثُمَّ',
    transliteration: 'Thumma',
    meaning: 'Then, Moreover',
    frequency: 338,
    audioUrl: '/audio/words/thumma.mp3',
    lessonOrderIndex: 36,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s sequencing word',
      body: 'ثُمَّ (Thumma) means "Then" or "Moreover." Unlike "fa" (and then, immediately), ثُمَّ implies a gap or sequence. It chains events: He created you, ثُمَّ He will cause you to die, ثُمَّ He will give you life again.',
      factStat: 'ثُمَّ appears 338 times in the Qur\'an. It\'s the primary tool for building sequences — creation narratives, Day of Judgment descriptions, and historical accounts all rely on ثُمَّ to move the story forward.',
    },
  },
  {
    orderIndex: 177,
    arabic: 'أَوْ',
    transliteration: 'Aw',
    meaning: 'Or',
    frequency: 280,
    audioUrl: '/audio/words/aw.mp3',
    lessonOrderIndex: 36,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Ya — in Urdu we say "ya," in Arabic it\'s Aw',
      body: 'أَوْ (Aw) means "Or." In Urdu, you say "ya" for "or," but in Arabic it\'s أَوْ. It presents choices and alternatives in the Qur\'an — "Do they not reflect, or have their hearts been locked?" Two-letter words carry big meaning in Arabic.',
    },
  },
  {
    orderIndex: 178,
    arabic: 'حَتَّى',
    transliteration: 'Hatta',
    meaning: 'Until',
    frequency: 95,
    audioUrl: '/audio/words/hatta.mp3',
    lessonOrderIndex: 36,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'You will never attain goodness UNTIL...',
      body: 'حَتَّى (Hatta) means "Until." It sets a condition or endpoint. The Qur\'an uses it to set the bar — you won\'t reach a goal حَتَّى you fulfill a condition.',
      ayahText: 'لَن تَنَالُوا الْبِرَّ حَتَّىٰ تُنفِقُوا مِمَّا تُحِبُّونَ',
      ayahRef: 'Aal-e-Imran 3:92',
    },
  },
  {
    orderIndex: 179,
    arabic: 'لَعَلَّ',
    transliteration: 'La\'alla',
    meaning: 'Perhaps, So that',
    frequency: 123,
    audioUrl: '/audio/words/laalla.mp3',
    lessonOrderIndex: 36,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'So that you may be grateful',
      body: 'لَعَلَّ (La\'alla) means "Perhaps" or "So that." The Qur\'an frequently ends commands with لَعَلَّ — "so that you may become mindful," "so that you may be grateful," "so that you may succeed." It reveals the purpose behind every instruction. Next time you read "la\'allakum," know that Allah is about to tell you WHY.',
    },
  },
  {
    orderIndex: 180,
    arabic: 'لَكِنْ',
    transliteration: 'Lakin',
    meaning: 'But, However',
    frequency: 65,
    audioUrl: '/audio/words/lakin.mp3',
    lessonOrderIndex: 36,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Lekin — you say this in Urdu every day',
      body: 'لَكِنْ (Lakin) means "But" or "However." In Urdu, "lekin" is exactly the same word with exactly the same meaning. It introduces a contrast or exception — "They say one thing, لَكِنْ the truth is different."',
      quickCheckQuestion: 'What does لَكِنْ (Lakin) mean?',
      quickCheckOptions: ['But, However', 'And, Also', 'Then, Next', 'Or, Either'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 37: "Before, After, Between" ──
  {
    orderIndex: 181,
    arabic: 'قَبْلَ',
    transliteration: 'Qabla',
    meaning: 'Before',
    frequency: 197,
    audioUrl: '/audio/words/qabla.mp3',
    lessonOrderIndex: 37,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Qabl az — "before" in Urdu is identical',
      body: 'قَبْلَ (Qabla) means "Before." In Urdu, "qabl" or "qabl az" means exactly the same thing — "qabl az waqt" (before time). The Qur\'an uses it frequently — "min qablu" (from before), referring to previous nations, previous scriptures, and time before creation.',
    },
  },
  {
    orderIndex: 182,
    arabic: 'بَعْدَ',
    transliteration: 'Ba\'da',
    meaning: 'After',
    frequency: 133,
    audioUrl: '/audio/words/bada.mp3',
    lessonOrderIndex: 37,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'After hardship comes ease',
      body: 'بَعْدَ (Ba\'da) means "After." The Qur\'an uses this word to teach sequence and consequence. One of the most comforting messages comes through this concept — after difficulty, ease.',
      ayahText: 'فَإِنَّ مَعَ الْعُسْرِ يُسْرًا إِنَّ مَعَ الْعُسْرِ يُسْرًا',
      ayahRef: 'Ash-Sharh 94:5-6',
    },
  },
  {
    orderIndex: 183,
    arabic: 'عِنْدَ',
    transliteration: 'Inda',
    meaning: 'At, Near, With',
    frequency: 160,
    audioUrl: '/audio/words/inda.mp3',
    lessonOrderIndex: 37,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'What\'s "with" Allah is better',
      body: 'عِنْدَ (Inda) means "At," "Near," or "With." The Qur\'an uses "inda Allah" (with Allah) to describe what truly matters — the rewards, the knowledge, and the judgment that are عِنْدَ اللَّهِ.',
      factStat: 'The phrase "inda Allah" (with/near Allah) appears over 90 times in the Qur\'an. It\'s used to say that true reward, true knowledge, and the final decision are all "with Allah" — not with people.',
    },
  },
  {
    orderIndex: 184,
    arabic: 'بَيْنَ',
    transliteration: 'Bayna',
    meaning: 'Between',
    frequency: 243,
    audioUrl: '/audio/words/bayna.mp3',
    lessonOrderIndex: 37,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Make peace between your brothers',
      body: 'بَيْنَ (Bayna) means "Between." The Qur\'an uses this word when talking about relationships — "fa aslihu bayna akhawaykum" (make peace between your brothers). It also describes what\'s between the heavens and the earth, between people, between nations. Next time there\'s a conflict around you, remember: your job is to fix what\'s بَيْنَ people.',
    },
  },
  {
    orderIndex: 185,
    arabic: 'مَعَ',
    transliteration: 'Ma\'a',
    meaning: 'With, Together',
    frequency: 159,
    audioUrl: '/audio/words/maa.mp3',
    lessonOrderIndex: 37,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Allah is with the patient ones',
      body: 'مَعَ (Ma\'a) means "With" or "Together." One of the most comforting phrases in the Qur\'an is "Innallaha ma\'as-sabireen" — Indeed, Allah is with the patient. You\'re never alone.',
      quickCheckQuestion: 'What does مَعَ (Ma\'a) mean?',
      quickCheckOptions: ['With, Together', 'Before, Earlier', 'After, Later', 'Between, Among'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 38: "O You Who Believe" ──
  {
    orderIndex: 186,
    arabic: 'بَعْض',
    transliteration: 'Ba\'d',
    meaning: 'Some, Part',
    frequency: 157,
    audioUrl: '/audio/words/bad.mp3',
    lessonOrderIndex: 38,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'When the Qur\'an says "some" it means exactly some',
      body: 'بَعْض (Ba\'d) means "Some" or "Part." Arabic is precise — كُلّ means "all," بَعْض means "some." When the Qur\'an says "ba\'duhum" (some of them), it\'s being carefully specific, not generalizing.',
      factStat: 'بَعْض appears 157 times in the Qur\'an. It\'s often used in "ba\'dukum li-ba\'d" (some of you to others) — describing how humans relate to each other, help each other, or test each other.',
    },
  },
  {
    orderIndex: 187,
    arabic: 'أُولَئِكَ',
    transliteration: 'Ula\'ika',
    meaning: 'Those',
    frequency: 204,
    audioUrl: '/audio/words/ulaika.mp3',
    lessonOrderIndex: 38,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Those are the ones who are guided',
      body: 'أُولَئِكَ (Ula\'ika) means "Those" — pointing to a group with emphasis. The Qur\'an uses it to identify the people being discussed, often followed by their reward or description.',
      ayahText: 'أُولَٰئِكَ عَلَىٰ هُدًى مِّن رَّبِّهِمْ وَأُولَٰئِكَ هُمُ الْمُفْلِحُونَ',
      ayahRef: 'Al-Baqarah 2:5',
    },
  },
  {
    orderIndex: 188,
    arabic: 'إِذَا',
    transliteration: 'Idha',
    meaning: 'When, If',
    frequency: 405,
    audioUrl: '/audio/words/idha.mp3',
    lessonOrderIndex: 38,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Idha — setting the scene for what\'s next',
      body: 'إِذَا (Idha) means "When" or "If." Many dramatic surahs open with إِذَا — "Idhash-shamsu kuwwirat" (When the sun is wrapped up), "Idhas-samaa\'un-shaqqat" (When the sky is split open). In Urdu discourse, "idha" is occasionally used in formal or religious contexts with the same meaning.',
    },
  },
  {
    orderIndex: 189,
    arabic: 'أَيُّهَا',
    transliteration: 'Ayyuha',
    meaning: 'O (vocative)',
    frequency: 153,
    audioUrl: '/audio/words/ayyuha.mp3',
    lessonOrderIndex: 38,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Ya ayyuhal-ladhina amanu — Allah is talking to YOU',
      body: 'أَيُّهَا (Ayyuha) means "O" — it\'s the vocative particle used when calling out to someone. "Ya ayyuhal-ladhina amanu" (O you who believe) is one of the most frequent addresses in the Qur\'an. Every time you hear it, Allah is directly addressing you as a believer. Pay attention — a command is about to follow.',
    },
  },
  {
    orderIndex: 190,
    arabic: 'أَحَد',
    transliteration: 'Ahad',
    meaning: 'One, Anyone',
    frequency: 74,
    audioUrl: '/audio/words/ahad.mp3',
    lessonOrderIndex: 38,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Qul huwa Allahu Ahad',
      body: 'أَحَد (Ahad) means "One" or "Anyone." You recite this in Surah Al-Ikhlas — "Qul huwa Allahu Ahad" (Say: He is Allah, the One). As a Name of Allah, it emphasizes absolute oneness — unique, indivisible, unmatched.',
      quickCheckQuestion: 'Where do you recite أَحَد (Ahad) most often?',
      quickCheckOptions: ['Surah Al-Ikhlas', 'Surah Al-Fatiha', 'Surah Al-Falaq', 'Surah An-Nas'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 39: "There Is No God But Allah" ──
  {
    orderIndex: 191,
    arabic: 'إِلَه',
    transliteration: 'Ilah',
    meaning: 'God, Deity',
    frequency: 147,
    audioUrl: '/audio/words/ilah.mp3',
    lessonOrderIndex: 39,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Hidden inside the word "Allah"',
      body: 'إِلَه (Ilah) means "God" or "Deity." The word "Allah" itself is believed to come from "Al-Ilah" (The God) — with the "al" and "ilah" merging together. So when you say "La ilaha illallah," you\'re saying "there is no ilah except Al-Ilah."',
      factStat: 'إِلَه appears 147 times in the Qur\'an. The phrase "La ilaha illallah" (there is no god but Allah) is considered the most important sentence in Islam — and you already know every word in it from this app.',
    },
  },
  {
    orderIndex: 192,
    arabic: 'غَيْر',
    transliteration: 'Ghayr',
    meaning: 'Other, Besides',
    frequency: 144,
    audioUrl: '/audio/words/ghayr.mp3',
    lessonOrderIndex: 39,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Ghair-hazir — the Urdu word for absent',
      body: 'غَيْر (Ghayr) means "Other" or "Besides." In Urdu, you use "ghair" all the time — "ghair-hazir" (absent/not present), "ghair-mulki" (foreign), "ghair-zaroori" (unnecessary). In the Qur\'an, "ghairillah" means "other than Allah" — anything that is not Allah.',
    },
  },
  {
    orderIndex: 193,
    arabic: 'آخِر',
    transliteration: 'Akhir',
    meaning: 'Last, Other',
    frequency: 133,
    audioUrl: '/audio/words/akhir.mp3',
    lessonOrderIndex: 39,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Last Day — Yawm al-Akhir',
      body: 'آخِر (Akhir) means "Last" or "Other." The Qur\'an pairs it with belief in Allah: "man amana billahi wal-yawmil-akhir" (whoever believes in Allah and the Last Day). Believing in the آخِرَة (the Hereafter) is a pillar of iman.',
      ayahText: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ',
      ayahRef: 'Al-Baqarah 2:232',
    },
  },
  {
    orderIndex: 194,
    arabic: 'قَلِيل',
    transliteration: 'Qalil',
    meaning: 'Few, Little',
    frequency: 43,
    audioUrl: '/audio/words/qalil.mp3',
    lessonOrderIndex: 39,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Don\'t sell your faith for a small price',
      body: 'قَلِيل (Qalil) means "Few" or "Little." The Qur\'an warns against selling faith for "thamanan qalila" — a small, little price. The dunya, no matter how much it offers, is قَلِيل compared to what Allah has prepared. This word is a reality check whenever the world feels too tempting.',
    },
  },
  {
    orderIndex: 195,
    arabic: 'جَمِيع',
    transliteration: 'Jami\'',
    meaning: 'All, Together',
    frequency: 53,
    audioUrl: '/audio/words/jami.mp3',
    lessonOrderIndex: 39,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Jami\'a — gathering everyone together',
      body: 'جَمِيع (Jami\') means "All" or "Together." In Urdu, "jami\'" or "majmoo\'a" (collection) comes from the same root. Jumu\'ah (Friday prayer) also comes from this root — it\'s the day of gathering. The Qur\'an uses جَمِيعًا to describe how all of humanity will be gathered on the Day of Judgment.',
      quickCheckQuestion: 'What does جَمِيع (Jami\') mean?',
      quickCheckOptions: ['All, Together', 'Few, Some', 'One, Single', 'Other, Besides'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 40: "Victory and Struggle" ──
  {
    orderIndex: 196,
    arabic: 'نَصَرَ',
    transliteration: 'Nasara',
    meaning: 'to help, give victory',
    frequency: 59,
    audioUrl: '/audio/words/nasara.mp3',
    lessonOrderIndex: 40,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Nusrat — Allah\'s help in Urdu',
      body: 'نَصَرَ (Nasara) means "to help" or "to give victory." In Urdu, "nusrat" means divine help. The name "Nasir" (helper) comes from this root. When the Qur\'an promises victory, this is the root it uses. Allah\'s نَصْر always comes — the question is whether we\'re patient enough to wait for it.',
    },
  },
  {
    orderIndex: 197,
    arabic: 'فِتْنَة',
    transliteration: 'Fitnah',
    meaning: 'Trial, Temptation',
    frequency: 34,
    audioUrl: '/audio/words/fitnah.mp3',
    lessonOrderIndex: 40,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Originally means \'melting gold to test its purity\'',
      body: 'فِتْنَة (Fitnah) means "Trial" or "Temptation." You\'ve heard this word in Urdu — "fitna" means chaos or trial. In the Qur\'an, it covers everything from personal tests to societal upheaval.',
      factStat: 'The original meaning of فِتْنَة is the process of melting gold to separate pure metal from impurities. Allah "tests" believers the way a goldsmith tests gold — the trial reveals and refines what\'s real.',
    },
  },
  {
    orderIndex: 198,
    arabic: 'عَدُوّ',
    transliteration: 'Aduww',
    meaning: 'Enemy',
    frequency: 49,
    audioUrl: '/audio/words/aduww.mp3',
    lessonOrderIndex: 40,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Shaytan is your declared enemy',
      body: 'عَدُوّ (Aduww) means "Enemy." The Qur\'an makes one enmity absolutely clear — Shaytan is your عَدُوّ, so treat him as one. This isn\'t about people; it\'s about recognizing the real adversary.',
      ayahText: 'إِنَّ الشَّيْطَانَ لَكُمْ عَدُوٌّ فَاتَّخِذُوهُ عَدُوًّا',
      ayahRef: 'Fatir 35:6',
    },
  },
  {
    orderIndex: 199,
    arabic: 'نَصْر',
    transliteration: 'Nasr',
    meaning: 'Help, Victory',
    frequency: 22,
    audioUrl: '/audio/words/nasr.mp3',
    lessonOrderIndex: 40,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'When the victory of Allah comes',
      body: 'نَصْر (Nasr) means "Help" or "Victory." This is the noun form of نَصَرَ (to help/give victory). An entire surah is named after this word — Surah An-Nasr, the last surah revealed to the Prophet ﷺ. "Idha jaa\'a nasrullahi wal-fath" — when the help of Allah and the conquest comes. Victory isn\'t something you take; it\'s something Allah gives.',
    },
  },
  {
    orderIndex: 200,
    arabic: 'وَلِيّ',
    transliteration: 'Wali',
    meaning: 'Guardian, Protector',
    frequency: 86,
    audioUrl: '/audio/words/wali.mp3',
    lessonOrderIndex: 40,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Allah is the Wali of those who believe',
      body: 'وَلِيّ (Wali) means "Guardian" or "Protector." In Urdu, "wali" is used for a saint or a guardian. In the Qur\'an, Allah is described as the وَلِيّ of the believers — their protector, helper, and closest ally. "Allahu waliyyul-ladhina amanu."',
      quickCheckQuestion: 'What does وَلِيّ (Wali) mean?',
      quickCheckOptions: ['Guardian, Protector', 'Enemy, Opponent', 'Witness, Martyr', 'Judge, Ruler'],
      quickCheckAnswer: 0,
    },
  },
];
