import { IntroductionStyle } from '@prisma/client';
import { WordSeedData } from './words-types';

export const WORDS_L1_L20: WordSeedData[] = [
  // ── Lesson 1: "Words You Already Know" ──
  {
    orderIndex: 1,
    arabic: 'رَبّ',
    transliteration: 'Rabb',
    meaning: 'Lord, Sustainer',
    frequency: 975,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rabb.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'You say this in every dua',
      body: 'The word رَبّ (Rabb) means "Lord" or "Sustainer." You already use this word in Urdu every day — "Ya Rabb!" It appears 975 times in the Qur\'an, making it one of the most frequent words.',
    },
  },
  {
    orderIndex: 2,
    arabic: 'رَحْمَة',
    transliteration: 'Rahmah',
    meaning: 'Mercy',
    frequency: 339,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rahmah.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The root of Bismillah',
      body: 'رَحْمَة (Rahmah) means "Mercy." You hear it every time you say "Bismillah ir-Rahman ir-Raheem." Let\'s see where it appears in the Qur\'an.',
      ayahText: 'وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ',
      ayahRef: 'Al-A\'raf 7:156',
    },
  },
  {
    orderIndex: 3,
    arabic: 'عِلْم',
    transliteration: 'Ilm',
    meaning: 'Knowledge',
    frequency: 382,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ilm.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s favorite topic',
      body: 'عِلْم (Ilm) means "Knowledge." You already use this word in Urdu all the time.',
      factStat: 'The word "Ilm" and its derivatives appear 780+ times in the Qur\'an. No other book in history emphasizes knowledge this much.',
    },
  },
  {
    orderIndex: 4,
    arabic: 'صَبْر',
    transliteration: 'Sabr',
    meaning: 'Patience',
    frequency: 103,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sabr.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'You already know this one',
      body: 'صَبْر (Sabr) — you definitely know this one from Urdu. But do you know what it means in Arabic?',
      quickCheckQuestion: 'What does صَبْر (Sabr) mean?',
      quickCheckOptions: ['Patience', 'Speed', 'Strength', 'Wisdom'],
      quickCheckAnswer: 0,
    },
  },
  {
    orderIndex: 5,
    arabic: 'هُدَى',
    transliteration: 'Huda',
    meaning: 'Guidance',
    frequency: 144,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/huda.mp3',
    lessonOrderIndex: 1,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Hidden in your daily prayer',
      body: 'هُدَى (Huda) means "Guidance." You say this in every prayer when you recite Al-Fatiha: "Ihdinas-siratal-mustaqeem" — "Guide us to the straight path." The word هُدَى is at the heart of that dua.',
    },
  },

  // ── Lesson 2: "The Foundations" ──
  {
    orderIndex: 6,
    arabic: 'اللَّه',
    transliteration: 'Allah',
    meaning: 'God',
    frequency: 2699,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/allah.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The most frequent word',
      body: 'اللَّه (Allah) — the name of God. The most sacred and most frequently used noun in the entire Qur\'an.',
      factStat: 'Allah appears 2,699 times in the Qur\'an — more than any other noun. That\'s an average of 23 times per surah.',
    },
  },
  {
    orderIndex: 7,
    arabic: 'كِتَاب',
    transliteration: 'Kitab',
    meaning: 'Book',
    frequency: 260,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kitab.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Same word, same meaning',
      body: 'كِتَاب (Kitab) means "Book." This is exactly the same word you use in Urdu. When Allah refers to the Qur\'an, He often calls it "Al-Kitab" — The Book.',
    },
  },
  {
    orderIndex: 8,
    arabic: 'آيَة',
    transliteration: 'Ayah',
    meaning: 'Sign, Verse',
    frequency: 382,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ayah.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'More than just a verse',
      body: 'آيَة (Ayah) means "Sign" or "Verse." Every verse of the Qur\'an is called an Ayah because each one is a sign from Allah.',
      ayahText: 'إِنَّ فِي ذَٰلِكَ لَآيَاتٍ لِّقَوْمٍ يَتَفَكَّرُونَ',
      ayahRef: 'Ar-Ra\'d 13:3',
    },
  },
  {
    orderIndex: 9,
    arabic: 'رَسُول',
    transliteration: 'Rasool',
    meaning: 'Messenger',
    frequency: 332,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rasool.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'In your Shahada, daily',
      body: 'رَسُول (Rasool) means "Messenger." You say this word multiple times every day in the Shahada and in Durood: "Muhammad ur Rasool Allah" — Muhammad is the Messenger of Allah.',
    },
  },
  {
    orderIndex: 10,
    arabic: 'حَقّ',
    transliteration: 'Haqq',
    meaning: 'Truth',
    frequency: 242,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/haqq.mp3',
    lessonOrderIndex: 2,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'One of Allah\'s names',
      body: 'حَقّ (Haqq) — you\'ve heard this many times. "Al-Haqq" is also one of Allah\'s names.',
      quickCheckQuestion: 'What does حَقّ (Haqq) mean?',
      quickCheckOptions: ['Truth', 'Peace', 'Book', 'Light'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 3: "Your World" ──
  {
    orderIndex: 11,
    arabic: 'أَرْض',
    transliteration: 'Ard',
    meaning: 'Earth',
    frequency: 461,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ard.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The other half of creation',
      body: 'أَرْض (Ard) means "Earth" or "Land." The Qur\'an often pairs this word with سَمَاء (sky) to describe the entire creation.',
      factStat: '"Earth" appears 461 times in the Qur\'an — almost always paired with "sky" to represent all of creation.',
    },
  },
  {
    orderIndex: 12,
    arabic: 'سَمَاء',
    transliteration: 'Sama',
    meaning: 'Sky, Heaven',
    frequency: 310,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sama.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Look up',
      body: 'سَمَاء (Sama) means "Sky" or "Heaven." In the Qur\'an, Allah often draws our attention upward.',
      ayahText: 'أَفَلَمْ يَنظُرُوا إِلَى السَّمَاءِ فَوْقَهُمْ كَيْفَ بَنَيْنَاهَا',
      ayahRef: 'Qaf 50:6',
    },
  },
  {
    orderIndex: 13,
    arabic: 'نَفْس',
    transliteration: 'Nafs',
    meaning: 'Self, Soul',
    frequency: 295,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nafs.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The Urdu word for \'nafs\'',
      body: 'نَفْس (Nafs) means "Self" or "Soul." In Urdu you say "nafs par qabu rakho" (control yourself). The Qur\'an talks about three types of nafs — the commanding self, the self-reproaching self, and the peaceful self.',
    },
  },
  {
    orderIndex: 14,
    arabic: 'نُور',
    transliteration: 'Noor',
    meaning: 'Light',
    frequency: 194,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/noor.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A name you definitely know',
      body: 'نُور (Noor) means "Light." This is probably a name you know — many people are named Noor. There\'s an entire surah called An-Noor (The Light). When people say someone has "noor on their face," they\'re using this Qur\'anic word.',
    },
  },
  {
    orderIndex: 15,
    arabic: 'حَيَاة',
    transliteration: 'Hayat',
    meaning: 'Life',
    frequency: 190,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hayat.mp3',
    lessonOrderIndex: 3,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'A word from everyday Urdu',
      body: 'حَيَاة (Hayat) — a beautiful word you use in Urdu too.',
      quickCheckQuestion: 'What does حَيَاة (Hayat) mean?',
      quickCheckOptions: ['Life', 'Death', 'Time', 'World'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 4: "Actions That Matter" ──
  {
    orderIndex: 16,
    arabic: 'عَلِمَ',
    transliteration: 'Alima',
    meaning: 'to know',
    frequency: 382,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/alima.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'You already know the root!',
      body: 'عَلِمَ (Alima) means "to know." Remember عِلْم (Ilm) from Lesson 1? Same root! Arabic builds families of meaning from roots. عِلْم = knowledge, عَلِمَ = to know, عَالِم = scholar. You already know all these from Urdu.',
    },
  },
  {
    orderIndex: 17,
    arabic: 'عَمِلَ',
    transliteration: 'Amila',
    meaning: 'to do, to work',
    frequency: 276,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/amila.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Qur\'an\'s favorite phrase',
      body: 'عَمِلَ (Amila) means "to do" or "to work." The phrase "alladhina aamanu wa amilus-salihaat" (those who believe and do good deeds) appears dozens of times in the Qur\'an.',
      ayahText: 'إِنَّ الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ',
      ayahRef: 'Al-Baqarah 2:277',
    },
  },
  {
    orderIndex: 18,
    arabic: 'خَلَقَ',
    transliteration: 'Khalaqa',
    meaning: 'to create',
    frequency: 184,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/khalaqa.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Did you know?',
      body: 'خَلَقَ (Khalaqa) means "to create." Al-Khaliq (The Creator) is one of Allah\'s 99 names.',
      factStat: 'The very first word revealed to Prophet Muhammad \uFDFA was "Iqra" (Read), and in those first verses, خَلَقَ appears: "Who created man from a clinging substance."',
    },
  },
  {
    orderIndex: 19,
    arabic: 'هَدَى',
    transliteration: 'Hada',
    meaning: 'to guide',
    frequency: 144,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hada.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this in every prayer!',
      body: 'هَدَى (Hada) means "to guide." Remember هُدَى (Huda/guidance) from Lesson 1? Same root! In Al-Fatiha, you ask "Ihdina" (guide us) — that\'s this very verb. Every time you pray, you\'re using this word.',
    },
  },
  {
    orderIndex: 20,
    arabic: 'سَمِعَ',
    transliteration: 'Sami\'a',
    meaning: 'to hear',
    frequency: 78,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/samia.mp3',
    lessonOrderIndex: 4,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'From As-Sami\' to the verb',
      body: 'سَمِعَ (Sami\'a) — As-Sami\' (The All-Hearing) is one of Allah\'s names. What does this verb mean?',
      quickCheckQuestion: 'What does سَمِعَ (Sami\'a) mean?',
      quickCheckOptions: ['to hear', 'to see', 'to speak', 'to know'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 5: "Rewards and Consequences" ──
  {
    orderIndex: 21,
    arabic: 'جَنَّة',
    transliteration: 'Jannah',
    meaning: 'Paradise, Garden',
    frequency: 147,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/jannah.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Your Urdu word for Paradise',
      body: 'جَنَّة (Jannah) means "Paradise" or "Garden." You know this word from Urdu — "Jannat." The literal meaning is "garden," and the Qur\'an describes it as gardens with rivers flowing beneath.',
    },
  },
  {
    orderIndex: 22,
    arabic: 'نَار',
    transliteration: 'Nar',
    meaning: 'Fire, Hell',
    frequency: 145,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nar.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Qur\'an\'s warning',
      body: 'نَار (Nar) means "Fire" — referring to the Hellfire. In the Qur\'an, Jannah and Nar are often mentioned together as the two ultimate destinations.',
      ayahText: 'فَاتَّقُوا النَّارَ الَّتِي وَقُودُهَا النَّاسُ وَالْحِجَارَةُ',
      ayahRef: 'Al-Baqarah 2:24',
    },
  },
  {
    orderIndex: 23,
    arabic: 'أَجْر',
    transliteration: 'Ajr',
    meaning: 'Reward',
    frequency: 105,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ajr.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A word you hear in khutbahs',
      body: 'أَجْر (Ajr) means "Reward." You hear this constantly in Islamic talks: "Allah will give you ajr for this." In the Qur\'an, believers are promised "ajr azeem" — a great reward.',
    },
  },
  {
    orderIndex: 24,
    arabic: 'عَذَاب',
    transliteration: 'Adhab',
    meaning: 'Punishment',
    frequency: 322,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/adhab.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'A word with weight',
      body: 'عَذَاب (Adhab) means "Punishment" — you know it as "azaab" in Urdu.',
      factStat: '"Adhab" appears 322 times in the Qur\'an. It\'s almost always followed by a qualifier: "adhab aleem" (painful), "adhab shadeed" (severe), or "adhab al-nar" (punishment of fire).',
    },
  },
  {
    orderIndex: 25,
    arabic: 'مَغْفِرَة',
    transliteration: 'Maghfirah',
    meaning: 'Forgiveness',
    frequency: 127,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/maghfirah.mp3',
    lessonOrderIndex: 5,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Think "Astaghfirullah"',
      body: 'مَغْفِرَة (Maghfirah) — "Astaghfirullah" (I seek Allah\'s forgiveness) comes from the same root.',
      quickCheckQuestion: 'What does مَغْفِرَة (Maghfirah) mean?',
      quickCheckOptions: ['Forgiveness', 'Punishment', 'Patience', 'Mercy'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 6: "Faith and Belief" ──
  {
    orderIndex: 26,
    arabic: 'آمَنَ',
    transliteration: 'Aamana',
    meaning: 'to believe',
    frequency: 537,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aamana.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The most important verb',
      body: 'آمَنَ (Aamana) means "to believe." The root gives us "Iman" (faith), "Mu\'min" (believer), and "Ameen" (trustworthy).',
      factStat: '"Aamana" and its forms appear 537 times — making "belief" one of the most repeated concepts in the Qur\'an.',
    },
  },
  {
    orderIndex: 27,
    arabic: 'إيمَان',
    transliteration: 'Iman',
    meaning: 'Faith',
    frequency: 45,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/iman.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The word that defines you',
      body: 'إيمَان (Iman) means "Faith." You know this word deeply from Urdu — "iman" is at the core of Muslim identity. It comes from the same root as آمَنَ (to believe) that you just learned. Iman isn\'t just belief — it\'s trust, conviction, and security all in one word.',
    },
  },
  {
    orderIndex: 28,
    arabic: 'مُؤْمِن',
    transliteration: 'Mu\'min',
    meaning: 'Believer',
    frequency: 195,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/mumin.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your identity as a Muslim',
      body: 'مُؤْمِن (Mu\'min) means "Believer." This comes from the same root as آمَنَ (to believe) that you just learned. In Urdu, "Momin" is both a name and a title for a person of faith. Al-Mu\'min is also one of Allah\'s names — The Guardian of Faith.',
    },
  },
  {
    orderIndex: 29,
    arabic: 'كَفَرَ',
    transliteration: 'Kafara',
    meaning: 'to cover/disbelieve',
    frequency: 289,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kafara.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'See the contrast in the Qur\'an',
      body: 'كَفَرَ (Kafara) literally means "to cover" — as in covering the truth. The Qur\'an uses it for denial or disbelief, and often pairs آمَنَ (to believe) with كَفَرَ (to disbelieve) to show the two paths.',
      ayahText: 'هُوَ الَّذِي خَلَقَكُمْ فَمِنكُمْ كَافِرٌ وَمِنكُم مُّؤْمِنٌ',
      ayahRef: 'At-Taghabun 64:2',
    },
  },
  {
    orderIndex: 30,
    arabic: 'عَبَدَ',
    transliteration: 'Abada',
    meaning: 'to worship',
    frequency: 122,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/abada.mp3',
    lessonOrderIndex: 6,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The purpose of existence',
      body: 'عَبَدَ (Abada) means "to worship." The word "ibadat" in Urdu comes from this root. Allah says: "I did not create jinn and mankind except to worship Me."',
      quickCheckQuestion: 'What does عَبَدَ (Abada) mean?',
      quickCheckOptions: ['to worship', 'to create', 'to believe', 'to know'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 7: "The People of the Qur'an" ──
  {
    orderIndex: 31,
    arabic: 'قَوْم',
    transliteration: 'Qawm',
    meaning: 'People, Nation',
    frequency: 383,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qawm.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A word from Pakistan\'s story',
      body: 'قَوْم (Qawm) means "People" or "Nation." Identical to the Urdu word "qaum." In the Qur\'an, prophets are always sent to their qawm — "Ya qawmi!" (O my people!) is a phrase you\'ll see repeatedly.',
    },
  },
  {
    orderIndex: 32,
    arabic: 'نَاس',
    transliteration: 'Nas',
    meaning: 'Mankind',
    frequency: 241,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nas.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A surah you already know!',
      body: 'نَاس (Nas) means "Mankind" or "People." You already know this from Surah An-Nas, which you may have memorized: "Qul a\'udhu bi Rabbin-Nas" — "Say: I seek refuge in the Lord of mankind."',
    },
  },
  {
    orderIndex: 33,
    arabic: 'عَبْد',
    transliteration: 'Abd',
    meaning: 'Servant',
    frequency: 275,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/abd.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The highest title',
      body: 'عَبْد (Abd) means "Servant." Abdullah (servant of Allah) is one of the most common Muslim names. The Qur\'an calls Prophet Muhammad \uFDFA "Abduhu" (His servant).',
      ayahText: 'سُبْحَانَ الَّذِي أَسْرَىٰ بِعَبْدِهِ لَيْلًا',
      ayahRef: 'Al-Isra 17:1',
    },
  },
  {
    orderIndex: 34,
    arabic: 'ظَالِم',
    transliteration: 'Zalim',
    meaning: 'Oppressor',
    frequency: 110,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/zalim.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'A word with layers',
      body: 'ظَالِم (Zalim) means "Oppressor" or "Wrongdoer." You know this word from Urdu.',
      factStat: 'In Arabic, "zulm" literally means "to put something in the wrong place." So a zalim isn\'t just cruel — they\'re someone who puts things where they don\'t belong, including denying Allah\'s rights.',
    },
  },
  {
    orderIndex: 35,
    arabic: 'نَبِيّ',
    transliteration: 'Nabi',
    meaning: 'Prophet',
    frequency: 75,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nabi.mp3',
    lessonOrderIndex: 7,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Every Muslim knows this',
      body: 'نَبِيّ (Nabi) — a word every Muslim knows.',
      quickCheckQuestion: 'What does نَبِيّ (Nabi) mean?',
      quickCheckOptions: ['Prophet', 'King', 'Scholar', 'Angel'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 8: "Your Daily Worship" ──
  {
    orderIndex: 36,
    arabic: 'صَلَاة',
    transliteration: 'Salah',
    meaning: 'Prayer',
    frequency: 99,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/salah.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your 5 daily connection',
      body: 'صَلَاة (Salah) means "Prayer." You know this as namaz. In the Qur\'an, Allah uses the beautiful word Salah. Every time the Qur\'an commands prayer, it uses this word. You perform salah 5 times a day — now you know the word Allah uses for it.',
    },
  },
  {
    orderIndex: 37,
    arabic: 'شُكْر',
    transliteration: 'Shukr',
    meaning: 'Gratitude',
    frequency: 75,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shukr.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'You say this every day!',
      body: 'شُكْر (Shukr) means "Gratitude." Every time you say "shukriya" in Urdu, you\'re using this Arabic root. Ash-Shakoor (The Most Grateful) is one of Allah\'s names.',
    },
  },
  {
    orderIndex: 38,
    arabic: 'رِزْق',
    transliteration: 'Rizq',
    meaning: 'Provision',
    frequency: 123,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rizq.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'More than just money',
      body: 'رِزْق (Rizq) means "Provision" or "Sustenance." Not just food — it includes wealth, health, children, knowledge. Everything Allah provides.',
      ayahText: 'إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ',
      ayahRef: 'Adh-Dhariyat 51:58',
    },
  },
  {
    orderIndex: 39,
    arabic: 'نِعْمَة',
    transliteration: 'Ni\'mah',
    meaning: 'Blessing',
    frequency: 144,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nimah.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Count your blessings',
      body: 'نِعْمَة (Ni\'mah) means "Blessing" or "Favor." In Urdu, "naimat" carries the same meaning.',
      factStat: 'Allah challenges us: "If you tried to count Allah\'s blessings, you could never enumerate them" (Ibrahim 14:34). The word ni\'mah appears 144 times, reminding us constantly.',
    },
  },
  {
    orderIndex: 40,
    arabic: 'حِكْمَة',
    transliteration: 'Hikmah',
    meaning: 'Wisdom',
    frequency: 39,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hikmah.mp3',
    lessonOrderIndex: 8,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'From Al-Hakeem\'s root',
      body: 'حِكْمَة (Hikmah) — Al-Hakeem (The All-Wise) is one of Allah\'s names, from this same root.',
      quickCheckQuestion: 'What does حِكْمَة (Hikmah) mean?',
      quickCheckOptions: ['Wisdom', 'Power', 'Beauty', 'Justice'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 9: "Powerful Verbs" ──
  {
    orderIndex: 41,
    arabic: 'قَالَ',
    transliteration: 'Qala',
    meaning: 'to say',
    frequency: 1618,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qala.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The #1 verb in the Qur\'an',
      body: 'قَالَ (Qala) means "to say" or "he said." This is the single most frequent verb in the entire Qur\'an.',
      factStat: '"Qala" appears 1,618 times — because the Qur\'an is full of dialogue. Allah speaks, prophets speak, angels speak, and even the disbelievers speak. When you see قَالَ, a conversation is happening.',
    },
  },
  {
    orderIndex: 42,
    arabic: 'دَعَا',
    transliteration: 'Da\'a',
    meaning: 'to call, to pray',
    frequency: 170,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/daa.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Every dua starts here',
      body: 'دَعَا (Da\'a) means "to call" or "to pray/supplicate." This is the root of "dua" — your personal prayers to Allah. Every time you make dua, you\'re using this verb.',
    },
  },
  {
    orderIndex: 43,
    arabic: 'غَفَرَ',
    transliteration: 'Ghafara',
    meaning: 'to forgive',
    frequency: 65,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ghafara.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A word you use daily',
      body: 'غَفَرَ (Ghafara) means "to forgive." Remember مَغْفِرَة (Maghfirah/forgiveness) from Lesson 5? Same root! And "Astaghfirullah" (I seek Allah\'s forgiveness) — you\'re using this verb every time you say it. Al-Ghafoor (The Most Forgiving) is one of Allah\'s most frequently mentioned names.',
    },
  },
  {
    orderIndex: 44,
    arabic: 'ذَكَرَ',
    transliteration: 'Dhakara',
    meaning: 'to remember, to mention',
    frequency: 84,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dhakara.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Allah\'s beautiful promise',
      body: 'ذَكَرَ (Dhakara) means "to remember" or "to mention." "Zikr" (remembrance of Allah) comes from this root.',
      ayahText: 'فَاذْكُرُونِي أَذْكُرْكُمْ',
      ayahRef: 'Al-Baqarah 2:152',
    },
  },
  {
    orderIndex: 45,
    arabic: 'ظَلَمَ',
    transliteration: 'Zalama',
    meaning: 'to oppress, to wrong',
    frequency: 110,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/zalama.mp3',
    lessonOrderIndex: 9,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Remember Zalim?',
      body: 'ظَلَمَ (Zalama) — remember ظَالِم (Zalim/oppressor) from Lesson 7? This is the verb form.',
      quickCheckQuestion: 'What does ظَلَمَ (Zalama) mean?',
      quickCheckOptions: ['to oppress / to wrong', 'to forgive', 'to create', 'to believe'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 10: "The Journey" ──
  {
    orderIndex: 46,
    arabic: 'سَبِيل',
    transliteration: 'Sabeel',
    meaning: 'Path, Way',
    frequency: 176,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sabeel.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'A phrase you know by heart',
      body: 'سَبِيل (Sabeel) means "Path" or "Way." You know the phrase "fi sabeel illah" (in the path of Allah). The Qur\'an constantly talks about the "sabeel of Allah" — and now you can recognize it every time.',
    },
  },
  {
    orderIndex: 47,
    arabic: 'صِرَاط',
    transliteration: 'Sirat',
    meaning: 'Straight Path',
    frequency: 45,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sirat.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'You say this 17 times a day!',
      body: 'صِرَاط (Sirat) means "Path." You say "Ihdinas-sirat-al-mustaqeem" (Guide us to the straight path) in every rak\'ah of every prayer. If you pray all 5 prayers, you say this word at least 17 times a day.',
    },
  },
  {
    orderIndex: 48,
    arabic: 'يَوْم',
    transliteration: 'Yawm',
    meaning: 'Day',
    frequency: 325,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/yawm.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'In your Al-Fatiha',
      body: 'يَوْم (Yawm) means "Day." You know it from "Yawm al-Qiyamah" (Day of Judgment) and from Al-Fatiha: "Maliki Yawm id-Deen" (Master of the Day of Judgment).',
      ayahText: 'مَالِكِ يَوْمِ الدِّينِ',
      ayahRef: 'Al-Fatiha 1:4',
    },
  },
  {
    orderIndex: 49,
    arabic: 'أَمْر',
    transliteration: 'Amr',
    meaning: 'Command, Matter',
    frequency: 166,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/amr.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'One word, big meaning',
      body: 'أَمْر (Amr) means "Command" or "Matter/Affair." When Allah decides something, He says "kun" (be) — and that is His amr.',
      factStat: '"Amr" appears 166 times. It can mean Allah\'s command, a matter/affair, or an order. Context determines the meaning — this is how Arabic works: one word, many shades.',
    },
  },
  {
    orderIndex: 50,
    arabic: 'مَوْت',
    transliteration: 'Mawt',
    meaning: 'Death',
    frequency: 165,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/mawt.mp3',
    lessonOrderIndex: 10,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'You know this one',
      body: 'مَوْت (Mawt) means "Death." You know this as "maut" in Urdu. The Qur\'an reminds us: every soul will taste death.',
      quickCheckQuestion: 'What does مَوْت (Mawt) mean?',
      quickCheckOptions: ['Death', 'Life', 'Time', 'Return'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 11: "What Comes Next" ──
  {
    orderIndex: 51,
    arabic: 'دُنْيَا',
    transliteration: 'Dunya',
    meaning: 'Worldly Life',
    frequency: 115,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dunya.mp3',
    lessonOrderIndex: 11,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'The word everyone warns you about',
      body: 'دُنْيَا (Dunya) means "Worldly Life." In Urdu, you hear "dunya ki mohabbat" (love of the world) all the time. In Arabic, dunya literally means "the lower/nearer thing" — a built-in reminder that this life is temporary.',
    },
  },
  {
    orderIndex: 52,
    arabic: 'آخِرَة',
    transliteration: 'Akhirah',
    meaning: 'Hereafter',
    frequency: 115,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/akhirah.mp3',
    lessonOrderIndex: 11,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Qur\'an\'s constant reminder',
      body: 'آخِرَة (Akhirah) means "The Hereafter." The Qur\'an always pairs Dunya with Akhirah — this life and the next. It appears 115 times, exactly as often as Dunya.',
      ayahText: 'وَمَا الْحَيَاةُ الدُّنْيَا إِلَّا مَتَاعُ الْغُرُورِ',
      ayahRef: 'Al-Hadid 57:20',
    },
  },
  {
    orderIndex: 53,
    arabic: 'قِيَامَة',
    transliteration: 'Qiyamah',
    meaning: 'Resurrection',
    frequency: 70,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qiyamah.mp3',
    lessonOrderIndex: 11,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Yawm al-Qiyamah — you know this phrase',
      body: 'قِيَامَة (Qiyamah) means "Resurrection" or "The Rising." You\'ve heard "Yawm al-Qiyamah" (the Day of Resurrection) countless times in khutbahs and Islamic talks. The root means "to stand up" — the day when all of creation will rise and stand before Allah.',
    },
  },
  {
    orderIndex: 54,
    arabic: 'حِسَاب',
    transliteration: 'Hisab',
    meaning: 'Reckoning',
    frequency: 39,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/hisab.mp3',
    lessonOrderIndex: 11,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Math meets the hereafter',
      body: 'حِسَاب (Hisab) means "Reckoning" or "Account." In Urdu, "hisab" means math or calculation — same word!',
      factStat: 'The Qur\'an uses the same word for mathematical calculation and divine reckoning. On the Day of Judgment, everyone receives their "hisab" — their account of deeds, calculated to the finest detail.',
    },
  },
  {
    orderIndex: 55,
    arabic: 'جَزَاء',
    transliteration: 'Jaza\'',
    meaning: 'Recompense',
    frequency: 43,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/jaza.mp3',
    lessonOrderIndex: 11,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'What goes around comes around',
      body: 'جَزَاء (Jaza\') — you hear "JazakAllah" (may Allah reward you) regularly. This is the root word behind that beautiful phrase.',
      quickCheckQuestion: 'What does جَزَاء (Jaza\') mean?',
      quickCheckOptions: ['Recompense / Reward', 'Punishment only', 'Forgiveness', 'Prayer'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 12: "Heart and Mind" ──
  {
    orderIndex: 56,
    arabic: 'قَلْب',
    transliteration: 'Qalb',
    meaning: 'Heart',
    frequency: 132,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qalb.mp3',
    lessonOrderIndex: 12,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Not just a body part',
      body: 'قَلْب (Qalb) means "Heart" — the same word as in Urdu. But in the Qur\'an, qalb isn\'t just the organ that pumps blood. It\'s the seat of understanding, faith, and intention. When the Qur\'an talks about "sealed hearts," it means hearts that refuse to understand.',
    },
  },
  {
    orderIndex: 57,
    arabic: 'رُوح',
    transliteration: 'Ruh',
    meaning: 'Spirit, Soul',
    frequency: 57,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ruh.mp3',
    lessonOrderIndex: 12,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'A mystery even the Qur\'an keeps',
      body: 'رُوح (Ruh) means "Spirit" or "Soul." You know "rooh" from Urdu — the soul, the essence of life.',
      factStat: 'When the Prophet \uFDFA was asked about the Ruh, Allah revealed: "They ask you about the spirit. Say: the spirit is from the command of my Lord, and you have been given only a little knowledge" (Al-Isra 17:85). Even the Qur\'an keeps this word mysterious.',
    },
  },
  {
    orderIndex: 58,
    arabic: 'بَصَر',
    transliteration: 'Basar',
    meaning: 'Sight, Vision',
    frequency: 148,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/basar.mp3',
    lessonOrderIndex: 12,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Seeing beyond the surface',
      body: 'بَصَر (Basar) means "Sight" or "Vision." Al-Basir (The All-Seeing) is one of Allah\'s names. The Qur\'an uses basar for both physical sight and spiritual insight.',
      ayahText: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
      ayahRef: 'Ar-Ra\'d 13:28',
    },
  },
  {
    orderIndex: 59,
    arabic: 'عَقْل',
    transliteration: 'Aql',
    meaning: 'Reason, Intellect',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/aql.mp3',
    lessonOrderIndex: 12,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'The Qur\'an values your mind',
      body: 'عَقْل (Aql) means "Reason" or "Intellect." In Urdu, you say "aqal se kaam lo" (use your brain). The Qur\'an repeatedly asks "afala ta\'qiloon?" — "Will you not use your reason?" Allah wants you to think, not just follow blindly.',
    },
  },
  {
    orderIndex: 60,
    arabic: 'صَدْر',
    transliteration: 'Sadr',
    meaning: 'Chest, Breast',
    frequency: 44,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sadr.mp3',
    lessonOrderIndex: 12,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Where feelings live',
      body: 'صَدْر (Sadr) — in Urdu, "seena" is more common, but "sadr" appears in phrases like "sadr-e-mushaf." In the Qur\'an, the sadr is where emotions, doubts, and faith reside.',
      quickCheckQuestion: 'What does صَدْر (Sadr) mean in the Qur\'an?',
      quickCheckOptions: ['Chest / Breast', 'Head', 'Hand', 'Back'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 13: "Coming and Going" ──
  {
    orderIndex: 61,
    arabic: 'جَاءَ',
    transliteration: 'Ja\'a',
    meaning: 'to come',
    frequency: 278,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/jaaa.mp3',
    lessonOrderIndex: 13,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The Qur\'an\'s way of saying "it arrived"',
      body: 'جَاءَ (Ja\'a) means "to come." It\'s used for everything from prophets arriving to the Day of Judgment itself.',
      factStat: '"Ja\'a" appears 278 times. The Qur\'an opens Surah An-Nasr with this very word: "When the help of Allah comes" — إِذَا جَاءَ نَصْرُ اللَّهِ. One word, enormous weight.',
    },
  },
  {
    orderIndex: 62,
    arabic: 'دَخَلَ',
    transliteration: 'Dakhala',
    meaning: 'to enter',
    frequency: 76,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/dakhala.mp3',
    lessonOrderIndex: 13,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Dakhl — interference or entry',
      body: 'دَخَلَ (Dakhala) means "to enter." In Urdu, "dakhl" means interference or involvement — entering into someone\'s affairs. In the Qur\'an, it\'s used for entering Jannah, entering Islam, and entering homes. The most beautiful use: "Enter among My righteous servants."',
    },
  },
  {
    orderIndex: 63,
    arabic: 'خَرَجَ',
    transliteration: 'Kharaja',
    meaning: 'to go out',
    frequency: 53,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kharaja.mp3',
    lessonOrderIndex: 13,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The opposite of entering',
      body: 'خَرَجَ (Kharaja) means "to go out" or "to emerge." The Qur\'an pairs دَخَلَ (to enter) with خَرَجَ (to exit) just like it pairs other opposites. Allah brings the living out of the dead and the dead out of the living.',
      ayahText: 'إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ',
      ayahRef: 'An-Nasr 110:1',
    },
  },
  {
    orderIndex: 64,
    arabic: 'رَجَعَ',
    transliteration: 'Raja\'a',
    meaning: 'to return',
    frequency: 79,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/rajaa.mp3',
    lessonOrderIndex: 13,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Inna lillahi wa inna ilayhi raji\'oon',
      body: 'رَجَعَ (Raja\'a) means "to return." You know this word from the phrase you say when someone passes away: "Indeed, to Allah we belong and to Him we shall return." The word "raji\'oon" (those who return) comes from this verb.',
    },
  },
  {
    orderIndex: 65,
    arabic: 'اتَّبَعَ',
    transliteration: 'Ittaba\'a',
    meaning: 'to follow',
    frequency: 136,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ittabaa.mp3',
    lessonOrderIndex: 13,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Leaders and followers',
      body: 'اتَّبَعَ (Ittaba\'a) — the Qur\'an talks a lot about who we follow. Following guidance or following desires — it\'s a central theme.',
      quickCheckQuestion: 'What does اتَّبَعَ (Ittaba\'a) mean?',
      quickCheckOptions: ['to follow', 'to lead', 'to leave', 'to enter'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 14: "Good and Evil" ──
  {
    orderIndex: 66,
    arabic: 'خَيْر',
    transliteration: 'Khayr',
    meaning: 'Good',
    frequency: 176,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/khayr.mp3',
    lessonOrderIndex: 14,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Khair mubarak!',
      body: 'خَيْر (Khayr) means "Good." You use this word all the time in Urdu — "khayr hai" (it\'s all good), "khairaat" (charity), "khair mubarak." In the Qur\'an, Allah promises that whoever does an atom\'s weight of khayr will see it.',
    },
  },
  {
    orderIndex: 67,
    arabic: 'شَرّ',
    transliteration: 'Sharr',
    meaning: 'Evil',
    frequency: 98,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sharr.mp3',
    lessonOrderIndex: 14,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The pair that decides everything',
      body: 'شَرّ (Sharr) means "Evil." The Qur\'an places khayr and sharr side by side in one of the most powerful passages — every atom of good and evil will be seen.',
      ayahText: 'فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ',
      ayahRef: 'Az-Zalzalah 99:7',
    },
  },
  {
    orderIndex: 68,
    arabic: 'صَالِح',
    transliteration: 'Salih',
    meaning: 'Righteous',
    frequency: 62,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/salih.mp3',
    lessonOrderIndex: 14,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'A name and a prayer',
      body: 'صَالِح (Salih) means "Righteous." This is both a prophet\'s name and the word every parent uses when praying for their children — "Ya Allah, make them salih." When the Qur\'an says "amilus-salihaat" (do righteous deeds), it\'s using this word.',
    },
  },
  {
    orderIndex: 69,
    arabic: 'عَظِيم',
    transliteration: 'Azeem',
    meaning: 'Great, Mighty',
    frequency: 104,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/azeem.mp3',
    lessonOrderIndex: 14,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The biggest adjective in the Qur\'an',
      body: 'عَظِيم (Azeem) means "Great" or "Mighty." You know "Al-Azeem" from "Subhana Rabbi al-Azeem" in ruku.',
      factStat: '"Azeem" appears 104 times. It describes Allah\'s throne (arsh azeem), His reward (ajr azeem), His punishment (adhab azeem), and even a great day (yawm azeem). When the Qur\'an calls something "azeem," pay attention.',
    },
  },
  {
    orderIndex: 70,
    arabic: 'كَبِير',
    transliteration: 'Kabir',
    meaning: 'Great, Big',
    frequency: 32,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kabir.mp3',
    lessonOrderIndex: 14,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Allahu Akbar — you already know this root',
      body: 'كَبِير (Kabir) — "Akbar" comes from the same root. Every time you say "Allahu Akbar," you\'re using a form of this word.',
      quickCheckQuestion: 'What does كَبِير (Kabir) mean?',
      quickCheckOptions: ['Great / Big', 'Small', 'Fast', 'Old'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 15: "Day and Night" ──
  {
    orderIndex: 71,
    arabic: 'لَيْل',
    transliteration: 'Layl',
    meaning: 'Night',
    frequency: 92,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/layl.mp3',
    lessonOrderIndex: 15,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'The most spiritual time',
      body: 'لَيْل (Layl) means "Night." There\'s an entire surah called Al-Layl (The Night).',
      factStat: 'The Qur\'an mentions night 92 times and often describes it as a time for rest, reflection, and special worship. The most powerful night in Islam — Laylat al-Qadr — uses this very word. Night prayer (tahajjud) is considered the closest you can get to Allah.',
    },
  },
  {
    orderIndex: 72,
    arabic: 'نَهَار',
    transliteration: 'Nahar',
    meaning: 'Daytime',
    frequency: 57,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/nahar.mp3',
    lessonOrderIndex: 15,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'The Qur\'an\'s day-night pair',
      body: 'نَهَار (Nahar) means "Daytime." Just like Jannah and Nar, the Qur\'an pairs layl (night) and nahar (day) as signs of Allah\'s creation. The alternation of day and night is presented as evidence of Allah\'s power.',
      ayahText: 'إِنَّ فِي خَلْقِ السَّمَاوَاتِ وَالْأَرْضِ وَاخْتِلَافِ اللَّيْلِ وَالنَّهَارِ لَآيَاتٍ',
      ayahRef: 'Al-Imran 3:190',
    },
  },
  {
    orderIndex: 73,
    arabic: 'شَمْس',
    transliteration: 'Shams',
    meaning: 'Sun',
    frequency: 33,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shams.mp3',
    lessonOrderIndex: 15,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Shamsi and Qamari — you know this pair',
      body: 'شَمْس (Shams) means "Sun." In Urdu, "shamsi" means solar — shamsi calendar, shamsi saal. There\'s a beautiful surah called Ash-Shams (The Sun) that begins with an oath by the sun and its brightness.',
    },
  },
  {
    orderIndex: 74,
    arabic: 'قَمَر',
    transliteration: 'Qamar',
    meaning: 'Moon',
    frequency: 27,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/qamar.mp3',
    lessonOrderIndex: 15,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'How you track Ramadan',
      body: 'قَمَر (Qamar) means "Moon." There\'s Surah Al-Qamar (The Moon) in the Qur\'an. The moon is deeply embedded in Islamic life — the lunar (qamari) calendar determines Ramadan, Eid, and Hajj. Every time you look for the new moon, you\'re connected to this word.',
    },
  },
  {
    orderIndex: 75,
    arabic: 'مَاء',
    transliteration: 'Ma\'',
    meaning: 'Water',
    frequency: 63,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/maa.mp3',
    lessonOrderIndex: 15,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The source of all life',
      body: 'مَاء (Ma\') — the Qur\'an says Allah made every living thing from water. This word appears in some of the most powerful creation verses.',
      quickCheckQuestion: 'What does مَاء (Ma\') mean?',
      quickCheckOptions: ['Water', 'Fire', 'Earth', 'Air'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 16: "Seeing and Sending" ──
  {
    orderIndex: 76,
    arabic: 'رَأَى',
    transliteration: 'Ra\'a',
    meaning: 'to see',
    frequency: 271,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/raa.mp3',
    lessonOrderIndex: 16,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'More than meets the eye',
      body: 'رَأَى (Ra\'a) means "to see." This word isn\'t limited to physical sight — it also means to think, realize, or perceive.',
      factStat: '"Ra\'a" appears 271 times. In the Qur\'an, "Have you not seen?" (alam tara) is a rhetorical device used to make you think. It\'s not asking about your eyes — it\'s asking about your understanding.',
    },
  },
  {
    orderIndex: 77,
    arabic: 'أَنْزَلَ',
    transliteration: 'Anzala',
    meaning: 'to send down, reveal',
    frequency: 183,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/anzala.mp3',
    lessonOrderIndex: 16,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'How the Qur\'an came to us',
      body: 'أَنْزَلَ (Anzala) means "to send down" or "to reveal." This is the word Allah uses for revealing the Qur\'an. The night the Qur\'an was first revealed uses this exact verb.',
      ayahText: 'إِنَّا أَنزَلْنَاهُ فِي لَيْلَةِ الْقَدْرِ',
      ayahRef: 'Al-Qadr 97:1',
    },
  },
  {
    orderIndex: 78,
    arabic: 'أَرْسَلَ',
    transliteration: 'Arsala',
    meaning: 'to send',
    frequency: 130,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/arsala.mp3',
    lessonOrderIndex: 16,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Rasool comes from this root',
      body: 'أَرْسَلَ (Arsala) means "to send." Remember رَسُول (Rasool/Messenger) from Lesson 2? Same root! ر-س-ل. Allah "arsala" (sent) His "rasool" (messenger). When you see the connection between these words, you\'re thinking in Arabic.',
    },
  },
  {
    orderIndex: 79,
    arabic: 'أَخَذَ',
    transliteration: 'Akhadha',
    meaning: 'to take, seize',
    frequency: 127,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/akhadha.mp3',
    lessonOrderIndex: 16,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Taking covenants and taking heed',
      body: 'أَخَذَ (Akhadha) means "to take" or "to seize." The Qur\'an uses this word in many powerful ways — Allah "takes" a covenant from the prophets, He "seizes" wrongdoers in punishment, and He "takes" souls at death. It\'s a word with real weight behind it.',
    },
  },
  {
    orderIndex: 80,
    arabic: 'جَعَلَ',
    transliteration: 'Ja\'ala',
    meaning: 'to make, set',
    frequency: 340,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/jaala.mp3',
    lessonOrderIndex: 16,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'Allah\'s creative word',
      body: 'جَعَلَ (Ja\'ala) — one of the most common verbs in the Qur\'an. Allah "ja\'ala" (made/set) the earth, the night, the stars, and so much more.',
      quickCheckQuestion: 'What does جَعَلَ (Ja\'ala) mean?',
      quickCheckOptions: ['to make / to set', 'to break', 'to find', 'to lose'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 17: "Religion and Identity" ──
  {
    orderIndex: 81,
    arabic: 'دِين',
    transliteration: 'Deen',
    meaning: 'Religion, Way of Life',
    frequency: 92,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/deen.mp3',
    lessonOrderIndex: 17,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'More than just religion',
      body: 'دِين (Deen) means "Religion" or "Way of Life." You know this from "Yawm id-Deen" (Day of Judgment) in Al-Fatiha and from "Lakum deenukum wa liya deen" (To you your religion, and to me mine). In Urdu, deen is the word for faith and way of life.',
    },
  },
  {
    orderIndex: 82,
    arabic: 'كَافِر',
    transliteration: 'Kafir',
    meaning: 'Disbeliever',
    frequency: 119,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/kafir.mp3',
    lessonOrderIndex: 17,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'From the verb you already know',
      body: 'كَافِر (Kafir) means "Disbeliever." Remember كَفَرَ (Kafara/to disbelieve) from Lesson 6? Same root! The Qur\'an has an entire surah called Al-Kafirun (The Disbelievers) — and you can now recognize the root word in its title.',
      ayahText: 'قُلْ يَا أَيُّهَا الْكَافِرُونَ',
      ayahRef: 'Al-Kafirun 109:1',
    },
  },
  {
    orderIndex: 83,
    arabic: 'مُسْلِم',
    transliteration: 'Muslim',
    meaning: 'One who submits',
    frequency: 40,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/muslim.mp3',
    lessonOrderIndex: 17,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Your name for yourself',
      body: 'مُسْلِم (Muslim) means "One who submits" — to Allah\'s will. This is what you call yourself every day. The root is "salama" (to submit, to be at peace), which also gives us "Islam" and "Salam." Being a Muslim means being at peace through submission to Allah.',
    },
  },
  {
    orderIndex: 84,
    arabic: 'مُنَافِق',
    transliteration: 'Munafiq',
    meaning: 'Hypocrite',
    frequency: 27,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/munafiq.mp3',
    lessonOrderIndex: 17,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'A whole surah dedicated to them',
      body: 'مُنَافِق (Munafiq) means "Hypocrite." You use this word in Urdu too.',
      factStat: 'The Qur\'an dedicates an entire surah (Al-Munafiqun) to hypocrites and warns about them more severely than open disbelievers. Why? Because a munafiq says one thing and hides another — the Qur\'an considers hidden betrayal worse than open opposition.',
    },
  },
  {
    orderIndex: 85,
    arabic: 'اتَّقَى',
    transliteration: 'Ittaqa',
    meaning: 'to be God-conscious',
    frequency: 166,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ittaqa.mp3',
    lessonOrderIndex: 17,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The root of Taqwa',
      body: 'اتَّقَى (Ittaqa) — this gives us "taqwa," one of the most important concepts in Islam. The Qur\'an addresses the "muttaqeen" (people of taqwa) again and again.',
      quickCheckQuestion: 'What does اتَّقَى (Ittaqa) mean?',
      quickCheckOptions: ['to be God-conscious', 'to be wealthy', 'to be patient', 'to be generous'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 18: "Giving and Spending" ──
  {
    orderIndex: 86,
    arabic: 'آتَى',
    transliteration: 'Ata',
    meaning: 'to give',
    frequency: 271,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ata.mp3',
    lessonOrderIndex: 18,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Ata karna — giving in Urdu',
      body: 'آتَى (Ata) means "to give." In Urdu, "ata karna" means to grant or bestow — it\'s the same word. The Qur\'an uses this verb when talking about what Allah gives to people: knowledge, wealth, scripture, and authority.',
    },
  },
  {
    orderIndex: 87,
    arabic: 'أَنْفَقَ',
    transliteration: 'Anfaqa',
    meaning: 'to spend (in charity)',
    frequency: 68,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/anfaqa.mp3',
    lessonOrderIndex: 18,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Spend before it\'s too late',
      body: 'أَنْفَقَ (Anfaqa) means "to spend," especially in the way of Allah. The Qur\'an constantly encourages believers to spend from what they\'ve been given — before a day comes when no spending will help.',
      ayahText: 'وَأَنفِقُوا مِمَّا رَزَقْنَاكُم',
      ayahRef: 'Al-Munafiqun 63:10',
    },
  },
  {
    orderIndex: 88,
    arabic: 'فَضْل',
    transliteration: 'Fadl',
    meaning: 'Grace, Bounty',
    frequency: 80,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/fadl.mp3',
    lessonOrderIndex: 18,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Extra — in the best way',
      body: 'فَضْل (Fadl) means "Grace" or "Bounty" — something extra, beyond what\'s deserved. In Urdu, "fazal" or "fazl" carries the same meaning.',
      factStat: 'Allah describes Himself as "Dhul-Fadl al-Azeem" — the Possessor of Great Bounty. The word fadl appears 80 times. When you say "fazl-e-Ilahi" in Urdu, you\'re using this exact Qur\'anic word.',
    },
  },
  {
    orderIndex: 89,
    arabic: 'رَزَقَ',
    transliteration: 'Razaqa',
    meaning: 'to provide',
    frequency: 61,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/razaqa.mp3',
    lessonOrderIndex: 18,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Ar-Razzaq provides everything',
      body: 'رَزَقَ (Razaqa) means "to provide." Remember رِزْق (Rizq/provision) from Lesson 8? Same root! Ar-Razzaq (The Provider) is one of Allah\'s names. Every paycheck, every meal, every breath — it all comes through this verb. When you say "Allah Razzaq hai," you\'re using this word.',
    },
  },
  {
    orderIndex: 90,
    arabic: 'زَكَاة',
    transliteration: 'Zakah',
    meaning: 'Purifying Charity',
    frequency: 32,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/zakah.mp3',
    lessonOrderIndex: 18,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'One of the five pillars',
      body: 'زَكَاة (Zakah) — one of the five pillars of Islam. The word literally means "purification" — giving zakah purifies your wealth.',
      quickCheckQuestion: 'What does زَكَاة (Zakah) mean?',
      quickCheckOptions: ['Purifying Charity', 'Prayer', 'Fasting', 'Pilgrimage'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 19: "Power and Authority" ──
  {
    orderIndex: 91,
    arabic: 'مَلِك',
    transliteration: 'Malik',
    meaning: 'King, Sovereign',
    frequency: 49,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/malik.mp3',
    lessonOrderIndex: 19,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'In your Al-Fatiha, every prayer',
      body: 'مَلِك (Malik) means "King" or "Sovereign." You say "Maliki Yawm id-Deen" (Master of the Day of Judgment) in every rak\'ah. Al-Malik (The King) is one of Allah\'s beautiful names. True sovereignty belongs to Him alone.',
    },
  },
  {
    orderIndex: 92,
    arabic: 'مُلْك',
    transliteration: 'Mulk',
    meaning: 'Dominion, Kingdom',
    frequency: 48,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/mulk.mp3',
    lessonOrderIndex: 19,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Surah Al-Mulk — you probably know it',
      body: 'مُلْك (Mulk) means "Dominion" or "Kingdom." Same root as Malik (King) that you just learned! In Urdu, "mulk" means country. Surah Al-Mulk is one of the most beloved surahs — its name means "The Dominion" or "The Sovereignty."',
    },
  },
  {
    orderIndex: 93,
    arabic: 'قُوَّة',
    transliteration: 'Quwwah',
    meaning: 'Power, Strength',
    frequency: 42,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/quwwah.mp3',
    lessonOrderIndex: 19,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'Real power belongs to Allah',
      body: 'قُوَّة (Quwwah) means "Power" or "Strength." You know "quwwat" from Urdu.',
      factStat: 'The Qur\'an makes a stunning declaration: "All power belongs to Allah entirely" (Al-Baqarah 2:165). The word quwwah appears 42 times, and almost every time it reminds us that human strength is borrowed — real quwwah is Allah\'s alone.',
    },
  },
  {
    orderIndex: 94,
    arabic: 'سُلْطَان',
    transliteration: 'Sultan',
    meaning: 'Authority',
    frequency: 37,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/sultan.mp3',
    lessonOrderIndex: 19,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Not just a title for kings',
      body: 'سُلْطَان (Sultan) means "Authority" or "Clear Proof." In Urdu, sultan means a ruler. But in the Qur\'an, it more often means "authority" or "proof" — as in clear evidence that gives someone the right to speak or act.',
      ayahText: 'مَا أَنزَلَ اللَّهُ بِهَا مِن سُلْطَانٍ',
      ayahRef: 'An-Najm 53:23',
    },
  },
  {
    orderIndex: 95,
    arabic: 'عَرْش',
    transliteration: 'Arsh',
    meaning: 'Throne',
    frequency: 26,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/arsh.mp3',
    lessonOrderIndex: 19,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'The mightiest seat of all',
      body: 'عَرْش (Arsh) — you know "arsh-e-Ilahi" (the Throne of God) from Urdu. Ayat al-Kursi, one of the most memorized ayahs, describes Allah\'s kursi extending over the heavens and earth, and His arsh is even greater.',
      quickCheckQuestion: 'What does عَرْش (Arsh) mean?',
      quickCheckOptions: ['Throne', 'Crown', 'Palace', 'Sky'],
      quickCheckAnswer: 0,
    },
  },

  // ── Lesson 20: "Desire and Will" ──
  {
    orderIndex: 96,
    arabic: 'شَاءَ',
    transliteration: 'Sha\'a',
    meaning: 'to will, to wish',
    frequency: 236,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/shaa.mp3',
    lessonOrderIndex: 20,
    introduction: {
      style: IntroductionStyle.FUN_FACT,
      headline: 'InshaAllah — now you know the root',
      body: 'شَاءَ (Sha\'a) means "to will" or "to wish." You say this word every single day without realizing it.',
      factStat: 'Every time you say "InshaAllah" (if Allah wills), you\'re using this verb: "in" (if) + "sha\'a" (wills) + "Allah." It appears 236 times in the Qur\'an — because nothing happens except by Allah\'s will.',
    },
  },
  {
    orderIndex: 97,
    arabic: 'أَرَادَ',
    transliteration: 'Arada',
    meaning: 'to want, to intend',
    frequency: 139,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/arada.mp3',
    lessonOrderIndex: 20,
    introduction: {
      style: IntroductionStyle.COGNATE,
      headline: 'Irada — willpower in Urdu',
      body: 'أَرَادَ (Arada) means "to want" or "to intend." In Urdu, "irada" means intention or willpower — "mera irada hai" (I intend to). When the Qur\'an says "idha arada shay\'an" (when He intends a thing), it uses this verb right before "kun fayakun" (Be, and it is).',
    },
  },
  {
    orderIndex: 98,
    arabic: 'أَحَبَّ',
    transliteration: 'Ahabba',
    meaning: 'to love',
    frequency: 64,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/ahabba.mp3',
    lessonOrderIndex: 20,
    introduction: {
      style: IntroductionStyle.QURAN_CONTEXT,
      headline: 'Allah loves — and tells you what He loves',
      body: 'أَحَبَّ (Ahabba) means "to love." The Qur\'an doesn\'t just describe Allah as powerful and just — it describes what He loves. "Allah loves those who do good," "Allah loves those who are patient."',
      ayahText: 'قُلْ إِن كُنتُمْ تُحِبُّونَ اللَّهَ فَاتَّبِعُونِي يُحْبِبْكُمُ اللَّهُ',
      ayahRef: 'Al-Imran 3:31',
    },
  },
  {
    orderIndex: 99,
    arabic: 'خَافَ',
    transliteration: 'Khafa',
    meaning: 'to fear',
    frequency: 83,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/khafa.mp3',
    lessonOrderIndex: 20,
    introduction: {
      style: IntroductionStyle.LIFE_CONNECTION,
      headline: 'Khauf and khashiyat — you know these',
      body: 'خَافَ (Khafa) means "to fear." In Urdu, "khauf" (fear) comes from this root. The Qur\'an talks about two kinds of fear — the fear of worldly things (which believers should overcome) and the fear of Allah (which is actually a sign of wisdom and closeness to Him).',
    },
  },
  {
    orderIndex: 100,
    arabic: 'رَضِيَ',
    transliteration: 'Radiya',
    meaning: 'to be pleased',
    frequency: 38,
    audioUrl: 'https://pub-5c2533d63fce46da8ebdcbe7cc5fe339.r2.dev/words/radiya.mp3',
    lessonOrderIndex: 20,
    introduction: {
      style: IntroductionStyle.QUICK_CHECK,
      headline: 'RadhiAllahu anhu — you say this all the time',
      body: 'رَضِيَ (Radiya) — every time you say "RadhiAllahu anhu" (may Allah be pleased with him) after a companion\'s name, you\'re using this verb. Your 100th word!',
      quickCheckQuestion: 'What does رَضِيَ (Radiya) mean?',
      quickCheckOptions: ['to be pleased', 'to be angry', 'to be surprised', 'to be patient'],
      quickCheckAnswer: 0,
    },
  },
];
